// Quiz Level 9: Drinken - Cocktails (Master-Level Cocktail Expertise & Innovation)
(function() {
  const level9 = {
    name: {
      en: "Master-Level Cocktail Expertise & Innovation",
      es: "Experiencia e Innovación de Cócteles a Nivel Maestro",
      de: "Meisterschafts-Cocktail-Expertise & Innovation",
      nl: "Meester-Level Cocktail Expertise & Innovatie"
    },
    questions: [
      {
        question: {
          en: "What is 'sous vide' cocktail preparation and how does it differ from traditional infusion methods?",
          es: "¿Qué es la preparación de cócteles 'sous vide' y cómo difiere de los métodos tradicionales de infusión?",
          de: "Was ist 'Sous Vide' Cocktail-Zubereitung und wie unterscheidet sie sich von traditionellen Infusionsmethoden?",
          nl: "Wat is 'sous vide' cocktailbereiding en hoe verschilt het van traditionele infusiemethoden?"
        },
        options: [
          { en: "Vacuum-sealed controlled temperature infusion allowing precise extraction without degradation", es: "Infusión a temperatura controlada sellada al vacío permitiendo extracción precisa sin degradación", de: "Vakuumversiegelte kontrollierte Temperatur-Infusion ermöglicht präzise Extraktion ohne Abbau", nl: "Vacuüm verzegelde gecontroleerde temperatuur infusie die precieze extractie mogelijk maakt zonder degradatie" },
          { en: "French cooking method using only wine", es: "Método de cocina francés usando solo vino", de: "Französische Kochmethode nur mit Wein", nl: "Franse kookmethode met alleen wijn" },
          { en: "Cold brewing technique below 5°C", es: "Técnica de preparación fría por debajo de 5°C", de: "Kaltbrühverfahren unter 5°C", nl: "Koude brew techniek onder 5°C" },
          { en: "Traditional shaking method from France", es: "Método de agitado tradicional de Francia", de: "Traditionelle Schüttelmethode aus Frankreich", nl: "Traditionele schudmethode uit Frankrijk" }
        ],
        correct: 0,
        explanation: {
          en: "Sous vide cocktail preparation involves vacuum-sealing ingredients with spirits or other liquids and heating them at precisely controlled low temperatures (typically 55-65°C) for extended periods. This technique allows for rapid, consistent infusions while preventing alcohol evaporation and ingredient degradation that occurs with traditional heating. It enables complex flavor extractions from delicate ingredients like herbs, fruits, or spices in hours rather than days or weeks. The controlled environment ensures reproducible results and can create flavors impossible through conventional methods.",
          es: "La preparación de cócteles sous vide implica sellar al vacío ingredientes con licores u otros líquidos y calentarlos a temperaturas bajas precisamente controladas (típicamente 55-65°C) por períodos extendidos. Esta técnica permite infusiones rápidas y consistentes mientras previene evaporación del alcohol y degradación de ingredientes que ocurre con calentamiento tradicional. Permite extracciones de sabor complejas de ingredientes delicados como hierbas, frutas o especias en horas en lugar de días o semanas. El ambiente controlado asegura resultados reproducibles y puede crear sabores imposibles a través de métodos convencionales.",
          de: "Sous Vide Cocktail-Zubereitung beinhaltet Vakuumversiegelung von Zutaten mit Spirituosen oder anderen Flüssigkeiten und Erhitzung bei präzise kontrollierten niedrigen Temperaturen (typisch 55-65°C) für längere Zeiträume. Diese Technik ermöglicht schnelle, konsistente Infusionen während Alkoholverdampfung und Zutatenzersetzung verhindert wird, die bei traditioneller Erhitzung auftritt. Sie ermöglicht komplexe Geschmacksextraktionen aus empfindlichen Zutaten wie Kräutern, Früchten oder Gewürzen in Stunden statt Tagen oder Wochen. Die kontrollierte Umgebung gewährleistet reproduzierbare Ergebnisse und kann Aromen schaffen, die durch konventionelle Methoden unmöglich sind.",
          nl: "Sous vide cocktailbereiding houdt in dat ingrediënten vacuüm worden verzegeld met sterke dranken of andere vloeistoffen en verwarmd bij precies gecontroleerde lage temperaturen (typisch 55-65°C) voor langere perioden. Deze techniek maakt snelle, consistente infusies mogelijk terwijl alcoholverdamping en ingrediënt degradatie wordt voorkomen die optreedt bij traditionele verwarming. Het maakt complexe smaakextracties mogelijk van delicate ingrediënten zoals kruiden, fruit of specerijen in uren in plaats van dagen of weken. De gecontroleerde omgeving verzekert reproduceerbare resultaten en kan smaken creëren die onmogelijk zijn door conventionele methoden."
        }
      },
      {
        question: {
          en: "What is 'rotary evaporation' (rotavap) in cocktail ingredient preparation?",
          es: "¿Qué es la 'evaporación rotatoria' (rotavap) en la preparación de ingredientes para cócteles?",
          de: "Was ist 'Rotationsverdampfung' (Rotavap) in der Cocktail-Zutatenvorbereitung?",
          nl: "Wat is 'rotatie verdamping' (rotavap) in cocktail ingrediënt voorbereiding?"
        },
        options: [
          { en: "Vacuum distillation at low temperatures to separate and concentrate volatile compounds", es: "Destilación al vacío a bajas temperaturas para separar y concentrar compuestos volátiles", de: "Vakuumdestillation bei niedrigen Temperaturen zur Trennung und Konzentration flüchtiger Verbindungen", nl: "Vacuüm distillatie bij lage temperaturen om vluchtige verbindingen te scheiden en concentreren" },
          { en: "Spinning cocktail shakers for better mixing", es: "Girar cocteleras para mejor mezcla", de: "Cocktail-Shaker drehen für besseres Mischen", nl: "Cocktail shakers draaien voor beter mengen" },
          { en: "Rotating garnishes for presentation", es: "Rotar guarniciones para presentación", de: "Garnituren für Präsentation rotieren", nl: "Garneringen roteren voor presentatie" },
          { en: "Circular motion stirring technique", es: "Técnica de revolver con movimiento circular", de: "Kreisbewegung-Rührtechnik", nl: "Circulaire beweging roertechniek" }
        ],
        correct: 0,
        explanation: {
          en: "Rotary evaporation uses vacuum distillation at reduced pressures and temperatures to gently separate volatile compounds from liquids. In cocktail applications, this allows bartenders to capture delicate aromatic compounds from fruits, herbs, or other ingredients without heat damage. The process can create highly concentrated essences, distilled spirits variations, or even 'impossible' combinations like clear fruit essences. Rotavap enables isolation of specific flavor components, creation of layered taste experiences, and development of unique ingredients that would be impossible through traditional methods.",
          es: "La evaporación rotatoria usa destilación al vacío a presiones y temperaturas reducidas para separar suavemente compuestos volátiles de líquidos. En aplicaciones de cócteles, esto permite a los bartenders capturar compuestos aromáticos delicados de frutas, hierbas u otros ingredientes sin daño por calor. El proceso puede crear esencias altamente concentradas, variaciones de licores destilados o incluso combinaciones 'imposibles' como esencias de frutas claras. Rotavap permite aislamiento de componentes de sabor específicos, creación de experiencias de sabor en capas y desarrollo de ingredientes únicos que serían imposibles a través de métodos tradicionales.",
          de: "Rotationsverdampfung verwendet Vakuumdestillation bei reduzierten Drücken und Temperaturen zur sanften Trennung flüchtiger Verbindungen aus Flüssigkeiten. In Cocktail-Anwendungen ermöglicht dies Bartendern, empfindliche aromatische Verbindungen aus Früchten, Kräutern oder anderen Zutaten ohne Hitzeschäden einzufangen. Der Prozess kann hochkonzentrierte Essenzen, destillierte Spirituosenvariationen oder sogar 'unmögliche' Kombinationen wie klare Fruchtessenzen schaffen. Rotavap ermöglicht Isolation spezifischer Geschmackskomponenten, Schaffung geschichteter Geschmackserfahrungen und Entwicklung einzigartiger Zutaten, die durch traditionelle Methoden unmöglich wären.",
          nl: "Rotatie verdamping gebruikt vacuüm distillatie bij verminderde drukken en temperaturen om vluchtige verbindingen zachtjes te scheiden van vloeistoffen. In cocktail toepassingen stelt dit bartenders in staat delicate aromatische verbindingen te vangen van fruit, kruiden of andere ingrediënten zonder hitteschade. Het proces kan zeer geconcentreerde essences creëren, gedistilleerde sterke dranken variaties of zelfs 'onmogelijke' combinaties zoals heldere fruitessences. Rotavap maakt isolatie van specifieke smaakcomponenten mogelijk, creatie van gelaagde smaakervaringen en ontwikkeling van unieke ingrediënten die onmogelijk zouden zijn door traditionele methoden."
        }
      },
      {
        question: {
          en: "What is 'liquid nitrogen' used for in molecular mixology and what safety considerations apply?",
          es: "¿Para qué se usa el 'nitrógeno líquido' en mixología molecular y qué consideraciones de seguridad se aplican?",
          de: "Wofür wird 'flüssiger Stickstoff' in der molekularen Mixologie verwendet und welche Sicherheitsüberlegungen gelten?",
          nl: "Waarvoor wordt 'vloeibare stikstof' gebruikt in moleculaire mixologie en welke veiligheidsoverwegingen gelden?"
        },
        options: [
          { en: "Flash-freezing for texture effects and dramatic presentation, requires proper ventilation and safety equipment", es: "Congelación instantánea para efectos de textura y presentación dramática, requiere ventilación apropiada y equipo de seguridad", de: "Schockgefrieren für Textureffekte und dramatische Präsentation, erfordert ordnungsgemäße Belüftung und Sicherheitsausrüstung", nl: "Flash-vriezen voor textuureffecten en dramatische presentatie, vereist juiste ventilatie en veiligheidsuitrusting" },
          { en: "Adding nitrogen flavor to cocktails", es: "Añadir sabor de nitrógeno a cócteles", de: "Stickstoffgeschmack zu Cocktails hinzufügen", nl: "Stikstof smaak toevoegen aan cocktails" },
          { en: "Carbonating drinks naturally", es: "Carbonatar bebidas naturalmente", de: "Getränke natürlich karbonisieren", nl: "Drankjes natuurlijk koolzuur geven" },
          { en: "Preserving cocktails for weeks", es: "Conservar cócteles por semanas", de: "Cocktails wochenlang konservieren", nl: "Cocktails weken bewaren" }
        ],
        correct: 0,
        explanation: {
          en: "Liquid nitrogen (-196°C/-321°F) is used in molecular mixology for instant freezing effects, creating unique textures like frozen mousses, shattered cocktail elements, or smoking presentations. It can freeze cocktail components instantly, create dramatic vapor effects, or make 'caviar' pearls from liquids. However, it requires extreme safety precautions: proper ventilation (nitrogen displacement can cause asphyxiation), insulated gloves, eye protection, and ensuring all liquid nitrogen evaporates before consumption. Only food-grade liquid nitrogen should be used, and bartenders need specialized training for safe handling.",
          es: "El nitrógeno líquido (-196°C/-321°F) se usa en mixología molecular para efectos de congelación instantánea, creando texturas únicas como mousses congelados, elementos de cóctel fragmentados o presentaciones humeantes. Puede congelar componentes de cócteles instantáneamente, crear efectos dramáticos de vapor o hacer perlas 'caviar' de líquidos. Sin embargo, requiere precauciones de seguridad extremas: ventilación apropiada (el desplazamiento de nitrógeno puede causar asfixia), guantes aislados, protección ocular y asegurar que todo el nitrógeno líquido se evapore antes del consumo. Solo debe usarse nitrógeno líquido grado alimentario, y los bartenders necesitan entrenamiento especializado para manejo seguro.",
          de: "Flüssiger Stickstoff (-196°C/-321°F) wird in molekularer Mixologie für Sofortgefriereffekte verwendet, schafft einzigartige Texturen wie gefrorene Mousses, zerbrochene Cocktail-Elemente oder rauchende Präsentationen. Er kann Cocktail-Komponenten sofort einfrieren, dramatische Dampfeffekte erzeugen oder 'Kaviar'-Perlen aus Flüssigkeiten machen. Er erfordert jedoch extreme Sicherheitsvorkehrungen: ordnungsgemäße Belüftung (Stickstoffverdrängung kann Erstickung verursachen), isolierte Handschuhe, Augenschutz und Sicherstellung, dass aller flüssige Stickstoff vor Verzehr verdampft. Nur lebensmittelechter flüssiger Stickstoff sollte verwendet werden, und Bartender benötigen spezialisierte Schulung für sicheren Umgang.",
          nl: "Vloeibare stikstof (-196°C/-321°F) wordt gebruikt in moleculaire mixologie voor directe vrieseffecten, wat unieke texturen creëert zoals bevroren mousses, verbrijzelde cocktail elementen of rokende presentaties. Het kan cocktail componenten direct bevriezen, dramatische dampeffecten creëren of 'kaviaar' parels maken van vloeistoffen. Het vereist echter extreme veiligheidsvoorzorgen: juiste ventilatie (stikstof verplaatsing kan verstikking veroorzaken), geïsoleerde handschoenen, oogbescherming en ervoor zorgen dat alle vloeibare stikstof verdampt voor consumptie. Alleen voedselkwaliteit vloeibare stikstof moet worden gebruikt, en bartenders hebben gespecialiseerde training nodig voor veilige hantering."
        }
      },
      {
        question: {
          en: "What is 'fermentation' in cocktail ingredients and how do bartenders control the process?",
          es: "¿Qué es la 'fermentación' en ingredientes de cócteles y cómo controlan los bartenders el proceso?",
          de: "Was ist 'Fermentation' in Cocktail-Zutaten und wie kontrollieren Bartender den Prozess?",
          nl: "Wat is 'fermentatie' in cocktail ingrediënten en hoe controleren bartenders het proces?"
        },
        options: [
          { en: "Controlled microbial transformation creating complex flavors through pH, temperature, and time management", es: "Transformación microbiana controlada creando sabores complejos a través de manejo de pH, temperatura y tiempo", de: "Kontrollierte mikrobielle Transformation, die komplexe Aromen durch pH-, Temperatur- und Zeitmanagement schafft", nl: "Gecontroleerde microbiële transformatie die complexe smaken creëert door pH-, temperatuur- en tijdbeheer" },
          { en: "Adding yeast to any cocktail", es: "Añadir levadura a cualquier cóctel", de: "Hefe zu jedem Cocktail hinzufügen", nl: "Gist toevoegen aan elke cocktail" },
          { en: "Aging spirits in barrels only", es: "Envejecer licores solo en barricas", de: "Spirituosen nur in Fässern reifen", nl: "Sterke dranken alleen in vaten rijpen" },
          { en: "Natural spoilage of ingredients", es: "Deterioro natural de ingredientes", de: "Natürlicher Verderb von Zutaten", nl: "Natuurlijk bederf van ingrediënten" }
        ],
        correct: 0,
        explanation: {
          en: "Controlled fermentation in cocktail preparation involves deliberately cultivating beneficial microorganisms (yeasts, bacteria, or koji) to transform ingredients and create complex flavors. Bartenders control fermentation through precise pH monitoring (typically 3.5-4.5), temperature regulation (varies by organism), timing (hours to weeks), and ingredient selection. This can create fermented fruit cordials, vegetable-based cocktail components, kombucha-style mixers, or even fermented garnishes. The process requires understanding of food safety, sterile technique, and microbiology to prevent harmful bacteria while encouraging desired flavors.",
          es: "La fermentación controlada en preparación de cócteles implica cultivar deliberadamente microorganismos beneficiosos (levaduras, bacterias o koji) para transformar ingredientes y crear sabores complejos. Los bartenders controlan la fermentación a través de monitoreo preciso del pH (típicamente 3.5-4.5), regulación de temperatura (varía por organismo), tiempo (horas a semanas) y selección de ingredientes. Esto puede crear cordiales de frutas fermentadas, componentes de cócteles basados en vegetales, mezcladores estilo kombucha o incluso guarniciones fermentadas. El proceso requiere entendimiento de seguridad alimentaria, técnica estéril y microbiología para prevenir bacterias dañinas mientras se fomentan sabores deseados.",
          de: "Kontrollierte Fermentation in Cocktail-Zubereitung beinhaltet bewusste Kultivierung nützlicher Mikroorganismen (Hefen, Bakterien oder Koji) zur Transformation von Zutaten und Schaffung komplexer Aromen. Bartender kontrollieren Fermentation durch präzise pH-Überwachung (typisch 3,5-4,5), Temperaturregulierung (variiert je Organismus), Timing (Stunden bis Wochen) und Zutatenselektion. Dies kann fermentierte Fruchtsiruppe, gemüsebasierte Cocktail-Komponenten, Kombucha-Style-Mixer oder sogar fermentierte Garnituren schaffen. Der Prozess erfordert Verständnis von Lebensmittelsicherheit, steriler Technik und Mikrobiologie zur Verhinderung schädlicher Bakterien während Förderung gewünschter Aromen.",
          nl: "Gecontroleerde fermentatie in cocktailbereiding houdt in dat opzettelijk gunstige micro-organismen (gisten, bacteriën of koji) worden gekweekt om ingrediënten te transformeren en complexe smaken te creëren. Bartenders controleren fermentatie door precieze pH monitoring (typisch 3,5-4,5), temperatuurregulatie (varieert per organisme), timing (uren tot weken) en ingrediënt selectie. Dit kan gefermenteerde fruitcordials creëren, groente-gebaseerde cocktail componenten, kombucha-stijl mixers of zelfs gefermenteerde garneringen. Het proces vereist begrip van voedselveiligheid, steriele techniek en microbiologie om schadelijke bacteriën te voorkomen terwijl gewenste smaken worden aangemoedigd."
        }
      },
      {
        question: {
          en: "What is 'ultrasonic extraction' and how does it revolutionize cocktail ingredient preparation?",
          es: "¿Qué es la 'extracción ultrasónica' y cómo revoluciona la preparación de ingredientes para cócteles?",
          de: "Was ist 'Ultraschallextraktion' und wie revolutioniert sie die Cocktail-Zutatenvorbereitung?",
          nl: "Wat is 'ultrasone extractie' en hoe revolutioneert het cocktail ingrediënt voorbereiding?"
        },
        options: [
          { en: "High-frequency sound waves rapidly extract flavors and compounds in minutes instead of hours or days", es: "Ondas de sonido de alta frecuencia extraen rápidamente sabores y compuestos en minutos en lugar de horas o días", de: "Hochfrequente Schallwellen extrahieren schnell Aromen und Verbindungen in Minuten statt Stunden oder Tagen", nl: "Hoogfrequente geluidsgolven extraheren snel smaken en verbindingen in minuten in plaats van uren of dagen" },
          { en: "Using ultrasonic shakers for better mixing", es: "Usar agitadores ultrasónicos para mejor mezcla", de: "Ultraschall-Shaker für besseres Mischen verwenden", nl: "Ultrasone shakers gebruiken voor beter mengen" },
          { en: "Playing ultrasonic music during preparation", es: "Tocar música ultrasónica durante la preparación", de: "Ultraschallmusik während der Zubereitung spielen", nl: "Ultrasone muziek afspelen tijdens bereiding" },
          { en: "Cleaning equipment with ultrasonic waves", es: "Limpiar equipo con ondas ultrasónicas", de: "Ausrüstung mit Ultraschallwellen reinigen", nl: "Apparatuur reinigen met ultrasone golven" }
        ],
        correct: 0,
        explanation: {
          en: "Ultrasonic extraction uses high-frequency sound waves (20-40 kHz) to create cavitation bubbles in liquids, which rapidly break down cellular structures and extract flavors, essential oils, and other compounds. This technique can achieve in 5-15 minutes what traditional infusion takes hours or days to accomplish. The mechanical action is gentle enough to preserve delicate volatile compounds while being powerful enough to extract deep flavors from tough materials like woody herbs or citrus peels. It's particularly valuable for creating consistent, rapid infusions for high-volume cocktail operations or experimental flavor development.",
          es: "La extracción ultrasónica usa ondas de sonido de alta frecuencia (20-40 kHz) para crear burbujas de cavitación en líquidos, que rápidamente descomponen estructuras celulares y extraen sabores, aceites esenciales y otros compuestos. Esta técnica puede lograr en 5-15 minutos lo que la infusión tradicional toma horas o días en realizar. La acción mecánica es suficientemente suave para preservar compuestos volátiles delicados mientras es suficientemente poderosa para extraer sabores profundos de materiales duros como hierbas leñosas o cáscaras cítricas. Es particularmente valiosa para crear infusiones consistentes y rápidas para operaciones de cócteles de alto volumen o desarrollo experimental de sabores.",
          de: "Ultraschallextraktion verwendet hochfrequente Schallwellen (20-40 kHz) zur Erzeugung von Kavitationsblasen in Flüssigkeiten, die schnell Zellstrukturen aufbrechen und Aromen, ätherische Öle und andere Verbindungen extrahieren. Diese Technik kann in 5-15 Minuten erreichen, was traditionelle Infusion Stunden oder Tage benötigt. Die mechanische Wirkung ist sanft genug, um empfindliche flüchtige Verbindungen zu bewahren, während sie kraftvoll genug ist, um tiefe Aromen aus harten Materialien wie holzigen Kräutern oder Zitrusschalen zu extrahieren. Sie ist besonders wertvoll für konsistente, schnelle Infusionen in hochvolumigen Cocktail-Operationen oder experimenteller Geschmacksentwicklung.",
          nl: "Ultrasone extractie gebruikt hoogfrequente geluidsgolven (20-40 kHz) om cavitatie bellen in vloeistoffen te creëren, die snel cellulaire structuren afbreken en smaken, essentiële oliën en andere verbindingen extraheren. Deze techniek kan in 5-15 minuten bereiken wat traditionele infusie uren of dagen kost. De mechanische actie is zacht genoeg om delicate vluchtige verbindingen te behouden terwijl het krachtig genoeg is om diepe smaken te extraheren uit harde materialen zoals houtige kruiden of citrusschillen. Het is bijzonder waardevol voor het creëren van consistente, snelle infusies voor hoog-volume cocktail operaties of experimentele smaakontwikkeling."
        }
      },
      {
        question: {
          en: "What is 'encapsulation' technology in modern cocktail garnishes and mixers?",
          es: "¿Qué es la tecnología de 'encapsulación' en guarniciones y mezcladores modernos de cócteles?",
          de: "Was ist 'Verkapselungs'-Technologie in modernen Cocktail-Garnituren und -Mixern?",
          nl: "Wat is 'inkapseling' technologie in moderne cocktail garneringen en mixers?"
        },
        options: [
          { en: "Creating liquid-filled spheres that burst with flavor using calcium chloride and sodium alginate", es: "Crear esferas llenas de líquido que explotan con sabor usando cloruro de calcio y alginato de sodio", de: "Flüssigkeitsgefüllte Kugeln schaffen, die mit Geschmack platzen, mit Calciumchlorid und Natriumalginat", nl: "Vloeistof-gevulde bollen creëren die barsten met smaak met calciumchloride en natriumalginaat" },
          { en: "Putting cocktails in capsules", es: "Poner cócteles en cápsulas", de: "Cocktails in Kapseln packen", nl: "Cocktails in capsules doen" },
          { en: "Using pill bottles for serving", es: "Usar frascos de pastillas para servir", de: "Pillenflaschen zum Servieren verwenden", nl: "Pil flesjes gebruiken voor serveren" },
          { en: "Wrapping garnishes in plastic", es: "Envolver guarniciones en plástico", de: "Garnituren in Plastik einwickeln", nl: "Garneringen in plastic wikkelen" }
        ],
        correct: 0,
        explanation: {
          en: "Encapsulation in cocktails primarily uses spherification - a molecular gastronomy technique creating liquid-filled spheres with gel membranes. The basic spherification uses sodium alginate and calcium chloride to form caviar-like pearls or larger 'ravioli' spheres containing cocktail liquids. When bitten, these spheres burst with concentrated flavors. Reverse spherification can create larger spheres with liquid centers. This technology allows bartenders to create surprising textural elements, concentrated flavor bombs, or interactive garnishes that transform the drinking experience through unexpected taste releases.",
          es: "La encapsulación en cócteles usa principalmente esferificación - una técnica de gastronomía molecular creando esferas llenas de líquido con membranas de gel. La esferificación básica usa alginato de sodio y cloruro de calcio para formar perlas similares al caviar o esferas 'ravioli' más grandes conteniendo líquidos de cóctel. Al morderlas, estas esferas explotan con sabores concentrados. La esferificación inversa puede crear esferas más grandes con centros líquidos. Esta tecnología permite a los bartenders crear elementos texturales sorprendentes, bombas de sabor concentradas o guarniciones interactivas que transforman la experiencia de bebida a través de liberaciones de sabor inesperadas.",
          de: "Verkapselung in Cocktails verwendet hauptsächlich Sphärifizierung - eine molekulargastronomische Technik zur Schaffung flüssigkeitsgefüllter Kugeln mit Gelmembranen. Die grundlegende Sphärifizierung verwendet Natriumalginat und Calciumchlorid zur Bildung kaviarähnlicher Perlen oder größerer 'Ravioli'-Kugeln mit Cocktail-Flüssigkeiten. Beim Beißen platzen diese Kugeln mit konzentrierten Aromen. Umgekehrte Sphärifizierung kann größere Kugeln mit flüssigen Zentren schaffen. Diese Technologie ermöglicht Bartendern, überraschende Texturelemente, konzentrierte Geschmacksbomben oder interaktive Garnituren zu schaffen, die das Trinkerlebnis durch unerwartete Geschmacksfreisetzungen transformieren.",
          nl: "Inkapseling in cocktails gebruikt voornamelijk spherificatie - een moleculair gastronomie techniek die vloeistof-gevulde bollen creëert met gel membranen. De basis spherificatie gebruikt natriumalginaat en calciumchloride om kaviaar-achtige parels te vormen of grotere 'ravioli' bollen met cocktail vloeistoffen. Wanneer gebeten, barsten deze bollen met geconcentreerde smaken. Omgekeerde spherificatie kan grotere bollen creëren met vloeibare centra. Deze technologie stelt bartenders in staat verrassende textuur elementen te creëren, geconcentreerde smaakbommen of interactieve garneringen die de drinkervaring transformeren door onverwachte smaak vrijgaves."
        }
      },
      {
        question: {
          en: "What is 'smoke capture and infusion' technology in cocktail presentation?",
          es: "¿Qué es la tecnología de 'captura e infusión de humo' en la presentación de cócteles?",
          de: "Was ist 'Rauchfang und -infusions'-Technologie in der Cocktail-Präsentation?",
          nl: "Wat is 'rook opvang en infusie' technologie in cocktail presentatie?"
        },
        options: [
          { en: "Controlled smoking using wood chips, aromatic herbs, or spices to infuse cocktails with smoke flavors", es: "Ahumado controlado usando astillas de madera, hierbas aromáticas o especias para infundir cócteles con sabores ahumados", de: "Kontrolliertes Räuchern mit Holzspänen, aromatischen Kräutern oder Gewürzen zur Rauchinfusion in Cocktails", nl: "Gecontroleerd roken met houtspaanders, aromatische kruiden of specerijen om cocktails te infuseren met rooksmaak" },
          { en: "Capturing cigarette smoke for cocktails", es: "Capturar humo de cigarrillos para cócteles", de: "Zigarettenrauch für Cocktails einfangen", nl: "Sigarettenrook vangen voor cocktails" },
          { en: "Using dry ice for visual effects only", es: "Usar hielo seco solo para efectos visuales", de: "Trockeneis nur für visuelle Effekte verwenden", nl: "Droogijs gebruiken alleen voor visuele effecten" },
          { en: "Industrial smoke machines for bars", es: "Máquinas de humo industriales para bares", de: "Industrielle Nebelmaschinen für Bars", nl: "Industriële rookmachines voor bars" }
        ],
        correct: 0,
        explanation: {
          en: "Smoke capture and infusion involves controlled combustion of aromatic materials (wood chips like applewood or cherry, herbs like rosemary or thyme, spices like cinnamon or star anise) to create flavored smoke that's captured under glass cloches, in smoking boxes, or through specialized equipment. The smoke infuses the cocktail with aromatic compounds, adding complexity and theatrical presentation. Techniques include smoking the glass beforehand, trapping smoke with the drink, or using smoking guns. Safety requires proper ventilation, food-grade materials only, and understanding which materials are safe for consumption.",
          es: "La captura e infusión de humo implica combustión controlada de materiales aromáticos (astillas de madera como manzano o cerezo, hierbas como romero o tomillo, especias como canela o anís estrellado) para crear humo saborizado que se captura bajo campanas de vidrio, en cajas de ahumado o a través de equipo especializado. El humo infunde el cóctel con compuestos aromáticos, añadiendo complejidad y presentación teatral. Las técnicas incluyen ahumar el vaso previamente, atrapar humo con la bebida o usar pistolas de humo. La seguridad requiere ventilación apropiada, solo materiales grado alimentario y entender qué materiales son seguros para consumo.",
          de: "Rauchfang und -infusion beinhaltet kontrollierte Verbrennung aromatischer Materialien (Holzspäne wie Apfel- oder Kirschholz, Kräuter wie Rosmarin oder Thymian, Gewürze wie Zimt oder Sternanis) zur Erzeugung von aromatisiertem Rauch, der unter Glasglocken, in Rauchboxen oder durch spezialisierte Ausrüstung gefangen wird. Der Rauch infundiert den Cocktail mit aromatischen Verbindungen und fügt Komplexität und theatralische Präsentation hinzu. Techniken umfassen Vorraucherung des Glases, Rauchfang mit dem Getränk oder Verwendung von Rauchpistolen. Sicherheit erfordert ordnungsgemäße Belüftung, nur lebensmittelechte Materialien und Verständnis, welche Materialien für Verzehr sicher sind.",
          nl: "Rook opvang en infusie houdt gecontroleerde verbranding in van aromatische materialen (houtspaanders zoals appel- of kersenhout, kruiden zoals rozemarijn of tijm, specerijen zoals kaneel of steranijs) om gearomatiseerde rook te creëren die wordt opgevangen onder glazen stolpen, in rookboxen of door gespecialiseerde apparatuur. De rook infuseert de cocktail met aromatische verbindingen, wat complexiteit en theatrale presentatie toevoegt. Technieken omvatten het glas vooraf roken, rook vangen met de drank of rookpistolen gebruiken. Veiligheid vereist juiste ventilatie, alleen voedselkwaliteit materialen en begrip welke materialen veilig zijn voor consumptie."
        }
      },
      {
        question: {
          en: "What is 'precision dilution' and how do professional bartenders calculate optimal water ratios?",
          es: "¿Qué es la 'dilución de precisión' y cómo calculan los bartenders profesionales las proporciones óptimas de agua?",
          de: "Was ist 'Präzisionsverdünnung' und wie berechnen professionelle Bartender optimale Wasserverhältnisse?",
          nl: "Wat is 'precisie verdunning' en hoe berekenen professionele bartenders optimale waterverhoudingen?"
        },
        options: [
          { en: "Mathematical calculation of exact water amounts to achieve target alcohol percentage and flavor balance", es: "Cálculo matemático de cantidades exactas de agua para lograr porcentaje objetivo de alcohol y equilibrio de sabor", de: "Mathematische Berechnung exakter Wassermengen zur Erreichung des Ziel-Alkoholprozentsatzes und Geschmacksgleichgewichts", nl: "Wiskundige berekening van exacte waterhoeveelheden om doelalcoholpercentage en smaakbalans te bereiken" },
          { en: "Adding random amounts of water", es: "Añadir cantidades aleatorias de agua", de: "Zufällige Wassermengen hinzufügen", nl: "Willekeurige hoeveelheden water toevoegen" },
          { en: "Using only ice for dilution", es: "Usar solo hielo para dilución", de: "Nur Eis für Verdünnung verwenden", nl: "Alleen ijs gebruiken voor verdunning" },
          { en: "Diluting all cocktails to 20% alcohol", es: "Diluir todos los cócteles a 20% alcohol", de: "Alle Cocktails auf 20% Alkohol verdünnen", nl: "Alle cocktails verdunnen tot 20% alcohol" }
        ],
        correct: 0,
        explanation: {
          en: "Precision dilution involves calculating exact water amounts to achieve specific alcohol percentages and optimal flavor balance in cocktails. Professional bartenders use formulas considering initial spirit proof, desired final proof, and total volume to determine precise dilution ratios. For example, to reduce a 40% ABV spirit to 25% in a 100ml cocktail requires approximately 60ml of the original spirit plus 40ml of water/other ingredients. This technique ensures consistent results, proper flavor integration, and replicatable cocktails. It's particularly important for batched cocktails, spirit-forward drinks, and maintaining consistency across different base spirit proofs.",
          es: "La dilución de precisión implica calcular cantidades exactas de agua para lograr porcentajes específicos de alcohol y equilibrio óptimo de sabor en cócteles. Los bartenders profesionales usan fórmulas considerando graduación inicial del licor, graduación final deseada y volumen total para determinar proporciones precisas de dilución. Por ejemplo, para reducir un licor de 40% ABV a 25% en un cóctel de 100ml requiere aproximadamente 60ml del licor original más 40ml de agua/otros ingredientes. Esta técnica asegura resultados consistentes, integración apropiada de sabor y cócteles replicables. Es particularmente importante para cócteles loteados, bebidas con predominio de licor y mantener consistencia a través de diferentes graduaciones de licores base.",
          de: "Präzisionsverdünnung beinhaltet Berechnung exakter Wassermengen zur Erreichung spezifischer Alkoholprozentsätze und optimaler Geschmacksbalance in Cocktails. Professionelle Bartender verwenden Formeln unter Berücksichtigung des anfänglichen Spirituosen-Proofs, gewünschten End-Proofs und Gesamtvolumens zur Bestimmung präziser Verdünnungsverhältnisse. Zum Beispiel erfordert die Reduzierung einer 40% ABV Spirituose auf 25% in einem 100ml Cocktail etwa 60ml der ursprünglichen Spirituose plus 40ml Wasser/andere Zutaten. Diese Technik gewährleistet konsistente Ergebnisse, ordnungsgemäße Geschmacksintegration und reproduzierbare Cocktails. Sie ist besonders wichtig für Batch-Cocktails, spirituosenbetonte Getränke und Konsistenzerhaltung über verschiedene Basis-Spirituosen-Proofs.",
          nl: "Precisie verdunning houdt in dat exacte waterhoeveelheden worden berekend om specifieke alcoholpercentages en optimale smaakbalans in cocktails te bereiken. Professionele bartenders gebruiken formules die rekening houden met initiële sterke drank proof, gewenste finale proof en totaal volume om precieze verdunningsverhoudingen te bepalen. Bijvoorbeeld, om een 40% ABV sterke drank te reduceren naar 25% in een 100ml cocktail vereist ongeveer 60ml van de originele sterke drank plus 40ml water/andere ingrediënten. Deze techniek verzekert consistente resultaten, juiste smaakintegratie en repliceerbare cocktails. Het is bijzonder belangrijk voor batch cocktails, sterke drank-gerichte drankjes en consistentie behouden over verschillende basis sterke drank proofs."
        }
      },
      {
        question: {
          en: "What is 'umami integration' in cocktail flavor profiling?",
          es: "¿Qué es la 'integración umami' en el perfilado de sabor de cócteles?",
          de: "Was ist 'Umami-Integration' in der Cocktail-Geschmacksprofilierung?",
          nl: "Wat is 'umami integratie' in cocktail smaakprofilering?"
        },
        options: [
          { en: "Incorporating savory, meaty, or mushroom-like flavors to add depth and complexity beyond sweet, sour, bitter, and salty", es: "Incorporar sabores salados, carnosos o similares a hongos para añadir profundidad y complejidad más allá de dulce, agrio, amargo y salado", de: "Einbindung herzhafter, fleischiger oder pilzähnlicher Aromen zur Hinzufügung von Tiefe und Komplexität jenseits von süß, sauer, bitter und salzig", nl: "Hartige, vleesachtige of paddenstoel-achtige smaken incorporeren om diepte en complexiteit toe te voegen voorbij zoet, zuur, bitter en zout" },
          { en: "Adding Japanese sake to all cocktails", es: "Añadir sake japonés a todos los cócteles", de: "Japanischen Sake zu allen Cocktails hinzufügen", nl: "Japanse sake toevoegen aan alle cocktails" },
          { en: "Using only Asian ingredients", es: "Usar solo ingredientes asiáticos", de: "Nur asiatische Zutaten verwenden", nl: "Alleen Aziatische ingrediënten gebruiken" },
          { en: "Making cocktails taste like sushi", es: "Hacer que los cócteles sepan a sushi", de: "Cocktails wie Sushi schmecken lassen", nl: "Cocktails laten smaken naar sushi" }
        ],
        correct: 0,
        explanation: {
          en: "Umami integration introduces the fifth taste - savory, meaty, or brothy flavors - into cocktail profiles through ingredients like mushroom-infused spirits, miso, soy sauce, aged cheeses, cured meats, or kombu seaweed. This creates multi-dimensional flavor experiences that go beyond traditional sweet-sour-bitter-salty cocktail profiles. Umami adds depth, complexity, and often a surprising 'completeness' to cocktails. It can be subtle (mushroom-washed whiskey) or pronounced (a Bloody Mary with dashi). This technique requires careful balancing as umami can easily overpower other flavors, but when done correctly, creates memorable and sophisticated drinking experiences.",
          es: "La integración umami introduce el quinto sabor - salado, carnoso o caldoso - en perfiles de cócteles a través de ingredientes como licores infundidos con hongos, miso, salsa de soja, quesos añejos, carnes curadas o alga kombu. Esto crea experiencias de sabor multidimensionales que van más allá de perfiles tradicionales dulce-agrio-amargo-salado de cócteles. Umami añade profundidad, complejidad y a menudo una 'completitud' sorprendente a los cócteles. Puede ser sutil (whiskey lavado con hongos) o pronunciado (un Bloody Mary con dashi). Esta técnica requiere equilibrio cuidadoso ya que umami puede fácilmente sobrepasar otros sabores, pero cuando se hace correctamente, crea experiencias de bebida memorables y sofisticadas.",
          de: "Umami-Integration führt den fünften Geschmack - herzhaft, fleischig oder brühig - in Cocktail-Profile durch Zutaten wie pilzinfundierte Spirituosen, Miso, Sojasauce, gereifte Käse, gepökelte Fleischwaren oder Kombu-Seetang ein. Dies schafft multidimensionale Geschmackserfahrungen, die über traditionelle süß-sauer-bitter-salzig Cocktail-Profile hinausgehen. Umami fügt Tiefe, Komplexität und oft eine überraschende 'Vollständigkeit' zu Cocktails hinzu. Es kann subtil sein (pilzgewaschener Whiskey) oder ausgeprägt (ein Bloody Mary mit Dashi). Diese Technik erfordert sorgfältige Balance, da Umami leicht andere Aromen überwältigen kann, aber richtig gemacht schafft es unvergessliche und raffinierte Trinkerfahrungen.",
          nl: "Umami integratie introduceert de vijfde smaak - hartig, vleesachtig of bouillon-achtig - in cocktail profielen door ingrediënten zoals paddenstoel-geïnfuseerde sterke dranken, miso, sojasaus, gerijpte kazen, gezouten vlees of kombu zeewier. Dit creëert multidimensionale smaakervaringen die verder gaan dan traditionele zoet-zuur-bitter-zout cocktail profielen. Umami voegt diepte, complexiteit en vaak een verrassende 'volledigheid' toe aan cocktails. Het kan subtiel zijn (paddenstoel-gewassen whiskey) of uitgesproken (een Bloody Mary met dashi). Deze techniek vereist zorgvuldige balancering omdat umami gemakkelijk andere smaken kan overheersen, maar wanneer correct gedaan, creëert het memorabele en verfijnde drinkervaringen."
        }
      },
      {
        question: {
          en: "What is 'temperature layering' in cocktail construction and service?",
          es: "¿Qué es la 'estratificación de temperatura' en la construcción y servicio de cócteles?",
          de: "Was ist 'Temperaturschichtung' in Cocktail-Konstruktion und -Service?",
          nl: "Wat is 'temperatuur gelaagdheid' in cocktail constructie en service?"
        },
        options: [
          { en: "Creating different temperature zones within a single cocktail for varying sensory experiences", es: "Crear diferentes zonas de temperatura dentro de un solo cóctel para experiencias sensoriales variadas", de: "Verschiedene Temperaturzonen innerhalb eines einzelnen Cocktails für variierende Sinneserfahrungen schaffen", nl: "Verschillende temperatuurzones binnen een enkele cocktail creëren voor variërende zintuiglijke ervaringen" },
          { en: "Serving cocktails at room temperature only", es: "Servir cócteles solo a temperatura ambiente", de: "Cocktails nur bei Raumtemperatur servieren", nl: "Cocktails alleen op kamertemperatuur serveren" },
          { en: "Using layers of different colored ingredients", es: "Usar capas de ingredientes de diferentes colores", de: "Schichten verschiedenfarbiger Zutaten verwenden", nl: "Lagen van verschillende gekleurde ingrediënten gebruiken" },
          { en: "Stacking ice cubes in order", es: "Apilar cubos de hielo en orden", de: "Eiswürfel in Reihenfolge stapeln", nl: "IJsblokjes op volgorde stapelen" }
        ],
        correct: 0,
        explanation: {
          en: "Temperature layering creates distinct temperature zones within a single cocktail, offering evolving sensory experiences as the drink is consumed. This might involve frozen elements (granitas, ice wines), chilled components (standard cocktail), and warm elements (heated spirits, warm garnishes). Techniques include using different density liquids at varying temperatures, introducing temperature-contrasting garnishes, or serving components that change temperature during consumption. The goal is to create dynamic drinking experiences where temperature differences enhance flavor perception, create textural contrasts, and provide surprising sensory moments throughout the drinking process.",
          es: "La estratificación de temperatura crea zonas de temperatura distintas dentro de un solo cóctel, ofreciendo experiencias sensoriales evolutivas mientras se consume la bebida. Esto podría involucrar elementos congelados (granitas, vinos helados), componentes fríos (cóctel estándar) y elementos calientes (licores calentados, guarniciones calientes). Las técnicas incluyen usar líquidos de diferentes densidades a temperaturas variadas, introducir guarniciones con temperatura contrastante, o servir componentes que cambian de temperatura durante el consumo. El objetivo es crear experiencias de bebida dinámicas donde las diferencias de temperatura mejoran la percepción del sabor, crean contrastes texturales y proporcionan momentos sensoriales sorprendentes durante todo el proceso de bebida.",
          de: "Temperaturschichtung schafft unterschiedliche Temperaturzonen innerhalb eines einzelnen Cocktails und bietet sich entwickelnde Sinneserfahrungen während des Trinkens. Dies könnte gefrorene Elemente (Granitas, Eisweine), gekühlte Komponenten (Standard-Cocktail) und warme Elemente (erhitzte Spirituosen, warme Garnituren) umfassen. Techniken umfassen verschiedene Dichte-Flüssigkeiten bei variierenden Temperaturen, Einführung temperaturkontrastierender Garnituren oder Servieren von Komponenten, die während des Konsums die Temperatur ändern. Das Ziel ist, dynamische Trinkerfahrungen zu schaffen, wo Temperaturunterschiede Geschmackswahrnehmung verbessern, Texturkontraste schaffen und überraschende Sinnesmomente während des gesamten Trinkprozesses bieten.",
          nl: "Temperatuur gelaagdheid creëert verschillende temperatuurzones binnen een enkele cocktail, wat evoluerende zintuiglijke ervaringen biedt terwijl de drank wordt geconsumeerd. Dit kan bevroren elementen omvatten (granita's, ijswijnen), gekoelde componenten (standaard cocktail) en warme elementen (verwarmde sterke dranken, warme garneringen). Technieken omvatten verschillende dichtheid vloeistoffen op variërende temperaturen gebruiken, temperatuur-contrasterende garneringen introduceren, of componenten serveren die van temperatuur veranderen tijdens consumptie. Het doel is dynamische drinkervaringen te creëren waar temperatuurverschillen smaakperceptie verbeteren, textuur contrasten creëren en verrassende zintuiglijke momenten bieden gedurende het hele drinkproces."
        }
      },
      {
        question: {
          en: "What is the 'golden ratio' for classic sour cocktails according to modern mixology standards?",
          es: "¿Cuál es la 'proporción áurea' para cócteles sour clásicos según los estándares modernos de mixología?",
          de: "Was ist das 'goldene Verhältnis' für klassische Sour-Cocktails nach modernen Mixologie-Standards?",
          nl: "Wat is de 'gulden snede' voor klassieke sour cocktails volgens moderne mixologie standaarden?"
        },
        options: [
          { en: "2:1:1 (spirit:citrus:sweetener)", es: "2:1:1 (licor:cítrico:endulzante)", de: "2:1:1 (Spirituose:Zitrus:Süßungsmittel)", nl: "2:1:1 (sterke drank:citrus:zoetstof)" },
          { en: "3:2:1 (spirit:citrus:sweetener)", es: "3:2:1 (licor:cítrico:endulzante)", de: "3:2:1 (Spirituose:Zitrus:Süßungsmittel)", nl: "3:2:1 (sterke drank:citrus:zoetstof)" },
          { en: "1:1:1 (equal parts)", es: "1:1:1 (partes iguales)", de: "1:1:1 (gleiche Teile)", nl: "1:1:1 (gelijke delen)" },
          { en: "4:2:1 (spirit:citrus:sweetener)", es: "4:2:1 (licor:cítrico:endulzante)", de: "4:2:1 (Spirituose:Zitrus:Süßungsmittel)", nl: "4:2:1 (sterke drank:citrus:zoetstof)" }
        ],
        correct: 0,
        explanation: {
          en: "The modern golden ratio for sour cocktails is 2:1:1 (2 parts spirit, 1 part citrus juice, 1 part sweetener). This ratio, often attributed to Sasha Petraske and other contemporary bartenders, creates balanced cocktails where the base spirit remains prominent while achieving proper sweet-tart balance. For example: 2 oz whiskey, 1 oz lemon juice, 1 oz simple syrup. However, this is a starting point—adjustments are needed based on spirit proof, citrus acidity, and sweetener concentration. Higher-proof spirits may use 2:0.75:0.75, while lower-acid citrus might need 2:1.25:0.75.",
          es: "La proporción áurea moderna para cócteles sour es 2:1:1 (2 partes licor, 1 parte jugo cítrico, 1 parte endulzante). Esta proporción, a menudo atribuida a Sasha Petraske y otros bartenders contemporáneos, crea cócteles equilibrados donde el licor base permanece prominente mientras se logra equilibrio dulce-ácido apropiado. Por ejemplo: 2 oz whiskey, 1 oz jugo de limón, 1 oz jarabe simple. Sin embargo, esto es un punto de partida—se necesitan ajustes basados en graduación del licor, acidez cítrica y concentración del endulzante. Licores de mayor graduación pueden usar 2:0.75:0.75, mientras que cítricos de menor acidez pueden necesitar 2:1.25:0.75.",
          de: "Das moderne goldene Verhältnis für Sour-Cocktails ist 2:1:1 (2 Teile Spirituose, 1 Teil Zitrussaft, 1 Teil Süßungsmittel). Dieses Verhältnis, oft Sasha Petraske und anderen zeitgenössischen Bartendern zugeschrieben, schafft ausgewogene Cocktails, wo die Basis-Spirituose prominent bleibt während angemessene süß-herbe Balance erreicht wird. Zum Beispiel: 2 oz Whiskey, 1 oz Zitronensaft, 1 oz einfacher Sirup. Dies ist jedoch ein Ausgangspunkt—Anpassungen sind erforderlich basierend auf Spirituosen-Proof, Zitrussäure und Süßungsmittel-Konzentration. Höher-prozentige Spirituosen können 2:0,75:0,75 verwenden, während niedrig-saure Zitrus 2:1,25:0,75 benötigen könnten.",
          nl: "De moderne gulden snede voor sour cocktails is 2:1:1 (2 delen sterke drank, 1 deel citrussap, 1 deel zoetstof). Deze verhouding, vaak toegeschreven aan Sasha Petraske en andere hedendaagse bartenders, creëert gebalanceerde cocktails waar de basis sterke drank prominent blijft terwijl een juiste zoet-zuur balans wordt bereikt. Bijvoorbeeld: 2 oz whiskey, 1 oz citroensap, 1 oz eenvoudige siroop. Dit is echter een startpunt—aanpassingen zijn nodig gebaseerd op sterke drank proof, citrus zuurgraad en zoetstof concentratie. Hogere-proof sterke dranken kunnen 2:0,75:0,75 gebruiken, terwijl lagere-zuur citrus 2:1,25:0,75 nodig kunnen hebben."
        }
      },
      {
        question: {
          en: "What is a 'Fix' cocktail and how does it differ from a traditional sour?",
          es: "¿Qué es un cóctel 'Fix' y cómo difiere de un sour tradicional?",
          de: "Was ist ein 'Fix'-Cocktail und wie unterscheidet er sich von einem traditionellen Sour?",
          nl: "Wat is een 'Fix' cocktail en hoe verschilt het van een traditionele sour?"
        },
        options: [
          { en: "A sour served over crushed ice with fresh fruit garnish and seasonal ingredients", es: "Un sour servido sobre hielo picado con guarnición de fruta fresca e ingredientes estacionales", de: "Ein Sour serviert über zerstoßenem Eis mit frischer Fruchtgarnitur und saisonalen Zutaten", nl: "Een sour geserveerd op crushed ijs met verse fruit garnering en seizoensgebonden ingrediënten" },
          { en: "A cocktail that fixes hangovers", es: "Un cóctel que cura resacas", de: "Ein Cocktail der Kater heilt", nl: "Een cocktail die katers geneest" },
          { en: "A pre-batched cocktail stored for weeks", es: "Un cóctel pre-loteado almacenado por semanas", de: "Ein vorbatch Cocktail wochenlang gelagert", nl: "Een vooraf batch cocktail weken bewaard" },
          { en: "A cocktail with fixed proportions that never change", es: "Un cóctel con proporciones fijas que nunca cambian", de: "Ein Cocktail mit festen Proportionen die nie ändern", nl: "Een cocktail met vaste verhoudingen die nooit veranderen" }
        ],
        correct: 0,
        explanation: {
          en: "A Fix is a classic cocktail category from the 1800s, essentially a sour cocktail served over crushed or pebble ice with abundant fresh fruit garnish and often seasonal ingredients. The typical structure is spirit, citrus juice, sweetener (often pineapple syrup or fruit-based sweeteners), served in a rocks glass over crushed ice with fresh berries, citrus wedges, or seasonal fruit. Famous examples include the Gin Fix and Brandy Fix. The crushed ice creates rapid dilution and a refreshing, slushy texture, while the fruit adds aromatics and visual appeal. It's considered a predecessor to the modern julep and cobbler categories.",
          es: "Un Fix es una categoría clásica de cóctel de los 1800s, esencialmente un cóctel sour servido sobre hielo picado o de guijarros con abundante guarnición de fruta fresca y a menudo ingredientes estacionales. La estructura típica es licor, jugo cítrico, endulzante (a menudo jarabe de piña o endulzantes basados en fruta), servido en un vaso rocks sobre hielo picado con bayas frescas, gajos de cítricos o fruta estacional. Ejemplos famosos incluyen el Gin Fix y Brandy Fix. El hielo picado crea dilución rápida y una textura refrescante y aguanieve, mientras que la fruta añade aromáticos y atractivo visual. Se considera un predecesor de las categorías modernas julep y cobbler.",
          de: "Ein Fix ist eine klassische Cocktail-Kategorie aus den 1800ern, im Wesentlichen ein Sour-Cocktail serviert über zerstoßenem oder Kieseleis mit reichlicher frischer Fruchtgarnitur und oft saisonalen Zutaten. Die typische Struktur ist Spirituose, Zitrussaft, Süßungsmittel (oft Ananassirup oder fruchtbasierte Süßungsmittel), serviert in einem Rocks-Glas über zerstoßenem Eis mit frischen Beeren, Zitrusspalten oder saisonaler Frucht. Berühmte Beispiele sind Gin Fix und Brandy Fix. Das zerstoßene Eis schafft schnelle Verdünnung und eine erfrischende, matschige Textur, während die Frucht Aromen und visuelle Anziehung hinzufügt. Es gilt als Vorläufer der modernen Julep- und Cobbler-Kategorien.",
          nl: "Een Fix is een klassieke cocktail categorie uit de jaren 1800, in wezen een sour cocktail geserveerd op crushed of grind ijs met overvloedige verse fruit garnering en vaak seizoensgebonden ingrediënten. De typische structuur is sterke drank, citrussap, zoetstof (vaak ananas siroop of fruit-gebaseerde zoetstoffen), geserveerd in een rocks glas op crushed ijs met verse bessen, citrus partjes of seizoensfruit. Beroemde voorbeelden zijn de Gin Fix en Brandy Fix. Het crushed ijs creëert snelle verdunning en een verfrissende, slushy textuur, terwijl het fruit aromaten en visuele aantrekkingskracht toevoegt. Het wordt beschouwd als een voorloper van de moderne julep en cobbler categorieën."
        }
      },
      {
        question: {
          en: "What is 'Ti' Punch' and what makes it different from a standard rum cocktail?",
          es: "¿Qué es el 'Ti' Punch' y qué lo hace diferente de un cóctel de ron estándar?",
          de: "Was ist 'Ti' Punch' und was macht ihn anders als einen Standard-Rum-Cocktail?",
          nl: "Wat is 'Ti' Punch' en wat maakt het anders dan een standaard rum cocktail?"
        },
        options: [
          { en: "Martinique rhum agricole, lime disc, cane syrup, self-mixed at the table by the drinker", es: "Rhum agricole de Martinica, disco de lima, jarabe de caña, auto-mezclado en la mesa por el bebedor", de: "Martinique Rhum Agricole, Limettenscheibe, Rohrzuckersirup, vom Trinker am Tisch selbst gemischt", nl: "Martinique rhum agricole, limoen schijf, rietsuikersiroop, zelf gemixt aan tafel door de drinker" },
          { en: "A tiny punch served in shot glasses", es: "Un ponche pequeño servido en vasos de chupito", de: "Ein winziger Punsch in Schnapsgläsern serviert", nl: "Een kleine punch geserveerd in shotglazen" },
          { en: "A Hawaiian punch with tiki garnishes", es: "Un ponche hawaiano con guarniciones tiki", de: "Ein hawaiianischer Punsch mit Tiki-Garnituren", nl: "Een Hawaïaanse punch met tiki garneringen" },
          { en: "A punch made with Thai ingredients", es: "Un ponche hecho con ingredientes tailandeses", de: "Ein Punsch mit thailändischen Zutaten gemacht", nl: "Een punch gemaakt met Thaise ingrediënten" }
        ],
        correct: 0,
        explanation: {
          en: "'Ti' Punch (short for 'Petit Punch') is the national drink of Martinique and French Caribbean islands. It consists of rhum agricole (cane juice rum), a lime disc (not juice), and cane syrup (sirop de canne). What makes it unique is the preparation ritual: ingredients are presented separately and the drinker mixes their own drink at the table using a swizzle stick (bois lélé), pressing the lime disc to release oils and adjusting sweetness to taste. The lime disc (not squeezed juice) provides aromatic oils and subtle acidity. It's typically served at room temperature to preserve the rhum's grassy, vegetal character.",
          es: "El 'Ti' Punch (abreviatura de 'Petit Punch') es la bebida nacional de Martinica y las islas del Caribe francés. Consiste en rhum agricole (ron de jugo de caña), un disco de lima (no jugo) y jarabe de caña (sirop de canne). Lo que lo hace único es el ritual de preparación: los ingredientes se presentan por separado y el bebedor mezcla su propia bebida en la mesa usando un palillo mezclador (bois lélé), presionando el disco de lima para liberar aceites y ajustando el dulzor al gusto. El disco de lima (no jugo exprimido) proporciona aceites aromáticos y acidez sutil. Típicamente se sirve a temperatura ambiente para preservar el carácter herbáceo y vegetal del rhum.",
          de: "'Ti' Punch (kurz für 'Petit Punch') ist das Nationalgetränk von Martinique und französischen Karibikinseln. Es besteht aus Rhum Agricole (Zuckerrohrsaft-Rum), einer Limettenscheibe (kein Saft) und Rohrzuckersirup (Sirop de Canne). Was ihn einzigartig macht, ist das Zubereitungsritual: Zutaten werden separat präsentiert und der Trinker mischt sein eigenes Getränk am Tisch mit einem Swizzle-Stick (Bois Lélé), drückt die Limettenscheibe um Öle freizusetzen und passt Süße nach Geschmack an. Die Limettenscheibe (nicht ausgepresster Saft) liefert aromatische Öle und subtile Säure. Es wird typisch bei Raumtemperatur serviert um den grasigen, pflanzlichen Charakter des Rhums zu bewahren.",
          nl: "'Ti' Punch (kort voor 'Petit Punch') is de nationale drank van Martinique en Franse Caribische eilanden. Het bestaat uit rhum agricole (rietsuikersap rum), een limoen schijf (niet sap) en rietsuikersiroop (sirop de canne). Wat het uniek maakt is het bereidingsritueel: ingrediënten worden apart gepresenteerd en de drinker mixt hun eigen drank aan tafel met een swizzle stick (bois lélé), de limoen schijf indrukkend om oliën vrij te maken en zoetheid naar smaak aan te passen. De limoen schijf (niet uitgeperst sap) levert aromatische oliën en subtiele zuurgraad. Het wordt typisch op kamertemperatuur geserveerd om het grasachtige, plantaardige karakter van de rhum te bewaren."
        }
      },
      {
        question: {
          en: "What is 'mise en place' in cocktail bar operations and why is it crucial?",
          es: "¿Qué es el 'mise en place' en las operaciones de bares de cócteles y por qué es crucial?",
          de: "Was ist 'Mise en Place' in Cocktail-Bar-Operationen und warum ist es entscheidend?",
          nl: "Wat is 'mise en place' in cocktail bar operaties en waarom is het cruciaal?"
        },
        options: [
          { en: "Complete preparation and organization of all ingredients, tools, and garnishes before service begins", es: "Preparación y organización completa de todos los ingredientes, herramientas y guarniciones antes de que comience el servicio", de: "Vollständige Vorbereitung und Organisation aller Zutaten, Werkzeuge und Garnituren vor Dienstbeginn", nl: "Complete voorbereiding en organisatie van alle ingrediënten, gereedschappen en garneringen voordat de dienst begint" },
          { en: "The location where cocktails are placed after making", es: "La ubicación donde se colocan los cócteles después de hacerlos", de: "Der Ort wo Cocktails nach dem Machen platziert werden", nl: "De locatie waar cocktails worden geplaatst na het maken" },
          { en: "A French cocktail with special ingredients", es: "Un cóctel francés con ingredientes especiales", de: "Ein französischer Cocktail mit speziellen Zutaten", nl: "Een Franse cocktail met speciale ingrediënten" },
          { en: "The bar's seating arrangement", es: "La disposición de asientos del bar", de: "Die Sitzordnung der Bar", nl: "De zitplaatsen regeling van de bar" }
        ],
        correct: 0,
        explanation: {
          en: "Mise en place (French for 'everything in its place') is the foundational practice of preparing and organizing all ingredients, tools, and garnishes before service. This includes: fresh juices squeezed, syrups prepared, fruits cut, herbs picked and organized, ice bins filled, glassware polished and chilled, bar tools positioned, and backup ingredients stocked. Proper mise en place is crucial because it enables fast, consistent cocktail production during busy service, reduces errors, minimizes waste, ensures quality control, and allows bartenders to focus on technique and customer interaction rather than searching for ingredients. Professional bars may spend 2-4 hours on mise en place before opening.",
          es: "Mise en place (francés para 'todo en su lugar') es la práctica fundamental de preparar y organizar todos los ingredientes, herramientas y guarniciones antes del servicio. Esto incluye: jugos frescos exprimidos, jarabes preparados, frutas cortadas, hierbas recogidas y organizadas, depósitos de hielo llenos, cristalería pulida y enfriada, herramientas de bar posicionadas e ingredientes de respaldo almacenados. El mise en place apropiado es crucial porque permite producción rápida y consistente de cócteles durante el servicio ocupado, reduce errores, minimiza desperdicios, asegura control de calidad y permite a los bartenders enfocarse en técnica e interacción con clientes en lugar de buscar ingredientes. Los bares profesionales pueden pasar 2-4 horas en mise en place antes de abrir.",
          de: "Mise en Place (französisch für 'alles an seinem Platz') ist die grundlegende Praxis der Vorbereitung und Organisation aller Zutaten, Werkzeuge und Garnituren vor dem Service. Dies umfasst: frische Säfte gepresst, Sirupe vorbereitet, Früchte geschnitten, Kräuter gepflückt und organisiert, Eisbehälter gefüllt, Glaswaren poliert und gekühlt, Bar-Werkzeuge positioniert und Ersatzzutaten gelagert. Ordnungsgemäße Mise en Place ist entscheidend, weil sie schnelle, konsistente Cocktail-Produktion während geschäftigem Service ermöglicht, Fehler reduziert, Verschwendung minimiert, Qualitätskontrolle sicherstellt und Bartendern erlaubt, sich auf Technik und Kundeninteraktion zu konzentrieren statt nach Zutaten zu suchen. Professionelle Bars können 2-4 Stunden Mise en Place vor Öffnung verbringen.",
          nl: "Mise en place (Frans voor 'alles op zijn plaats') is de fundamentele praktijk van het voorbereiden en organiseren van alle ingrediënten, gereedschappen en garneringen voor de dienst. Dit omvat: verse sappen geperst, siropen bereid, fruit gesneden, kruiden geplukt en georganiseerd, ijsbakken gevuld, glaswerk gepolijst en gekoeld, bar gereedschappen gepositioneerd en backup ingrediënten opgeslagen. Juiste mise en place is cruciaal omdat het snelle, consistente cocktail productie mogelijk maakt tijdens drukke dienst, fouten vermindert, verspilling minimaliseert, kwaliteitscontrole verzekert en bartenders in staat stelt zich te concentreren op techniek en klant interactie in plaats van zoeken naar ingrediënten. Professionele bars kunnen 2-4 uur besteden aan mise en place voor opening."
        }
      },
      {
        question: {
          en: "What is the 'Bartender's Handshake' and what does it represent in cocktail culture?",
          es: "¿Qué es el 'Apretón de Manos del Bartender' y qué representa en la cultura de cócteles?",
          de: "Was ist der 'Bartender's Handshake' und was repräsentiert er in der Cocktail-Kultur?",
          nl: "Wat is de 'Bartender's Handshake' en wat vertegenwoordigt het in cocktail cultuur?"
        },
        options: [
          { en: "A shot of Fernet-Branca offered between bartenders as a sign of hospitality and professional respect", es: "Un trago de Fernet-Branca ofrecido entre bartenders como signo de hospitalidad y respeto profesional", de: "Ein Shot Fernet-Branca zwischen Bartendern als Zeichen von Gastfreundschaft und professionellem Respekt angeboten", nl: "Een shot Fernet-Branca aangeboden tussen bartenders als teken van gastvrijheid en professioneel respect" },
          { en: "A special way bartenders shake cocktails", es: "Una forma especial en que los bartenders agitan cócteles", de: "Eine spezielle Art wie Bartender Cocktails schütteln", nl: "Een speciale manier waarop bartenders cocktails schudden" },
          { en: "The first cocktail served to a new customer", es: "El primer cóctel servido a un nuevo cliente", de: "Der erste Cocktail der einem neuen Kunden serviert wird", nl: "De eerste cocktail geserveerd aan een nieuwe klant" },
          { en: "A handshake technique for greeting customers", es: "Una técnica de apretón de manos para saludar clientes", de: "Eine Handschlag-Technik zur Begrüßung von Kunden", nl: "Een handdruk techniek voor het begroeten van klanten" }
        ],
        correct: 0,
        explanation: {
          en: "The 'Bartender's Handshake' is an industry tradition where bartenders offer each other a shot of Fernet-Branca, an intensely bitter Italian amaro. This ritual represents professional camaraderie, mutual respect, and hospitality within the bartending community. The tradition likely started in San Francisco in the early 2000s and spread worldwide. Fernet-Branca was chosen for its acquired taste—bitter, mentholated, and complex—which separates industry professionals from casual drinkers. Accepting and drinking the shot signals you're part of the bartending fraternity. The practice has extended to other spirituous offerings but Fernet-Branca remains the iconic choice.",
          es: "El 'Apretón de Manos del Bartender' es una tradición de la industria donde los bartenders se ofrecen mutuamente un trago de Fernet-Branca, un amaro italiano intensamente amargo. Este ritual representa camaradería profesional, respeto mutuo y hospitalidad dentro de la comunidad de bartenders. La tradición probablemente comenzó en San Francisco a principios de los 2000s y se extendió mundialmente. Fernet-Branca fue elegido por su sabor adquirido—amargo, mentolado y complejo—que separa profesionales de la industria de bebedores casuales. Aceptar y beber el trago señala que eres parte de la fraternidad de bartenders. La práctica se ha extendido a otras ofertas espirituosas pero Fernet-Branca permanece como la elección icónica.",
          de: "Der 'Bartender's Handshake' ist eine Branchentradition, wo Bartender einander einen Shot Fernet-Branca anbieten, einen intensiv bitteren italienischen Amaro. Dieses Ritual repräsentiert professionelle Kameradschaft, gegenseitigen Respekt und Gastfreundschaft innerhalb der Bartender-Gemeinschaft. Die Tradition begann wahrscheinlich in San Francisco Anfang der 2000er und verbreitete sich weltweit. Fernet-Branca wurde wegen seines erworbenen Geschmacks gewählt—bitter, mentholiert und komplex—der Branchenprofis von Gelegenheitstrinkern trennt. Das Akzeptieren und Trinken des Shots signalisiert, dass man Teil der Bartender-Bruderschaft ist. Die Praxis hat sich auf andere spirituose Angebote ausgedehnt, aber Fernet-Branca bleibt die ikonische Wahl.",
          nl: "De 'Bartender's Handshake' is een industrie traditie waar bartenders elkaar een shot Fernet-Branca aanbieden, een intens bittere Italiaanse amaro. Dit ritueel vertegenwoordigt professionele kameraadschap, wederzijds respect en gastvrijheid binnen de bartender gemeenschap. De traditie begon waarschijnlijk in San Francisco begin jaren 2000 en verspreidde zich wereldwijd. Fernet-Branca werd gekozen voor zijn verworven smaak—bitter, gementholeerd en complex—wat industrie professionals scheidt van casual drinkers. Het accepteren en drinken van de shot geeft aan dat je deel uitmaakt van de bartender broederschap. De praktijk is uitgebreid naar andere spiritueuze aanbiedingen maar Fernet-Branca blijft de iconische keuze."
        }
      },
      {
        question: {
          en: "What is the 'Brown Derby' cocktail and what's unique about its creation story?",
          es: "¿Qué es el cóctel 'Brown Derby' y qué es único sobre su historia de creación?",
          de: "Was ist der 'Brown Derby'-Cocktail und was ist einzigartig an seiner Entstehungsgeschichte?",
          nl: "Wat is de 'Brown Derby' cocktail en wat is uniek aan het creatie verhaal?"
        },
        options: [
          { en: "Bourbon, grapefruit juice, honey syrup; created at the Vendôme Club but named after the famous hat-shaped restaurant", es: "Bourbon, jugo de toronja, jarabe de miel; creado en el Vendôme Club pero nombrado por el famoso restaurante en forma de sombrero", de: "Bourbon, Grapefruitsaft, Honigsirup; im Vendôme Club kreiert aber nach dem berühmten hutförmigen Restaurant benannt", nl: "Bourbon, grapefruitsap, honing siroop; gecreëerd in de Vendôme Club maar genoemd naar het beroemde hoed-vormige restaurant" },
          { en: "Made with brown rum only", es: "Hecho solo con ron marrón", de: "Nur mit braunem Rum gemacht", nl: "Gemaakt met alleen bruine rum" },
          { en: "Served in a derby hat glass", es: "Servido en un vaso de sombrero derby", de: "In einem Derby-Hut-Glas serviert", nl: "Geserveerd in een derby hoed glas" },
          { en: "Created for horse racing events", es: "Creado para eventos de carreras de caballos", de: "Für Pferderennen kreiert", nl: "Gecreëerd voor paardenraces" }
        ],
        correct: 0,
        explanation: {
          en: "The Brown Derby is a Prohibition-era cocktail made with bourbon, fresh grapefruit juice, and honey syrup. Despite being famously associated with the Brown Derby restaurant (the iconic hat-shaped Los Angeles restaurant), it was actually created at the nearby Vendôme Club in the 1930s. The cocktail showcases the classic American combination of whiskey with citrus, enhanced by honey's floral complexity. The grapefruit provides bitter-sweet balance that complements bourbon's caramel notes. It's considered a predecessor to modern craft cocktail movements that emphasize fresh citrus and natural sweeteners.",
          es: "El Brown Derby es un cóctel de la era de la Prohibición hecho con bourbon, jugo fresco de toronja y jarabe de miel. A pesar de estar famosamente asociado con el restaurante Brown Derby (el icónico restaurante de Los Ángeles en forma de sombrero), fue realmente creado en el cercano Vendôme Club en los 1930s. El cóctel muestra la combinación americana clásica de whiskey con cítricos, realzada por la complejidad floral de la miel. La toronja proporciona equilibrio amargo-dulce que complementa las notas de caramelo del bourbon. Se considera un predecesor de los movimientos modernos de cócteles artesanales que enfatizan cítricos frescos y endulzantes naturales.",
          de: "Der Brown Derby ist ein Cocktail aus der Prohibitionszeit aus Bourbon, frischem Grapefruitsaft und Honigsirup. Trotz berühmter Assoziation mit dem Brown Derby Restaurant (das ikonische hutförmige Los Angeles Restaurant) wurde er tatsächlich im nahegelegenen Vendôme Club in den 1930ern kreiert. Der Cocktail zeigt die klassische amerikanische Kombination von Whiskey mit Zitrus, verstärkt durch Honigs florale Komplexität. Die Grapefruit bietet bitter-süße Balance, die Bourbons Karamellnoten ergänzt. Er gilt als Vorläufer moderner Craft-Cocktail-Bewegungen, die frische Zitrus und natürliche Süßungsmittel betonen.",
          nl: "De Brown Derby is een Prohibition-tijdperk cocktail gemaakt met bourbon, vers grapefruitsap en honing siroop. Ondanks dat het beroemd wordt geassocieerd met het Brown Derby restaurant (het iconische hoed-vormige Los Angeles restaurant), werd het eigenlijk gecreëerd in de nabijgelegen Vendôme Club in de jaren 1930. De cocktail toont de klassieke Amerikaanse combinatie van whiskey met citrus, versterkt door honing's bloemen complexiteit. De grapefruit biedt bitter-zoete balans die bourbon's karamel noten complementeert. Het wordt beschouwd als een voorloper van moderne craft cocktail bewegingen die verse citrus en natuurlijke zoetstoffen benadrukken."
        }
      },
      {
        question: {
          en: "What is the 'Aviation' cocktail controversy regarding crème de violette?",
          es: "¿Cuál es la controversia del cóctel 'Aviation' respecto al crème de violette?",
          de: "Was ist die 'Aviation'-Cocktail-Kontroverse bezüglich Crème de Violette?",
          nl: "Wat is de 'Aviation' cocktail controverse over crème de violette?"
        },
        options: [
          { en: "Original 1916 recipe included crème de violette, but it was omitted from 1930s-2000s recipes due to unavailability, changing the cocktail's character and color", es: "La receta original de 1916 incluía crème de violette, pero fue omitido de recetas de 1930s-2000s debido a indisponibilidad, cambiando el carácter y color del cóctel", de: "Original 1916 Rezept enthielt Crème de Violette, wurde aber von 1930er-2000er Rezepten weggelassen wegen Nichtverfügbarkeit, änderte Charakter und Farbe des Cocktails", nl: "Origineel 1916 recept bevatte crème de violette, maar het werd weggelaten uit 1930s-2000s recepten door onbeschikbaarheid, wat het karakter en kleur van de cocktail veranderde" },
          { en: "Violet liqueur is illegal in some countries", es: "El licor de violeta es ilegal en algunos países", de: "Veilchenlikör ist in einigen Ländern illegal", nl: "Violet likeur is illegaal in sommige landen" },
          { en: "The cocktail was never meant to have violets", es: "El cóctel nunca debía tener violetas", de: "Der Cocktail sollte nie Veilchen haben", nl: "De cocktail was nooit bedoeld om viooltjes te hebben" },
          { en: "Airlines complained about the name", es: "Las aerolíneas se quejaron del nombre", de: "Fluggesellschaften beschwerten sich über den Namen", nl: "Luchtvaartmaatschappijen klaagden over de naam" }
        ],
        correct: 0,
        explanation: {
          en: "The Aviation controversy centers on crème de violette. Hugo Ensslin's original 1916 recipe included gin, lemon juice, maraschino liqueur, and crème de violette (giving it a distinctive pale purple hue). However, when crème de violette became unavailable in the mid-20th century, recipes omitted it—most famously in 'The Savoy Cocktail Book' (1930). This created two distinct drinks: the pale Aviation without violette, and the original purple-hued version. When Rothman & Winter reintroduced crème de violette in 2007, bartenders rediscovered the original recipe. The debate continues: is the 'true' Aviation with or without violette?",
          es: "La controversia del Aviation se centra en el crème de violette. La receta original de Hugo Ensslin de 1916 incluía gin, jugo de limón, licor maraschino y crème de violette (dándole un distintivo tono púrpura pálido). Sin embargo, cuando el crème de violette se volvió indisponible a mediados del siglo XX, las recetas lo omitieron—más famosamente en 'The Savoy Cocktail Book' (1930). Esto creó dos bebidas distintas: el Aviation pálido sin violette y la versión original con tono púrpura. Cuando Rothman & Winter reintrodujo el crème de violette en 2007, los bartenders redescubrieron la receta original. El debate continúa: ¿es el 'verdadero' Aviation con o sin violette?",
          de: "Die Aviation-Kontroverse dreht sich um Crème de Violette. Hugo Ensslins Original-1916-Rezept enthielt Gin, Zitronensaft, Maraschino-Likör und Crème de Violette (gab ihm einen charakteristischen blassvioletten Farbton). Als Crème de Violette Mitte des 20. Jahrhunderts nicht verfügbar wurde, ließen Rezepte es weg—am berühmtesten in 'The Savoy Cocktail Book' (1930). Dies schuf zwei unterschiedliche Drinks: den blassen Aviation ohne Violette und die ursprüngliche lila-getönte Version. Als Rothman & Winter Crème de Violette 2007 wieder einführte, entdeckten Bartender das Originalrezept wieder. Die Debatte geht weiter: Ist der 'echte' Aviation mit oder ohne Violette?",
          nl: "De Aviation controverse draait om crème de violette. Hugo Ensslin's originele 1916 recept bevatte gin, citroensap, maraschino likeur en crème de violette (wat het een onderscheidende bleek paarse tint gaf). Echter, toen crème de violette onbeschikbaar werd in het midden van de 20e eeuw, lieten recepten het weg—meest beroemd in 'The Savoy Cocktail Book' (1930). Dit creëerde twee verschillende drankjes: de bleke Aviation zonder violette, en de originele paars-getinte versie. Toen Rothman & Winter crème de violette opnieuw introduceerde in 2007, herontdekten bartenders het originele recept. Het debat gaat door: is de 'echte' Aviation met of zonder violette?"
        }
      },
      {
        question: {
          en: "What is 'perlage' and why is it important in Champagne cocktails?",
          es: "¿Qué es el 'perlage' y por qué es importante en cócteles de Champagne?",
          de: "Was ist 'Perlage' und warum ist es wichtig in Champagner-Cocktails?",
          nl: "Wat is 'perlage' en waarom is het belangrijk in Champagne cocktails?"
        },
        options: [
          { en: "The quality, size, and persistence of bubbles; important for texture, aroma delivery, and visual appeal in sparkling wine cocktails", es: "La calidad, tamaño y persistencia de las burbujas; importante para textura, entrega de aroma y atractivo visual en cócteles de vino espumoso", de: "Die Qualität, Größe und Persistenz der Blasen; wichtig für Textur, Aromaabgabe und visuelle Anziehung in Schaumwein-Cocktails", nl: "De kwaliteit, grootte en persistentie van bubbels; belangrijk voor textuur, aroma afgifte en visuele aantrekkingskracht in mousserende wijn cocktails" },
          { en: "A type of pearl garnish for fancy cocktails", es: "Un tipo de guarnición de perlas para cócteles elegantes", de: "Eine Art Perlengarnitur für schicke Cocktails", nl: "Een type parel garnering voor chique cocktails" },
          { en: "The French method of pouring Champagne", es: "El método francés de servir Champagne", de: "Die französische Methode Champagner einzuschenken", nl: "De Franse methode van Champagne inschenken" },
          { en: "A Champagne cocktail invented in Paris", es: "Un cóctel de Champagne inventado en París", de: "Ein in Paris erfundener Champagner-Cocktail", nl: "Een Champagne cocktail uitgevonden in Parijs" }
        ],
        correct: 0,
        explanation: {
          en: "Perlage refers to the bubbles in sparkling wine—their size, quantity, persistence, and how they rise (train of bubbles). Fine perlage has small, persistent bubbles that create creamy mousse, deliver aromatics to the nose, and provide pleasant texture. In Champagne cocktails, preserving perlage is crucial: gentle stirring (never shaking), adding Champagne last, using chilled ingredients, and proper glassware all help maintain bubble structure. Poor technique destroys perlage, making cocktails flat and less aromatic. High-quality Champagne's persistent perlage ensures cocktails remain effervescent throughout drinking.",
          es: "Perlage se refiere a las burbujas en vino espumoso—su tamaño, cantidad, persistencia y cómo suben (tren de burbujas). Perlage fino tiene burbujas pequeñas y persistentes que crean mousse cremosa, entregan aromáticos a la nariz y proporcionan textura agradable. En cócteles de Champagne, preservar el perlage es crucial: revolver suavemente (nunca agitar), añadir Champagne al final, usar ingredientes fríos y cristalería apropiada ayudan a mantener la estructura de burbujas. Técnica pobre destruye el perlage, haciendo cócteles planos y menos aromáticos. El perlage persistente de Champagne de alta calidad asegura que los cócteles permanezcan efervescentes durante toda la bebida.",
          de: "Perlage bezieht sich auf die Blasen in Schaumwein—ihre Größe, Menge, Persistenz und wie sie aufsteigen (Blasenzug). Feine Perlage hat kleine, persistente Blasen, die cremige Mousse schaffen, Aromen zur Nase liefern und angenehme Textur bieten. In Champagner-Cocktails ist Perlage-Erhaltung entscheidend: sanftes Rühren (nie schütteln), Champagner zuletzt hinzufügen, gekühlte Zutaten verwenden und ordnungsgemäße Glaswaren helfen, Blasenstruktur zu erhalten. Schlechte Technik zerstört Perlage, macht Cocktails flach und weniger aromatisch. Hochwertige Champagners persistente Perlage gewährleistet, dass Cocktails während des Trinkens sprudelnd bleiben.",
          nl: "Perlage verwijst naar de bubbels in mousserende wijn—hun grootte, hoeveelheid, persistentie en hoe ze opstijgen (trein van bubbels). Fijne perlage heeft kleine, persistente bubbels die romige mousse creëren, aromaten leveren aan de neus en aangename textuur bieden. In Champagne cocktails is het behouden van perlage cruciaal: zacht roeren (nooit schudden), Champagne als laatste toevoegen, gekoelde ingrediënten gebruiken en juist glaswerk helpen allemaal bubbel structuur te behouden. Slechte techniek vernietigt perlage, wat cocktails plat en minder aromatisch maakt. Hoge-kwaliteit Champagne's persistente perlage verzekert dat cocktails bruisend blijven tijdens het drinken."
        }
      },
      {
        question: {
          en: "What is 'The Navy Grog' and why is it considered a 'holy grail' of tiki cocktails?",
          es: "¿Qué es 'The Navy Grog' y por qué se considera un 'santo grial' de cócteles tiki?",
          de: "Was ist 'The Navy Grog' und warum wird er als 'Heiliger Gral' der Tiki-Cocktails betrachtet?",
          nl: "Wat is 'The Navy Grog' en waarom wordt het beschouwd als een 'heilige graal' van tiki cocktails?"
        },
        options: [
          { en: "Don the Beachcomber's complex three-rum blend with citrus, honey, and soda; famous for balanced complexity and the original 'grog' served with crushed ice cone", es: "Mezcla compleja de tres rones de Don the Beachcomber con cítricos, miel y soda; famoso por complejidad equilibrada y el 'grog' original servido con cono de hielo picado", de: "Don the Beachcombers komplexe Drei-Rum-Mischung mit Zitrus, Honig und Soda; berühmt für ausgewogene Komplexität und das original 'Grog' serviert mit zerstoßenem Eiskegel", nl: "Don the Beachcomber's complexe drie-rum blend met citrus, honing en soda; beroemd voor gebalanceerde complexiteit en de originele 'grog' geserveerd met crushed ijs kegel" },
          { en: "A cocktail served only to navy officers", es: "Un cóctel servido solo a oficiales de la marina", de: "Ein nur für Marineoffiziere servierter Cocktail", nl: "Een cocktail alleen geserveerd aan marine officieren" },
          { en: "Made with seawater and naval rum", es: "Hecho con agua de mar y ron naval", de: "Mit Meerwasser und Marine-Rum gemacht", nl: "Gemaakt met zeewater en marine rum" },
          { en: "A simple rum and cola variation", es: "Una simple variación de ron y cola", de: "Eine einfache Rum-Cola-Variation", nl: "Een eenvoudige rum en cola variatie" }
        ],
        correct: 0,
        explanation: {
          en: "The Navy Grog, created by Don the Beachcomber (Donn Beach) in the 1940s, is considered tiki royalty for its sophisticated balance. It uses three rums (typically light Puerto Rican, dark Jamaican, and Demerara), fresh lime and grapefruit juice, honey syrup, and soda water. The complexity comes from layering different rum profiles while maintaining refreshing citrus balance. Traditionally served with a crushed ice cone rising from the drink. The recipe was closely guarded—Don used numbered bottles and prepared secret mixes to prevent staff from replicating it. It represents tiki's evolution from simple tropical drinks to complex, balanced cocktails requiring genuine bartending skill.",
          es: "El Navy Grog, creado por Don the Beachcomber (Donn Beach) en los 1940s, se considera realeza tiki por su sofisticado equilibrio. Usa tres rones (típicamente puertorriqueño ligero, jamaicano oscuro y Demerara), jugo fresco de lima y toronja, jarabe de miel y agua con gas. La complejidad viene de capas de diferentes perfiles de ron mientras se mantiene equilibrio cítrico refrescante. Tradicionalmente servido con un cono de hielo picado elevándose de la bebida. La receta fue celosamente guardada—Don usó botellas numeradas y mezclas secretas preparadas para prevenir que el personal la replicara. Representa la evolución del tiki de bebidas tropicales simples a cócteles complejos y equilibrados que requieren genuina habilidad de bartender.",
          de: "Der Navy Grog, von Don the Beachcomber (Donn Beach) in den 1940ern kreiert, gilt als Tiki-Königtum für seine raffinierte Balance. Er verwendet drei Rums (typisch heller Puerto Rican, dunkler Jamaican und Demerara), frischen Limetten- und Grapefruitsaft, Honigsirup und Sodawasser. Die Komplexität kommt vom Schichten verschiedener Rum-Profile während erfrischende Zitrus-Balance erhalten wird. Traditionell mit einem zerstoßenen Eiskegel serviert, der aus dem Drink ragt. Das Rezept wurde streng gehütet—Don benutzte nummerierte Flaschen und vorbereitete geheime Mischungen, um Personal von Replikation abzuhalten. Es repräsentiert Tikis Evolution von einfachen tropischen Drinks zu komplexen, ausgewogenen Cocktails, die echtes Bartender-Können erfordern.",
          nl: "De Navy Grog, gecreëerd door Don the Beachcomber (Donn Beach) in de jaren 1940, wordt beschouwd als tiki royalty voor zijn verfijnde balans. Het gebruikt drie rums (typisch lichte Puerto Ricaanse, donkere Jamaicaanse en Demerara), vers limoen en grapefruitsap, honing siroop en sodawater. De complexiteit komt van het lagen van verschillende rum profielen terwijl verfrissende citrus balans wordt behouden. Traditioneel geserveerd met een crushed ijs kegel opstijgend uit de drank. Het recept werd nauwgezet bewaakt—Don gebruikte genummerde flessen en bereide geheime mixen om personeel van replicatie te weerhouden. Het vertegenwoordigt tiki's evolutie van eenvoudige tropische drankjes naar complexe, gebalanceerde cocktails die echte bartender vaardigheid vereisen."
        }
      },
      {
        question: {
          en: "What is 'batching' cocktails and what adjustments must be made for proper execution?",
          es: "¿Qué es el 'loteado' de cócteles y qué ajustes deben hacerse para ejecución apropiada?",
          de: "Was ist 'Batching' von Cocktails und welche Anpassungen müssen für ordnungsgemäße Ausführung gemacht werden?",
          nl: "Wat is 'batching' cocktails en welke aanpassingen moeten worden gemaakt voor juiste uitvoering?"
        },
        options: [
          { en: "Pre-mixing cocktail ingredients in large quantities; requires adding calculated dilution (20-25% water) to replicate shaking/stirring and adjusting for ingredient integration over time", es: "Pre-mezclar ingredientes de cócteles en grandes cantidades; requiere añadir dilución calculada (20-25% agua) para replicar agitado/revolver y ajustar por integración de ingredientes con el tiempo", de: "Vorab-Mischen von Cocktail-Zutaten in großen Mengen; erfordert Hinzufügung berechneter Verdünnung (20-25% Wasser) zur Replikation von Schütteln/Rühren und Anpassung für Zutatenintegration über Zeit", nl: "Vooraf mengen van cocktail ingrediënten in grote hoeveelheden; vereist toevoegen van berekende verdunning (20-25% water) om schudden/roeren te repliceren en aanpassen voor ingrediënt integratie over tijd" },
          { en: "Making one cocktail at a time very slowly", es: "Hacer un cóctel a la vez muy lentamente", de: "Einen Cocktail zur Zeit sehr langsam machen", nl: "Een cocktail tegelijk zeer langzaam maken" },
          { en: "Serving cocktails in large bowls only", es: "Servir cócteles solo en tazones grandes", de: "Cocktails nur in großen Schalen servieren", nl: "Cocktails alleen in grote kom men serveren" },
          { en: "Using batch production equipment like blenders", es: "Usar equipo de producción por lotes como licuadoras", de: "Batch-Produktionsausrüstung wie Mixer verwenden", nl: "Batch productie apparatuur zoals blenders gebruiken" }
        ],
        correct: 0,
        explanation: {
          en: "Batching involves pre-mixing cocktail ingredients in large quantities for efficient service. Critical adjustments include: (1) Adding calculated dilution—typically 20-25% water by volume—to replicate the water added through shaking or stirring with ice. (2) Allowing ingredients to integrate—citrus acids, sugars, and spirits marry over time, often improving flavor. (3) Accounting for temperature—batched cocktails are stored cold and served over ice or chilled. (4) Adjusting for ingredient settling or separation. (5) Never batch egg whites, dairy, or carbonation. Proper batching maintains cocktail quality while enabling rapid service for events or high-volume bars.",
          es: "El loteado implica pre-mezclar ingredientes de cócteles en grandes cantidades para servicio eficiente. Ajustes críticos incluyen: (1) Añadir dilución calculada—típicamente 20-25% agua por volumen—para replicar el agua añadida al agitar o revolver con hielo. (2) Permitir que los ingredientes se integren—ácidos cítricos, azúcares y licores se casan con el tiempo, a menudo mejorando el sabor. (3) Contabilizar temperatura—cócteles loteados se almacenan fríos y se sirven sobre hielo o enfriados. (4) Ajustar por sedimentación o separación de ingredientes. (5) Nunca lotear claras de huevo, lácteos o carbonatación. El loteado apropiado mantiene calidad de cóctel mientras permite servicio rápido para eventos o bares de alto volumen.",
          de: "Batching beinhaltet Vorab-Mischen von Cocktail-Zutaten in großen Mengen für effizienten Service. Kritische Anpassungen umfassen: (1) Hinzufügung berechneter Verdünnung—typisch 20-25% Wasser nach Volumen—zur Replikation des durch Schütteln oder Rühren mit Eis hinzugefügten Wassers. (2) Zutatenintegration ermöglichen—Zitrussäuren, Zucker und Spirituosen vermählen sich über Zeit, verbessern oft Geschmack. (3) Temperaturberücksichtigung—gebatchte Cocktails werden kalt gelagert und über Eis oder gekühlt serviert. (4) Anpassung für Zutatensedimentation oder -trennung. (5) Nie Eiweiß, Milchprodukte oder Kohlensäure batchen. Ordnungsgemäßes Batching erhält Cocktail-Qualität während schneller Service für Events oder hochvolumige Bars ermöglicht wird.",
          nl: "Batching houdt in dat cocktail ingrediënten vooraf worden gemengd in grote hoeveelheden voor efficiënte service. Kritieke aanpassingen omvatten: (1) Berekende verdunning toevoegen—typisch 20-25% water per volume—om het water te repliceren dat wordt toegevoegd door schudden of roeren met ijs. (2) Ingrediënten laten integreren—citrus zuren, suikers en sterke dranken trouwen over tijd, verbeteren vaak smaak. (3) Rekening houden met temperatuur—batch cocktails worden koud opgeslagen en geserveerd over ijs of gekoeld. (4) Aanpassen voor ingrediënt bezinking of scheiding. (5) Nooit eiwit, zuivel of carbonatie batchen. Juiste batching behoudt cocktail kwaliteit terwijl snelle service mogelijk wordt gemaakt voor events of hoog-volume bars."
        }
      }]
  };

  // Export for use in the quiz application
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = level9;
  } else if (typeof window !== 'undefined') {
    window.level9 = level9;
  }
})();