// Quiz Template - Level 10: Currencies - Euro (Master Level)
(function() {
  const level10 = {
    name: {
      en: "Euro Currency - Master Level",
      es: "Moneda Euro - Nivel Maestro",
      de: "Euro-Währung - Meisterstufe",
      nl: "Euro Valuta - Meesterniveau"
    },
    questions: [
      {
        question: {
          en: "According to the Impossible Trinity (Mundell-Fleming trilemma), which combination is theoretically impossible for the ECB to maintain simultaneously?",
          es: "Según la Trinidad Imposible (trilema de Mundell-Fleming), ¿qué combinación es teóricamente imposible para el BCE mantener simultáneamente?",
          de: "Laut der Unmöglichen Dreifaltigkeit (Mundell-Fleming-Trilemma), welche Kombination ist für die EZB theoretisch unmöglich gleichzeitig aufrechtzuerhalten?",
          nl: "Volgens de Onmogelijke Driehoek (Mundell-Fleming trilemma), welke combinatie is theoretisch onmogelijk voor de ECB om gelijktijdig te handhaven?"
        },
        options: [
          { en: "Fixed exchange rates, free capital movement, and independent monetary policy", es: "Tipos de cambio fijos, libre movimiento de capital y política monetaria independiente", de: "Feste Wechselkurse, freier Kapitalverkehr und unabhängige Geldpolitik", nl: "Vaste wisselkoersen, vrij kapitaalverkeer en onafhankelijk monetair beleid" },
          { en: "Inflation targeting, fiscal consolidation, and banking supervision", es: "Objetivos de inflación, consolidación fiscal y supervisión bancaria", de: "Inflationsziele, Haushaltskonsolidierung und Bankenaufsicht", nl: "Inflatiedoelstellingen, fiscale consolidatie en banktoezicht" },
          { en: "Price stability, financial stability, and full employment", es: "Estabilidad de precios, estabilidad financiera y pleno empleo", de: "Preisstabilität, Finanzstabilität und Vollbeschäftigung", nl: "Prijsstabiliteit, financiële stabiliteit en volledige werkgelegenheid" },
          { en: "Quantitative easing, negative interest rates, and forward guidance", es: "Flexibilización cuantitativa, tipos de interés negativos y orientación prospectiva", de: "Quantitative Lockerung, negative Zinssätze und Forward Guidance", nl: "Kwantitatieve versoepeling, negatieve rentes en forward guidance" }
        ],
        correct: 0,
        explanation: {
          en: "The Impossible Trinity states that a country cannot simultaneously maintain fixed exchange rates, free capital movement, and independent monetary policy. The eurozone chose free capital movement and independent monetary policy, sacrificing exchange rate flexibility against non-euro currencies.",
          es: "La Trinidad Imposible establece que un país no puede mantener simultáneamente tipos de cambio fijos, libre movimiento de capital y política monetaria independiente. La eurozona eligió el libre movimiento de capital y la política monetaria independiente, sacrificando la flexibilidad del tipo de cambio contra las monedas no euro.",
          de: "Die Unmögliche Dreifaltigkeit besagt, dass ein Land nicht gleichzeitig feste Wechselkurse, freien Kapitalverkehr und unabhängige Geldpolitik aufrechterhalten kann. Die Eurozone wählte freien Kapitalverkehr und unabhängige Geldpolitik und opferte die Wechselkursflexibilität gegenüber Nicht-Euro-Währungen.",
          nl: "De Onmogelijke Driehoek stelt dat een land niet gelijktijdig vaste wisselkoersen, vrij kapitaalverkeer en onafhankelijk monetair beleid kan handhaven. De eurozone koos voor vrij kapitaalverkeer en onafhankelijk monetair beleid, waarbij flexibiliteit van wisselkoersen tegen niet-euro valuta werd opgeofferd."
        }
      },
      {
        question: {
          en: "What is the theoretical foundation behind the ECB's 'below, but close to, 2%' inflation target according to New Keynesian DSGE models?",
          es: "¿Cuál es el fundamento teórico detrás del objetivo de inflación del BCE de 'por debajo, pero cerca del 2%' según los modelos DSGE neokeynesianos?",
          de: "Was ist die theoretische Grundlage für das EZB-Inflationsziel von 'unter, aber nahe 2%' laut neukeynesianischen DSGE-Modellen?",
          nl: "Wat is de theoretische basis achter de ECB's inflatie doelstelling van 'onder, maar dicht bij 2%' volgens New Keynesiaanse DSGE modellen?"
        },
        options: [
          { en: "Zero lower bound constraints and deflationary spiral prevention", es: "Restricciones del límite inferior cero y prevención de espirales deflacionarias", de: "Nullzinsschranken-Beschränkungen und Deflationsspiralprävention", nl: "Nul-ondergrens beperkingen en preventie van deflatoire spiralen" },
          { en: "Optimal taxation theory and Ramsey steady state conditions", es: "Teoría de tributación óptima y condiciones de estado estacionario de Ramsey", de: "Optimale Besteuerungstheorie und Ramsey-Steady-State-Bedingungen", nl: "Optimale belastingtheorie en Ramsey steady state voorwaarden" },
          { en: "Lucas critique and rational expectations equilibrium", es: "Crítica de Lucas y equilibrio de expectativas racionales", de: "Lucas-Kritik und rationales Erwartungsgleichgewicht", nl: "Lucas kritiek en rationele verwachtingen evenwicht" },
          { en: "Real business cycle theory and productivity shock absorption", es: "Teoría del ciclo económico real y absorción de choques de productividad", de: "Reale Konjunkturzyklustheorie und Produktivitätsschockabsorption", nl: "Reële conjunctuurcyclus theorie en productiviteitsschok absorptie" }
        ],
        correct: 0,
        explanation: {
          en: "The 2% target provides a buffer against deflationary risks and zero lower bound constraints. In DSGE models, this level balances the costs of moderate inflation against the benefits of having room for conventional monetary policy during downturns, preventing deflationary spirals that could lead to liquidity traps.",
          es: "El objetivo del 2% proporciona un amortiguador contra los riesgos deflacionarios y las restricciones del límite inferior cero. En los modelos DSGE, este nivel equilibra los costos de la inflación moderada contra los beneficios de tener espacio para la política monetaria convencional durante las recesiones, previniendo espirales deflacionarias que podrían llevar a trampas de liquidez.",
          de: "Das 2%-Ziel bietet einen Puffer gegen Deflationsrisiken und Nullzinsschranken-Beschränkungen. In DSGE-Modellen balanciert dieses Niveau die Kosten moderater Inflation gegen die Vorteile aus, Raum für konventionelle Geldpolitik während Abschwüngen zu haben, um Deflationsspiralen zu verhindern, die zu Liquiditätsfallen führen könnten.",
          nl: "Het 2% doel biedt een buffer tegen deflatoire risico's en nul-ondergrens beperkingen. In DSGE modellen balanceert dit niveau de kosten van gematigde inflatie tegen de voordelen van ruimte voor conventioneel monetair beleid tijdens recessies, waardoor deflatoire spiralen worden voorkomen die tot liquiditeitsvalstrikken zouden kunnen leiden."
        }
      },
      {
        question: {
          en: "How does the Calvo pricing mechanism in New Keynesian models justify the ECB's gradualist approach to monetary policy adjustments?",
          es: "¿Cómo justifica el mecanismo de precios de Calvo en los modelos neokeynesianos el enfoque gradualista del BCE para los ajustes de política monetaria?",
          de: "Wie rechtfertigt der Calvo-Preismechanismus in neukeynesianischen Modellen den gradualistischen Ansatz der EZB bei geldpolitischen Anpassungen?",
          nl: "Hoe rechtvaardigt het Calvo prijsmechanisme in New Keynesiaanse modellen de geleidelijke benadering van de ECB voor monetaire beleidsaanpassingen?"
        },
        options: [
          { en: "Sticky prices create persistent real effects of nominal shocks, requiring gradual policy to avoid overshooting", es: "Los precios rígidos crean efectos reales persistentes de choques nominales, requiriendo política gradual para evitar sobrepaso", de: "Klebrige Preise schaffen persistente reale Effekte nominaler Schocks, die graduelle Politik erfordern, um Überschießen zu vermeiden", nl: "Kleverige prijzen creëren persistente reële effecten van nominale schokken, wat geleidelijk beleid vereist om overschieten te voorkomen" },
          { en: "Random price adjustment creates information asymmetries requiring forward guidance", es: "El ajuste aleatorio de precios crea asimetrías de información que requieren orientación prospectiva", de: "Zufällige Preisanpassung schafft Informationsasymmetrien, die Forward Guidance erfordern", nl: "Willekeurige prijsaanpassing creëert informatie asymmetrieën die forward guidance vereisen" },
          { en: "Monopolistic competition requires antitrust considerations in monetary policy", es: "La competencia monopolística requiere consideraciones antimonopolio en la política monetaria", de: "Monopolistische Konkurrenz erfordert kartellrechtliche Überlegungen in der Geldpolitik", nl: "Monopolistische concurrentie vereist mededingingsoverwegingen in monetair beleid" },
          { en: "Heterogeneous expectations require consensus-building through communication", es: "Las expectativas heterogéneas requieren construcción de consenso a través de la comunicación", de: "Heterogene Erwartungen erfordern Konsensbildung durch Kommunikation", nl: "Heterogene verwachtingen vereisen consensusvorming door communicatie" }
        ],
        correct: 0,
        explanation: {
          en: "In Calvo pricing models, only a fraction of firms can adjust prices in each period. This creates price stickiness, meaning monetary policy has persistent real effects. Gradual adjustments prevent overshooting because rapid policy changes can create excessive volatility when prices adjust slowly and unevenly across the economy.",
          es: "En los modelos de precios de Calvo, solo una fracción de empresas puede ajustar precios en cada período. Esto crea rigidez de precios, lo que significa que la política monetaria tiene efectos reales persistentes. Los ajustes graduales previenen el sobrepaso porque los cambios rápidos de política pueden crear volatilidad excesiva cuando los precios se ajustan lenta y desigualmente en la economía.",
          de: "In Calvo-Preismodellen kann nur ein Bruchteil der Firmen die Preise in jeder Periode anpassen. Dies schafft Preisrigidität, was bedeutet, dass Geldpolitik persistente reale Effekte hat. Graduelle Anpassungen verhindern Überschießen, weil schnelle Politikänderungen excessive Volatilität schaffen können, wenn sich Preise langsam und ungleichmäßig in der Wirtschaft anpassen.",
          nl: "In Calvo prijsmodellen kan slechts een fractie van bedrijven prijzen aanpassen in elke periode. Dit creëert prijsrigiditeit, wat betekent dat monetair beleid persistente reële effecten heeft. Geleidelijke aanpassingen voorkomen overschieten omdat snelle beleidsveranderingen excessieve volatiliteit kunnen creëren wanneer prijzen langzaam en ongelijk aanpassen in de economie."
        }
      },
      {
        question: {
          en: "What role does the 'divine coincidence' concept play in understanding the ECB's dual mandate conflict between price stability and financial stability?",
          es: "¿Qué papel juega el concepto de 'coincidencia divina' en entender el conflicto de doble mandato del BCE entre estabilidad de precios y estabilidad financiera?",
          de: "Welche Rolle spielt das Konzept der 'göttlichen Koinzidenz' beim Verständnis des Doppelmandatkonflikts der EZB zwischen Preisstabilität und Finanzstabilität?",
          nl: "Welke rol speelt het 'goddelijke toeval' concept in het begrijpen van de ECB's dubbele mandaat conflict tussen prijsstabiliteit en financiële stabiliteit?"
        },
        options: [
          { en: "It explains why targeting price stability automatically ensures financial stability under efficient markets", es: "Explica por qué dirigirse a la estabilidad de precios automáticamente asegura la estabilidad financiera bajo mercados eficientes", de: "Es erklärt, warum das Anvisieren von Preisstabilität automatisch Finanzstabilität unter effizienten Märkten gewährleistet", nl: "Het verklaart waarom het nastreven van prijsstabiliteit automatisch financiële stabiliteit waarborgt onder efficiënte markten" },
          { en: "It demonstrates the impossibility of achieving both objectives simultaneously in practice", es: "Demuestra la imposibilidad de lograr ambos objetivos simultáneamente en la práctica", de: "Es demonstriert die Unmöglichkeit, beide Ziele gleichzeitig in der Praxis zu erreichen", nl: "Het toont de onmogelijkheid aan om beide doelstellingen gelijktijdig te bereiken in de praktijk" },
          { en: "It suggests that optimal monetary policy can align both objectives without trade-offs under specific conditions", es: "Sugiere que la política monetaria óptima puede alinear ambos objetivos sin compromisos bajo condiciones específicas", de: "Es deutet darauf hin, dass optimale Geldpolitik beide Ziele ohne Trade-offs unter spezifischen Bedingungen ausrichten kann", nl: "Het suggereert dat optimaal monetair beleid beide doelstellingen kan uitlijnen zonder afwegingen onder specifieke omstandigheden" },
          { en: "It requires the ECB to prioritize financial stability over price stability during crises", es: "Requiere que el BCE priorice la estabilidad financiera sobre la estabilidad de precios durante las crisis", de: "Es erfordert, dass die EZB Finanzstabilität über Preisstabilität während Krisen priorisiert", nl: "Het vereist dat de ECB financiële stabiliteit prioriteit geeft boven prijsstabiliteit tijdens crises" }
        ],
        correct: 2,
        explanation: {
          en: "The divine coincidence suggests that under certain conditions (flexible prices, efficient markets, absence of cost-push shocks), stabilizing inflation also stabilizes the output gap, creating no trade-off between price and financial stability. However, financial frictions and asset price bubbles can break this coincidence, requiring more complex policy responses.",
          es: "La coincidencia divina sugiere que bajo ciertas condiciones (precios flexibles, mercados eficientes, ausencia de choques de costos), estabilizar la inflación también estabiliza la brecha del producto, no creando compromiso entre estabilidad de precios y financiera. Sin embargo, las fricciones financieras y las burbujas de precios de activos pueden romper esta coincidencia, requiriendo respuestas políticas más complejas.",
          de: "Die göttliche Koinzidenz deutet darauf hin, dass unter bestimmten Bedingungen (flexible Preise, effiziente Märkte, Abwesenheit von Cost-Push-Schocks) die Stabilisierung der Inflation auch die Produktionslücke stabilisiert, wodurch kein Trade-off zwischen Preis- und Finanzstabilität entsteht. Jedoch können Finanzfriktionen und Vermögenspreisblasen diese Koinzidenz brechen, was komplexere Politikantworten erfordert.",
          nl: "Het goddelijke toeval suggereert dat onder bepaalde omstandigheden (flexibele prijzen, efficiënte markten, afwezigheid van kostendrukte schokken), het stabiliseren van inflatie ook de output gap stabiliseert, waardoor geen afweging ontstaat tussen prijs- en financiële stabiliteit. Echter, financiële fricties en vermogensprijsbubbels kunnen dit toeval doorbreken, wat complexere beleidsreacties vereist."
        }
      },
      {
        question: {
          en: "How does the concept of 'fiscal dominance' in Sargent-Wallace models relate to the ECB's independence and the fiscal theory of the price level?",
          es: "¿Cómo se relaciona el concepto de 'dominancia fiscal' en los modelos de Sargent-Wallace con la independencia del BCE y la teoría fiscal del nivel de precios?",
          de: "Wie verhält sich das Konzept der 'fiskalischen Dominanz' in Sargent-Wallace-Modellen zur EZB-Unabhängigkeit und der fiskalischen Theorie des Preisniveaus?",
          nl: "Hoe verhoudt het concept van 'fiscale dominantie' in Sargent-Wallace modellen zich tot de ECB's onafhankelijkheid en de fiscale theorie van het prijsniveau?"
        },
        options: [
          { en: "Fiscal dominance implies that monetary policy must ultimately accommodate fiscal needs, potentially compromising price stability", es: "La dominancia fiscal implica que la política monetaria debe finalmente acomodar las necesidades fiscales, potencialmente comprometiendo la estabilidad de precios", de: "Fiskalische Dominanz impliziert, dass Geldpolitik letztendlich fiskalische Bedürfnisse akkommodieren muss, was möglicherweise die Preisstabilität gefährdet", nl: "Fiscale dominantie impliceert dat monetair beleid uiteindelijk fiscale behoeften moet accommoderen, wat mogelijk prijsstabiliteit in gevaar brengt" },
          { en: "Central bank independence automatically prevents any form of fiscal influence on monetary policy", es: "La independencia del banco central previene automáticamente cualquier forma de influencia fiscal en la política monetaria", de: "Zentralbankautonomie verhindert automatisch jede Form fiskalischen Einflusses auf die Geldpolitik", nl: "Centrale bank onafhankelijkheid voorkomt automatisch elke vorm van fiscale invloed op monetair beleid" },
          { en: "Fiscal policy determines inflation regardless of monetary policy actions under all circumstances", es: "La política fiscal determina la inflación independientemente de las acciones de política monetaria bajo todas las circunstancias", de: "Fiskalpolitik bestimmt Inflation unabhängig von geldpolitischen Maßnahmen unter allen Umständen", nl: "Fiscaal beleid bepaalt inflatie ongeacht monetaire beleidsacties onder alle omstandigheden" },
          { en: "Monetary and fiscal authorities must coordinate perfectly to achieve optimal outcomes", es: "Las autoridades monetarias y fiscales deben coordinarse perfectamente para lograr resultados óptimos", de: "Geld- und Fiskalbehörden müssen sich perfekt koordinieren, um optimale Ergebnisse zu erzielen", nl: "Monetaire en fiscale autoriteiten moeten perfect coördineren om optimale resultaten te bereiken" }
        ],
        correct: 0,
        explanation: {
          en: "In Sargent-Wallace models, fiscal dominance occurs when unsustainable fiscal policies force the central bank to eventually monetize debt, compromising price stability. The fiscal theory of the price level suggests that fiscal policy can determine inflation when fiscal authority is dominant. ECB independence aims to prevent this by maintaining monetary dominance over price determination.",
          es: "En los modelos de Sargent-Wallace, la dominancia fiscal ocurre cuando las políticas fiscales insostenibles fuerzan al banco central a eventualmente monetizar la deuda, comprometiendo la estabilidad de precios. La teoría fiscal del nivel de precios sugiere que la política fiscal puede determinar la inflación cuando la autoridad fiscal es dominante. La independencia del BCE pretende prevenir esto manteniendo la dominancia monetaria sobre la determinación de precios.",
          de: "In Sargent-Wallace-Modellen tritt fiskalische Dominanz auf, wenn unhaltbare Fiskalpolitiken die Zentralbank zwingen, letztendlich Schulden zu monetarisieren, was die Preisstabilität gefährdet. Die fiskalische Theorie des Preisniveaus deutet darauf hin, dass Fiskalpolitik Inflation bestimmen kann, wenn fiskalische Autorität dominant ist. EZB-Unabhängigkeit zielt darauf ab, dies durch Aufrechterhaltung geldpolitischer Dominanz über Preisbestimmung zu verhindern.",
          nl: "In Sargent-Wallace modellen treedt fiscale dominantie op wanneer onhoudbaar fiscaal beleid de centrale bank dwingt om uiteindelijk schuld te monetariseren, wat prijsstabiliteit in gevaar brengt. De fiscale theorie van het prijsniveau suggereert dat fiscaal beleid inflatie kan bepalen wanneer fiscale autoriteit dominant is. ECB onafhankelijkheid beoogt dit te voorkomen door monetaire dominantie over prijsbepaling te handhaven."
        }
      },
      {
        question: {
          en: "What is the theoretical basis for the ECB's use of negative interest rates according to New Keynesian models with financial intermediation?",
          es: "¿Cuál es la base teórica para el uso del BCE de tipos de interés negativos según los modelos neokeynesianos con intermediación financiera?",
          de: "Was ist die theoretische Grundlage für die Verwendung negativer Zinssätze durch die EZB laut neukeynesianischen Modellen mit Finanzintermediation?",
          nl: "Wat is de theoretische basis voor de ECB's gebruik van negatieve rentes volgens New Keynesiaanse modellen met financiële intermediatie?"
        },
        options: [
          { en: "Breaking the zero lower bound to achieve necessary negative real rates during deflationary pressures", es: "Romper el límite inferior cero para lograr las tasas reales negativas necesarias durante presiones deflacionarias", de: "Durchbrechen der Nullzinsschranke, um notwendige negative Realzinsen während deflationärer Drücke zu erreichen", nl: "Doorbreken van de nul-ondergrens om noodzakelijke negatieve reële rentes te bereiken tijdens deflatoire druk" },
          { en: "Encouraging excessive risk-taking to stimulate economic growth through financial channels", es: "Fomentar la toma excesiva de riesgos para estimular el crecimiento económico a través de canales financieros", de: "Förderung übermäßiger Risikobereitschaft zur Stimulierung des Wirtschaftswachstums durch Finanzkanäle", nl: "Aanmoedigen van excessieve risiconame om economische groei te stimuleren via financiële kanalen" },
          { en: "Reducing bank profitability to force consolidation in the banking sector", es: "Reducir la rentabilidad bancaria para forzar la consolidación en el sector bancario", de: "Reduzierung der Bankrentabilität zur Erzwingung von Konsolidierung im Bankensektor", nl: "Verminderen van bankwinstgevendheid om consolidatie in de banksector af te dwingen" },
          { en: "Creating arbitrage opportunities for international investors in currency markets", es: "Crear oportunidades de arbitraje para inversores internacionales en mercados de divisas", de: "Schaffen von Arbitragemöglichkeiten für internationale Investoren in Devisenmärkten", nl: "Creëren van arbitrage mogelijkheden voor internationale investeerders in valutamarkten" }
        ],
        correct: 0,
        explanation: {
          en: "In New Keynesian models with financial intermediation, negative policy rates allow central banks to achieve the necessary negative real interest rates when inflation expectations are below target and the economy faces deflationary pressures. This breaks the zero lower bound constraint, though it may create side effects on bank profitability and financial stability.",
          es: "En los modelos neokeynesianos con intermediación financiera, las tasas de política negativas permiten a los bancos centrales lograr las tasas de interés reales negativas necesarias cuando las expectativas de inflación están por debajo del objetivo y la economía enfrenta presiones deflacionarias. Esto rompe la restricción del límite inferior cero, aunque puede crear efectos secundarios en la rentabilidad bancaria y la estabilidad financiera.",
          de: "In neukeynesianischen Modellen mit Finanzintermediation ermöglichen negative Leitzinsen Zentralbanken, die notwendigen negativen Realzinsen zu erreichen, wenn Inflationserwartungen unter dem Ziel liegen und die Wirtschaft deflationären Drücken ausgesetzt ist. Dies durchbricht die Nullzinsschranken-Beschränkung, obwohl es Nebenwirkungen auf Bankrentabilität und Finanzstabilität haben kann.",
          nl: "In New Keynesiaanse modellen met financiële intermediatie stellen negatieve beleidsrentes centrale banken in staat om de noodzakelijke negatieve reële rentes te bereiken wanneer inflatie verwachtingen onder het doel liggen en de economie deflatoire druk ervaart. Dit doorbreekt de nul-ondergrens beperking, hoewel het neveneffecten kan hebben op bankwinstgevendheid en financiële stabiliteit."
        }
      },
      {
        question: {
          en: "How does the 'bank lending channel' transmission mechanism differ from the 'balance sheet channel' in ECB monetary policy effectiveness?",
          es: "¿Cómo difiere el mecanismo de transmisión del 'canal de préstamos bancarios' del 'canal del balance' en la efectividad de la política monetaria del BCE?",
          de: "Wie unterscheidet sich der Übertragungsmechanismus des 'Bankkreditkanals' vom 'Bilanzkanal' in der Wirksamkeit der EZB-Geldpolitik?",
          nl: "Hoe verschilt het 'bankleningkanaal' transmissiemechanisme van het 'balanskanaal' in ECB monetaire beleidseffectiviteit?"
        },
        options: [
          { en: "Bank lending channel affects loan supply through bank capital constraints; balance sheet channel affects borrower demand through collateral values", es: "El canal de préstamos bancarios afecta la oferta de préstamos a través de restricciones de capital bancario; el canal del balance afecta la demanda del prestatario a través de valores de garantía", de: "Bankkreditkanal beeinflusst Kreditangebot durch Bankkapitalbeschränkungen; Bilanzkanal beeinflusst Kreditnachfrage durch Sicherheitenwerte", nl: "Bankleningkanaal beïnvloedt kredietaanbod door bankkapitaalbeperkingen; balanskanaal beïnvloedt leningvraag door onderpandwaarden" },
          { en: "Both channels operate identically through interest rate adjustments only", es: "Ambos canales operan idénticamente solo a través de ajustes de tasas de interés", de: "Beide Kanäle funktionieren identisch nur durch Zinsanpassungen", nl: "Beide kanalen werken identiek alleen door renteaanpassingen" },
          { en: "Bank lending channel affects international capital flows; balance sheet channel affects domestic investment", es: "El canal de préstamos bancarios afecta los flujos de capital internacional; el canal del balance afecta la inversión doméstica", de: "Bankkreditkanal beeinflusst internationale Kapitalflüsse; Bilanzkanal beeinflusst inländische Investitionen", nl: "Bankleningkanaal beïnvloedt internationale kapitaalstromen; balanskanaal beïnvloedt binnenlandse investeringen" },
          { en: "Balance sheet channel only operates during financial crises; bank lending channel operates continuously", es: "El canal del balance solo opera durante crisis financieras; el canal de préstamos bancarios opera continuamente", de: "Bilanzkanal funktioniert nur während Finanzkrisen; Bankkreditkanal funktioniert kontinuierlich", nl: "Balanskanaal werkt alleen tijdens financiële crises; bankleningkanaal werkt continu" }
        ],
        correct: 0,
        explanation: {
          en: "The bank lending channel focuses on how monetary policy affects banks' ability to lend through changes in bank funding costs and capital constraints. The balance sheet channel operates through borrowers' net worth and collateral values, affecting their ability to obtain credit. Both are crucial for ECB policy transmission, especially in bank-based financial systems.",
          es: "El canal de préstamos bancarios se enfoca en cómo la política monetaria afecta la capacidad de los bancos para prestar a través de cambios en los costos de financiamiento bancario y restricciones de capital. El canal del balance opera a través del patrimonio neto de los prestatarios y valores de garantía, afectando su capacidad para obtener crédito. Ambos son cruciales para la transmisión de política del BCE, especialmente en sistemas financieros basados en bancos.",
          de: "Der Bankkreditkanal konzentriert sich darauf, wie Geldpolitik die Fähigkeit der Banken zur Kreditvergabe durch Änderungen der Bankfinanzierungskosten und Kapitalbeschränkungen beeinflusst. Der Bilanzkanal funktioniert durch das Nettovermögen der Kreditnehmer und Sicherheitenwerte, was ihre Fähigkeit zur Kreditbeschaffung beeinflusst. Beide sind entscheidend für die EZB-Politikübertragung, besonders in bankbasierten Finanzsystemen.",
          nl: "Het bankleningkanaal richt zich op hoe monetair beleid de mogelijkheid van banken om te lenen beïnvloedt door veranderingen in bankfinancieringskosten en kapitaalbeperkingen. Het balanskanaal werkt door het netto vermogen van leners en onderpandwaarden, wat hun mogelijkheid om krediet te verkrijgen beïnvloedt. Beide zijn cruciaal voor ECB beleidstransmissie, vooral in bank-gebaseerde financiële systemen."
        }
      },
      {
        question: {
          en: "What role does 'hysteresis' play in the ECB's assessment of potential output and the natural rate of unemployment in DSGE models?",
          es: "¿Qué papel juega la 'histéresis' en la evaluación del BCE del producto potencial y la tasa natural de desempleo en los modelos DSGE?",
          de: "Welche Rolle spielt 'Hysterese' in der EZB-Bewertung des Potentialoutputs und der natürlichen Arbeitslosenrate in DSGE-Modellen?",
          nl: "Welke rol speelt 'hysterese' in de ECB's beoordeling van potentiële output en de natuurlijke werkloosheidsgraad in DSGE modellen?"
        },
        options: [
          { en: "Cyclical unemployment becomes structural through skill deterioration and labor market scarring effects", es: "El desempleo cíclico se vuelve estructural a través del deterioro de habilidades y efectos de cicatrización del mercado laboral", de: "Zyklische Arbeitslosigkeit wird durch Qualifikationsverschlechterung und Arbeitsmarkt-Narbeneffekte strukturell", nl: "Cyclische werkloosheid wordt structureel door vaardigheidsverslechtering en arbeidsmarkt litteken effecten" },
          { en: "Monetary policy has no long-term effects on real variables under any circumstances", es: "La política monetaria no tiene efectos a largo plazo en las variables reales bajo ninguna circunstancia", de: "Geldpolitik hat unter keinen Umständen langfristige Effekte auf reale Variablen", nl: "Monetair beleid heeft onder geen enkele omstandigheid langetermijneffecten op reële variabelen" },
          { en: "Inflation expectations become permanently anchored regardless of economic conditions", es: "Las expectativas de inflación se anclan permanentemente independientemente de las condiciones económicas", de: "Inflationserwartungen werden dauerhaft verankert unabhängig von den wirtschaftlichen Bedingungen", nl: "Inflatie verwachtingen worden permanent verankerd ongeacht economische omstandigheden" },
          { en: "Technological progress accelerates during economic downturns automatically", es: "El progreso tecnológico se acelera durante las recesiones económicas automáticamente", de: "Technologischer Fortschritt beschleunigt sich während wirtschaftlicher Abschwünge automatisch", nl: "Technologische vooruitgang versnelt automatisch tijdens economische neergang" }
        ],
        correct: 0,
        explanation: {
          en: "Hysteresis in DSGE models suggests that temporary cyclical downturns can have permanent effects on potential output and the natural rate of unemployment. Long-term unemployment can lead to skill deterioration, labor market dropout, and reduced capital formation, making cyclical unemployment structural. This affects ECB policy as it implies monetary accommodation might have lasting benefits.",
          es: "La histéresis en los modelos DSGE sugiere que las recesiones cíclicas temporales pueden tener efectos permanentes en el producto potencial y la tasa natural de desempleo. El desempleo a largo plazo puede llevar al deterioro de habilidades, abandono del mercado laboral y reducción de la formación de capital, convirtiendo el desempleo cíclico en estructural. Esto afecta la política del BCE ya que implica que la acomodación monetaria podría tener beneficios duraderos.",
          de: "Hysterese in DSGE-Modellen deutet darauf hin, dass temporäre zyklische Abschwünge permanente Effekte auf Potentialoutput und natürliche Arbeitslosenrate haben können. Langzeitarbeitslosigkeit kann zu Qualifikationsverschlechterung, Arbeitsmarktaustritt und reduzierter Kapitalbildung führen, wodurch zyklische Arbeitslosigkeit strukturell wird. Dies beeinflusst EZB-Politik, da es impliziert, dass geldpolitische Akkommodierung dauerhafte Vorteile haben könnte.",
          nl: "Hysterese in DSGE modellen suggereert dat tijdelijke cyclische neergangen permanente effecten kunnen hebben op potentiële output en de natuurlijke werkloosheidsgraad. Langdurige werkloosheid kan leiden tot vaardigheidsverslechtering, arbeidsmarkt uitval en verminderde kapitaalvorming, waardoor cyclische werkloosheid structureel wordt. Dit beïnvloedt ECB beleid omdat het impliceert dat monetaire accommodatie blijvende voordelen zou kunnen hebben."
        }
      },
      {
        question: {
          en: "How does the 'risk-taking channel' of monetary transmission relate to the concept of 'search for yield' in low interest rate environments?",
          es: "¿Cómo se relaciona el 'canal de toma de riesgos' de la transmisión monetaria con el concepto de 'búsqueda de rendimiento' en entornos de bajas tasas de interés?",
          de: "Wie verhält sich der 'Risikokanal' der geldpolitischen Übertragung zum Konzept der 'Renditesuche' in Niedrigzinsumgebungen?",
          nl: "Hoe verhoudt het 'risiconemingskanaal' van monetaire transmissie zich tot het concept van 'zoeken naar rendement' in lage rente omgevingen?"
        },
        options: [
          { en: "Low rates increase risk appetite and asset prices, potentially creating financial instability through excessive leverage", es: "Las bajas tasas aumentan el apetito por el riesgo y los precios de activos, potencialmente creando inestabilidad financiera a través del apalancamiento excesivo", de: "Niedrige Zinsen erhöhen Risikobereitschaft und Vermögenspreise, was möglicherweise durch übermäßige Verschuldung finanzielle Instabilität schafft", nl: "Lage rentes verhogen risicobereidheid en activaprijzen, wat mogelijk financiële instabiliteit creëert door excessieve hefboomwerking" },
          { en: "Risk-taking channel only operates during financial crises and has no relevance in normal times", es: "El canal de toma de riesgos solo opera durante crisis financieras y no tiene relevancia en tiempos normales", de: "Risikokanal funktioniert nur während Finanzkrisen und hat keine Relevanz in normalen Zeiten", nl: "Risiconemingskanaal werkt alleen tijdens financiële crises en heeft geen relevantie in normale tijden" },
          { en: "Search for yield automatically ensures optimal capital allocation without any negative side effects", es: "La búsqueda de rendimiento asegura automáticamente la asignación óptima de capital sin efectos secundarios negativos", de: "Renditesuche gewährleistet automatisch optimale Kapitalallokation ohne negative Nebenwirkungen", nl: "Zoeken naar rendement zorgt automatisch voor optimale kapitaalallocatie zonder negatieve bijeffecten" },
          { en: "Low interest rates discourage all forms of investment and risk-taking universally", es: "Las bajas tasas de interés desalientan todas las formas de inversión y toma de riesgos universalmente", de: "Niedrige Zinsen entmutigen alle Formen von Investitionen und Risikobereitschaft universell", nl: "Lage rentes ontmoedigen alle vormen van investering en risiconame universeel" }
        ],
        correct: 0,
        explanation: {
          en: "The risk-taking channel suggests that low interest rates encourage investors to 'search for yield' by taking on more risk to maintain target returns. This can lead to asset price bubbles, excessive leverage, and financial instability. The ECB must balance stimulative effects with potential risks to financial stability when implementing accommodative monetary policy.",
          es: "El canal de toma de riesgos sugiere que las bajas tasas de interés animan a los inversores a 'buscar rendimiento' asumiendo más riesgo para mantener los retornos objetivo. Esto puede llevar a burbujas de precios de activos, apalancamiento excesivo e inestabilidad financiera. El BCE debe equilibrar los efectos estimulantes con los riesgos potenciales para la estabilidad financiera al implementar política monetaria acomodaticia.",
          de: "Der Risikokanal deutet darauf hin, dass niedrige Zinsen Investoren ermutigen, 'nach Rendite zu suchen', indem sie mehr Risiko eingehen, um Zielrenditen zu erhalten. Dies kann zu Vermögenspreisblasen, übermäßiger Verschuldung und finanzieller Instabilität führen. Die EZB muss stimulierende Effekte mit potenziellen Risiken für die Finanzstabilität ausbalancieren, wenn sie akkommodierende Geldpolitik implementiert.",
          nl: "Het risiconemingskanaal suggereert dat lage rentes investeerders aanmoedigen om 'naar rendement te zoeken' door meer risico te nemen om doelrendementen te behouden. Dit kan leiden tot activaprijsbubbels, excessieve hefboomwerking en financiële instabiliteit. De ECB moet stimulerende effecten balanceren met potentiële risico's voor financiële stabiliteit bij het implementeren van accommoderend monetair beleid."
        }
      },
      {
        question: {
          en: "What is the significance of the 'reversal rate' concept in understanding the effectiveness limits of ECB's negative interest rate policy?",
          es: "¿Cuál es la significancia del concepto de 'tasa de reversión' en entender los límites de efectividad de la política de tasas de interés negativas del BCE?",
          de: "Was ist die Bedeutung des 'Umkehrzinssatz'-Konzepts für das Verständnis der Wirksamkeitsgrenzen der negativen Zinspolitik der EZB?",
          nl: "Wat is de betekenis van het 'omkeertarief' concept in het begrijpen van de effectiviteitsgrenzen van de ECB's negatieve rente beleid?"
        },
        options: [
          { en: "Below the reversal rate, further cuts become contractionary as bank profitability deteriorates and credit supply contracts", es: "Por debajo de la tasa de reversión, más recortes se vuelven contractivos ya que la rentabilidad bancaria se deteriora y la oferta de crédito se contrae", de: "Unter dem Umkehrzinssatz werden weitere Senkungen kontraktiv, da sich die Bankrentabilität verschlechtert und das Kreditangebot kontrahiert", nl: "Onder het omkeertarief worden verdere verlagingen contractief omdat bankwinstgevendheid verslechtert en kredietaanbod krimpt" },
          { en: "The reversal rate represents the optimal negative rate that maximizes economic growth permanently", es: "La tasa de reversión representa la tasa negativa óptima que maximiza el crecimiento económico permanentemente", de: "Der Umkehrzinssatz repräsentiert den optimalen negativen Zinssatz, der Wirtschaftswachstum dauerhaft maximiert", nl: "Het omkeertarief vertegenwoordigt de optimale negatieve rente die economische groei permanent maximaliseert" },
          { en: "Banks automatically increase lending when rates fall below the reversal rate", es: "Los bancos automáticamente aumentan los préstamos cuando las tasas caen por debajo de la tasa de reversión", de: "Banken erhöhen automatisch die Kreditvergabe, wenn die Zinsen unter den Umkehrzinssatz fallen", nl: "Banken verhogen automatisch de kredietverlening wanneer rentes onder het omkeertarief vallen" },
          { en: "The reversal rate only applies to government bonds and has no effect on private lending", es: "La tasa de reversión solo se aplica a bonos gubernamentales y no tiene efecto en los préstamos privados", de: "Der Umkehrzinssatz gilt nur für Staatsanleihen und hat keinen Effekt auf private Kreditvergabe", nl: "Het omkeertarief geldt alleen voor staatsobligaties en heeft geen effect op private kredietverlening" }
        ],
        correct: 0,
        explanation: {
          en: "The reversal rate is the level below which further interest rate cuts become contractionary rather than expansionary. When rates fall too far below zero, bank profit margins compress severely, leading to reduced credit supply that outweighs the stimulative effects of lower borrowing costs. This concept helps explain why ECB negative rates have limits.",
          es: "La tasa de reversión es el nivel por debajo del cual más recortes de tasas de interés se vuelven contractivos en lugar de expansivos. Cuando las tasas caen demasiado por debajo de cero, los márgenes de beneficio bancarios se comprimen severamente, llevando a una oferta de crédito reducida que supera los efectos estimulantes de menores costos de endeudamiento. Este concepto ayuda a explicar por qué las tasas negativas del BCE tienen límites.",
          de: "Der Umkehrzinssatz ist das Niveau, unter dem weitere Zinssenkungen kontraktiv statt expansiv werden. Wenn die Zinsen zu weit unter null fallen, komprimieren sich die Bankgewinnmargen stark, was zu reduziertem Kreditangebot führt, das die stimulierenden Effekte niedrigerer Kreditkosten überwiegt. Dieses Konzept hilft zu erklären, warum EZB-Negativzinsen Grenzen haben.",
          nl: "Het omkeertarief is het niveau waaronder verdere renteverlagingen contractief worden in plaats van expansief. Wanneer rentes te ver onder nul vallen, krimpen bankwinstmarges ernstig, wat leidt tot verminderd kredietaanbod dat de stimulerende effecten van lagere leenkosten overtreft. Dit concept helpt verklaren waarom ECB negatieve rentes grenzen hebben."
        }
      },
      {
        question: {
          en: "How does the 'signaling channel' of monetary policy interact with the 'portfolio balance channel' in ECB's quantitative easing operations?",
          es: "¿Cómo interactúa el 'canal de señalización' de la política monetaria con el 'canal de equilibrio de cartera' en las operaciones de flexibilización cuantitativa del BCE?",
          de: "Wie interagiert der 'Signalkanal' der Geldpolitik mit dem 'Portfolioausgleichskanal' in den quantitativen Lockerungsoperationen der EZB?",
          nl: "Hoe interageert het 'signaalkanaal' van monetair beleid met het 'portfolio balanskanaal' in ECB's kwantitatieve versoepeling operaties?"
        },
        options: [
          { en: "Signaling reinforces portfolio effects by communicating commitment to low rates, while portfolio rebalancing amplifies duration risk premiums", es: "La señalización refuerza los efectos de cartera comunicando compromiso con tasas bajas, mientras que el reequilibrio de cartera amplifica las primas de riesgo de duración", de: "Signaling verstärkt Portfolioeffekte durch Kommunikation von Niedrigzinsverpflichtung, während Portfolioumschichtung Laufzeitrisikoprämien verstärkt", nl: "Signaling versterkt portfolio effecten door toewijding aan lage rentes te communiceren, terwijl portfolio herbalancering looptijdrisicopremies versterkt" },
          { en: "Both channels operate independently without any interaction or reinforcement effects", es: "Ambos canales operan independientemente sin efectos de interacción o refuerzo", de: "Beide Kanäle funktionieren unabhängig ohne Interaktions- oder Verstärkungseffekte", nl: "Beide kanalen werken onafhankelijk zonder interactie of versterkingseffecten" },
          { en: "Portfolio channel completely dominates signaling effects in all market conditions", es: "El canal de cartera domina completamente los efectos de señalización en todas las condiciones de mercado", de: "Portfoliokanal dominiert völlig Signaleffekte unter allen Marktbedingungen", nl: "Portfolio kanaal domineert volledig signaaleffecten onder alle marktomstandigheden" },
          { en: "Signaling channel only works through inflation expectations while portfolio channel affects real interest rates", es: "El canal de señalización solo funciona a través de expectativas de inflación mientras que el canal de cartera afecta las tasas de interés reales", de: "Signalkanal funktioniert nur durch Inflationserwartungen, während Portfoliokanal reale Zinsen beeinflusst", nl: "Signaalkanaal werkt alleen door inflatie verwachtingen terwijl portfolio kanaal reële rentes beïnvloedt" }
        ],
        correct: 0,
        explanation: {
          en: "The signaling channel communicates the ECB's commitment to keeping rates low for extended periods, which reinforces the portfolio balance effects of QE. Portfolio rebalancing occurs as investors substitute between assets, reducing term premiums. These channels work synergistically: signaling enhances portfolio effects by providing credible commitment, while large-scale purchases validate the signaling.",
          es: "El canal de señalización comunica el compromiso del BCE de mantener las tasas bajas por períodos extendidos, lo que refuerza los efectos de equilibrio de cartera del QE. El reequilibrio de cartera ocurre cuando los inversores sustituyen entre activos, reduciendo las primas de plazo. Estos canales funcionan sinérgicamente: la señalización mejora los efectos de cartera proporcionando compromiso creíble, mientras que las compras a gran escala validan la señalización.",
          de: "Der Signalkanal kommuniziert die EZB-Verpflichtung, Zinsen für längere Zeiträume niedrig zu halten, was die Portfolioausgleichseffekte von QE verstärkt. Portfolioumschichtung tritt auf, wenn Investoren zwischen Vermögenswerten substituieren, wodurch Laufzeitprämien reduziert werden. Diese Kanäle funktionieren synergistisch: Signaling verstärkt Portfolioeffekte durch glaubwürdige Verpflichtung, während groß angelegte Käufe das Signaling validieren.",
          nl: "Het signaalkanaal communiceert de ECB's toewijding om rentes voor langere perioden laag te houden, wat de portfolio balans effecten van QE versterkt. Portfolio herbalancering treedt op wanneer investeerders substitueren tussen assets, waardoor termijnpremies verminderen. Deze kanalen werken synergetisch: signaling versterkt portfolio effecten door geloofwaardige toewijding te bieden, terwijl grootschalige aankopen de signaling valideren."
        }
      },
      {
        question: {
          en: "What role does the 'effective lower bound' concept play in modern monetary theory and ECB's unconventional policy design?",
          es: "¿Qué papel juega el concepto del 'límite inferior efectivo' en la teoría monetaria moderna y el diseño de política no convencional del BCE?",
          de: "Welche Rolle spielt das Konzept der 'effektiven Untergrenze' in der modernen Geldtheorie und dem unkonventionellen Politikdesign der EZB?",
          nl: "Welke rol speelt het 'effectieve ondergrens' concept in moderne monetaire theorie en de ECB's onconventionele beleidsontwerp?"
        },
        options: [
          { en: "ELB represents the practical limit where further rate cuts become ineffective, necessitating alternative tools like QE and forward guidance", es: "ELB representa el límite práctico donde más recortes de tasas se vuelven inefectivos, necesitando herramientas alternativas como QE y orientación prospectiva", de: "ELB repräsentiert die praktische Grenze, wo weitere Zinssenkungen ineffektiv werden, was alternative Instrumente wie QE und Forward Guidance erforderlich macht", nl: "ELB vertegenwoordigt de praktische grens waar verdere renteverlagingen ineffectief worden, wat alternatieve tools zoals QE en forward guidance noodzakelijk maakt" },
          { en: "ELB is always exactly zero and cannot be influenced by central bank policies", es: "ELB es siempre exactamente cero y no puede ser influenciado por políticas del banco central", de: "ELB ist immer genau null und kann nicht durch Zentralbankpolitiken beeinflusst werden", nl: "ELB is altijd precies nul en kan niet worden beïnvloed door centrale bank beleid" },
          { en: "ELB only applies to government bonds and has no relevance for private market rates", es: "ELB solo se aplica a bonos gubernamentales y no tiene relevancia para tasas de mercado privado", de: "ELB gilt nur für Staatsanleihen und hat keine Relevanz für private Marktzinsen", nl: "ELB geldt alleen voor staatsobligaties en heeft geen relevantie voor private marktrentes" },
          { en: "ELB makes conventional monetary policy more effective by concentrating transmission mechanisms", es: "ELB hace la política monetaria convencional más efectiva concentrando los mecanismos de transmisión", de: "ELB macht konventionelle Geldpolitik effektiver durch Konzentration der Übertragungsmechanismen", nl: "ELB maakt conventioneel monetair beleid effectiever door transmissiemechanismen te concentreren" }
        ],
        correct: 0,
        explanation: {
          en: "The effective lower bound (ELB) represents the practical limit for conventional monetary policy, which may be below zero but not infinitely negative due to cash conversion and financial system constraints. When approaching the ELB, central banks must rely on unconventional tools like quantitative easing, forward guidance, and negative rates with tiering to maintain policy effectiveness.",
          es: "El límite inferior efectivo (ELB) representa el límite práctico para la política monetaria convencional, que puede estar por debajo de cero pero no infinitamente negativo debido a la conversión de efectivo y restricciones del sistema financiero. Al acercarse al ELB, los bancos centrales deben depender de herramientas no convencionales como flexibilización cuantitativa, orientación prospectiva y tasas negativas con niveles para mantener la efectividad política.",
          de: "Die effektive Untergrenze (ELB) repräsentiert die praktische Grenze für konventionelle Geldpolitik, die unter null liegen kann, aber nicht unendlich negativ aufgrund von Bargeldkonversion und Finanzsystembeschränkungen. Beim Annähern an die ELB müssen Zentralbanken auf unkonventionelle Instrumente wie quantitative Lockerung, Forward Guidance und negative Zinsen mit Staffelung setzen, um Politikwirksamkeit zu erhalten.",
          nl: "De effectieve ondergrens (ELB) vertegenwoordigt de praktische grens voor conventioneel monetair beleid, die onder nul kan liggen maar niet oneindig negatief vanwege contantgeldconversie en financiële systeembeperkingen. Bij nadering van de ELB moeten centrale banken vertrouwen op onconventionele tools zoals kwantitatieve versoepeling, forward guidance en negatieve rentes met lagen om beleidseffectiviteit te behouden."
        }
      },
      {
        question: {
          en: "How does the concept of 'r-star' (natural rate of interest) influence ECB's assessment of monetary policy stance and neutral rate estimation?",
          es: "¿Cómo influye el concepto de 'r-star' (tasa natural de interés) en la evaluación del BCE de la postura de política monetaria y estimación de tasa neutral?",
          de: "Wie beeinflusst das Konzept von 'r-star' (natürlicher Zinssatz) die EZB-Bewertung der geldpolitischen Haltung und Neutralzinsschätzung?",
          nl: "Hoe beïnvloedt het concept van 'r-star' (natuurlijke rente) de ECB's beoordeling van monetaire beleidsstatus en neutrale rente schatting?"
        },
        options: [
          { en: "R-star represents the real interest rate consistent with full employment and stable inflation, serving as a benchmark for policy neutrality", es: "R-star representa la tasa de interés real consistente con pleno empleo e inflación estable, sirviendo como referencia para la neutralidad política", de: "R-star repräsentiert den realen Zinssatz, der mit Vollbeschäftigung und stabiler Inflation konsistent ist und als Maßstab für Politikneutralität dient", nl: "R-star vertegenwoordigt de reële rente consistent met volledige werkgelegenheid en stabiele inflatie, dienend als benchmark voor beleidsneutraliteit" },
          { en: "R-star is always fixed at 2% regardless of economic conditions or structural changes", es: "R-star siempre está fijado en 2% independientemente de las condiciones económicas o cambios estructurales", de: "R-star ist immer bei 2% fixiert unabhängig von wirtschaftlichen Bedingungen oder strukturellen Veränderungen", nl: "R-star is altijd vastgesteld op 2% ongeacht economische omstandigheden of structurele veranderingen" },
          { en: "R-star only applies to emerging market economies and has no relevance for developed economies", es: "R-star solo se aplica a economías de mercados emergentes y no tiene relevancia para economías desarrolladas", de: "R-star gilt nur für Schwellenländer und hat keine Relevanz für entwickelte Volkswirtschaften", nl: "R-star geldt alleen voor opkomende markteconomieën en heeft geen relevantie voor ontwikkelde economieën" },
          { en: "R-star can be precisely measured in real-time without any estimation uncertainty", es: "R-star puede ser medido precisamente en tiempo real sin incertidumbre de estimación", de: "R-star kann in Echtzeit präzise gemessen werden ohne Schätzunsicherheit", nl: "R-star kan precies in real-time gemeten worden zonder schattingsonzekerheid" }
        ],
        correct: 0,
        explanation: {
          en: "R-star (r*) is the natural or neutral real interest rate that would prevail when the economy is at full employment and inflation is stable. It serves as a key benchmark for assessing whether monetary policy is accommodative, neutral, or restrictive. The ECB uses various models to estimate r-star, though it's unobservable and subject to significant uncertainty, particularly given structural changes affecting productivity and demographics.",
          es: "R-star (r*) es la tasa de interés real natural o neutral que prevalecería cuando la economía está en pleno empleo y la inflación es estable. Sirve como referencia clave para evaluar si la política monetaria es acomodaticia, neutral o restrictiva. El BCE usa varios modelos para estimar r-star, aunque es inobservable y sujeto a incertidumbre significativa, particularmente dados los cambios estructurales que afectan la productividad y demografía.",
          de: "R-star (r*) ist der natürliche oder neutrale Realzinssatz, der herrschen würde, wenn die Wirtschaft bei Vollbeschäftigung ist und die Inflation stabil ist. Er dient als wichtiger Maßstab zur Bewertung, ob Geldpolitik akkommodierend, neutral oder restriktiv ist. Die EZB verwendet verschiedene Modelle zur Schätzung von r-star, obwohl es unbeobachtbar und erheblicher Unsicherheit unterworfen ist, besonders angesichts struktureller Veränderungen bei Produktivität und Demografie.",
          nl: "R-star (r*) is de natuurlijke of neutrale reële rente die zou heersen wanneer de economie op volledige werkgelegenheid is en inflatie stabiel is. Het dient als belangrijke benchmark voor het beoordelen of monetair beleid accommoderend, neutraal of restrictief is. De ECB gebruikt verschillende modellen om r-star te schatten, hoewel het onobserveerbaar is en onderhevig aan significante onzekerheid, vooral gezien structurele veranderingen die productiviteit en demografie beïnvloeden."
        }
      },
      {
        question: {
          en: "What is the theoretical foundation of the 'debt deflation' mechanism in Irving Fisher's framework and its relevance to ECB crisis response policies?",
          es: "¿Cuál es el fundamento teórico del mecanismo de 'deflación de deuda' en el marco de Irving Fisher y su relevancia para las políticas de respuesta a crisis del BCE?",
          de: "Was ist die theoretische Grundlage des 'Schuldendeflations'-Mechanismus in Irving Fishers Rahmen und seine Relevanz für EZB-Krisenreaktionspolitiken?",
          nl: "Wat is de theoretische basis van het 'schuldendeflatie' mechanisme in Irving Fisher's raamwerk en de relevantie voor ECB crisisrespons beleid?"
        },
        options: [
          { en: "Deflation increases real debt burdens, forcing deleveraging that further depresses prices in a vicious cycle requiring aggressive monetary intervention", es: "La deflación aumenta las cargas de deuda reales, forzando desapalancamiento que deprime aún más los precios en un ciclo vicioso que requiere intervención monetaria agresiva", de: "Deflation erhöht reale Schuldenlasten, was Entschuldung erzwingt, die Preise weiter drückt in einem Teufelskreis, der aggressive geldpolitische Intervention erfordert", nl: "Deflatie verhoogt reële schuldlasten, wat deleveraging forceert die prijzen verder drukt in een vicieuze cirkel die agressieve monetaire interventie vereist" },
          { en: "Debt deflation only affects government debt and has no impact on private sector balance sheets", es: "La deflación de deuda solo afecta la deuda gubernamental y no tiene impacto en los balances del sector privado", de: "Schuldendeflation betrifft nur Staatsschulden und hat keinen Einfluss auf private Bilanzen", nl: "Schuldendeflatie beïnvloedt alleen overheidsschuld en heeft geen impact op private sector balansen" },
          { en: "Deflation automatically reduces debt burdens and stimulates economic recovery without intervention", es: "La deflación automáticamente reduce las cargas de deuda y estimula la recuperación económica sin intervención", de: "Deflation reduziert automatisch Schuldenlasten und stimuliert wirtschaftliche Erholung ohne Intervention", nl: "Deflatie vermindert automatisch schuldlasten en stimuleert economisch herstel zonder interventie" },
          { en: "Debt deflation mechanism only operates during hyperinflation periods", es: "El mecanismo de deflación de deuda solo opera durante períodos de hiperinflación", de: "Schuldendeflationsmechanismus funktioniert nur während Hyperinflationsperioden", nl: "Schuldendeflatie mechanisme werkt alleen tijdens hyperinflatie perioden" }
        ],
        correct: 0,
        explanation: {
          en: "Fisher's debt deflation theory explains how falling prices increase the real burden of nominal debt, forcing debtors to sell assets and reduce spending, which further depresses prices and economic activity. This creates a vicious cycle that can lead to deep recessions. The ECB's aggressive monetary policies during crises aim to prevent such deflationary spirals through QE, negative rates, and forward guidance.",
          es: "La teoría de deflación de deuda de Fisher explica cómo la caída de precios aumenta la carga real de la deuda nominal, forzando a los deudores a vender activos y reducir el gasto, lo que deprime aún más los precios y la actividad económica. Esto crea un ciclo vicioso que puede llevar a recesiones profundas. Las políticas monetarias agresivas del BCE durante las crisis apuntan a prevenir tales espirales deflacionarias a través de QE, tasas negativas y orientación prospectiva.",
          de: "Fishers Schuldendeflationstheorie erklärt, wie fallende Preise die reale Belastung nominaler Schulden erhöhen, was Schuldner zwingt, Vermögenswerte zu verkaufen und Ausgaben zu reduzieren, was Preise und Wirtschaftsaktivität weiter drückt. Dies schafft einen Teufelskreis, der zu tiefen Rezessionen führen kann. Die EZBs aggressive geldpolitische Maßnahmen während Krisen zielen darauf ab, solche Deflationsspiralen durch QE, negative Zinsen und Forward Guidance zu verhindern.",
          nl: "Fisher's schuldendeflatie theorie verklaart hoe dalende prijzen de reële last van nominale schuld verhogen, waardoor debiteuren gedwongen worden assets te verkopen en uitgaven te verminderen, wat prijzen en economische activiteit verder drukt. Dit creëert een vicieuze cirkel die tot diepe recessies kan leiden. De ECB's agressieve monetaire beleid tijdens crises beoogt dergelijke deflatoire spiralen te voorkomen door QE, negatieve rentes en forward guidance."
        }
      },
      {
        question: {
          en: "How does the 'time inconsistency problem' in monetary policy relate to the ECB's institutional design and credibility framework?",
          es: "¿Cómo se relaciona el 'problema de inconsistencia temporal' en la política monetaria con el diseño institucional del BCE y el marco de credibilidad?",
          de: "Wie verhält sich das 'Zeitinkonsistenzproblem' in der Geldpolitik zum institutionellen Design der EZB und Glaubwürdigkeitsrahmen?",
          nl: "Hoe verhoudt het 'tijdsinconsistentie probleem' in monetair beleid zich tot de ECB's institutionele ontwerp en geloofwaardigheidsraamwerk?"
        },
        options: [
          { en: "Central bank independence and institutional commitment mechanisms help solve time inconsistency by preventing short-term political pressure from undermining long-term credibility", es: "La independencia del banco central y los mecanismos de compromiso institucional ayudan a resolver la inconsistencia temporal previniendo que la presión política a corto plazo socave la credibilidad a largo plazo", de: "Zentralbankautonomie und institutionelle Bindungsmechanismen helfen, Zeitinkonsistenz zu lösen, indem sie verhindern, dass kurzfristiger politischer Druck langfristige Glaubwürdigkeit untergräbt", nl: "Centrale bank onafhankelijkheid en institutionele toewijdingsmechanismen helpen tijdsinconsistentie op te lossen door te voorkomen dat korte termijn politieke druk lange termijn geloofwaardigheid ondermijnt" },
          { en: "Time inconsistency problems are automatically solved by democratic oversight of monetary policy decisions", es: "Los problemas de inconsistencia temporal se resuelven automáticamente por la supervisión democrática de las decisiones de política monetaria", de: "Zeitinkonsistenzprobleme werden automatisch durch demokratische Überwachung geldpolitischer Entscheidungen gelöst", nl: "Tijdsinconsistentie problemen worden automatisch opgelost door democratische oversight van monetaire beleidsbeslissingen" },
          { en: "The ECB's mandate flexibility allows it to ignore time inconsistency considerations entirely", es: "La flexibilidad del mandato del BCE le permite ignorar completamente las consideraciones de inconsistencia temporal", de: "Die EZB-Mandatsflexibilität erlaubt es, Zeitinkonsistenzüberlegungen völlig zu ignorieren", nl: "De ECB's mandaat flexibiliteit staat toe om tijdsinconsistentie overwegingen volledig te negeren" },
          { en: "Time inconsistency only affects fiscal policy and has no relevance for monetary authorities", es: "La inconsistencia temporal solo afecta la política fiscal y no tiene relevancia para las autoridades monetarias", de: "Zeitinkonsistenz betrifft nur Fiskalpolitik und hat keine Relevanz für Geldautoritäten", nl: "Tijdsinconsistentie beïnvloedt alleen fiscaal beleid en heeft geen relevantie voor monetaire autoriteiten" }
        ],
        correct: 0,
        explanation: {
          en: "The time inconsistency problem arises when policymakers have incentives to deviate from previously announced optimal policies, undermining credibility. The ECB's institutional independence, clear mandate, and transparent framework are designed to solve this problem by creating credible commitment to price stability, preventing the temptation to exploit short-term Phillips curve trade-offs that would ultimately prove counterproductive.",
          es: "El problema de inconsistencia temporal surge cuando los responsables de políticas tienen incentivos para desviarse de las políticas óptimas previamente anunciadas, socavando la credibilidad. La independencia institucional del BCE, mandato claro y marco transparente están diseñados para resolver este problema creando compromiso creíble con la estabilidad de precios, previniendo la tentación de explotar compensaciones de curva de Phillips a corto plazo que finalmente resultarían contraproducentes.",
          de: "Das Zeitinkonsistenzproblem entsteht, wenn Politikgestalter Anreize haben, von zuvor angekündigten optimalen Politiken abzuweichen, was Glaubwürdigkeit untergräbt. Die EZBs institutionelle Unabhängigkeit, klares Mandat und transparenter Rahmen sind darauf ausgelegt, dieses Problem durch glaubwürdige Bindung an Preisstabilität zu lösen, um die Versuchung zu verhindern, kurzfristige Phillips-Kurven-Trade-offs zu nutzen, die sich letztendlich als kontraproduktiv erweisen würden.",
          nl: "Het tijdsinconsistentie probleem ontstaat wanneer beleidsmakers prikkels hebben om af te wijken van eerder aangekondigde optimale beleidsmaatregelen, wat geloofwaardigheid ondermijnt. De ECB's institutionele onafhankelijkheid, duidelijk mandaat en transparant raamwerk zijn ontworpen om dit probleem op te lossen door geloofwaardige toewijding aan prijsstabiliteit te creëren, waardoor de verleiding wordt voorkomen om korte termijn Phillips curve trade-offs te exploiteren die uiteindelijk contraproductief zouden blijken."
        }
      },
      {
        question: {
          en: "What is the significance of the 'New Keynesian Phillips Curve' in understanding ECB's inflation dynamics and monetary transmission mechanisms?",
          es: "¿Cuál es la significancia de la 'Curva de Phillips Neokeynesiana' en entender las dinámicas de inflación del BCE y los mecanismos de transmisión monetaria?",
          de: "Was ist die Bedeutung der 'Neukeynesianischen Phillips-Kurve' für das Verständnis der EZB-Inflationsdynamik und geldpolitischen Übertragungsmechanismen?",
          nl: "Wat is de betekenis van de 'New Keynesiaanse Phillips Curve' in het begrijpen van ECB's inflatie dynamiek en monetaire transmissiemechanismen?"
        },
        options: [
          { en: "Forward-looking expectations and price stickiness create inflation persistence, making gradual policy adjustments optimal for achieving price stability", es: "Las expectativas prospectivas y la rigidez de precios crean persistencia de inflación, haciendo óptimos los ajustes graduales de política para lograr estabilidad de precios", de: "Vorausschauende Erwartungen und Preisrigidität schaffen Inflationspersistenz, wodurch graduelle Politikanpassungen optimal für Preisstabilität werden", nl: "Vooruitkijkende verwachtingen en prijsrigiditeit creëren inflatie persistentie, waardoor geleidelijke beleidsaanpassingen optimaal worden voor prijsstabiliteit" },
          { en: "The Phillips Curve is perfectly vertical at all times, making monetary policy completely ineffective", es: "La Curva de Phillips es perfectamente vertical en todo momento, haciendo la política monetaria completamente inefectiva", de: "Die Phillips-Kurve ist jederzeit perfekt vertikal, wodurch Geldpolitik völlig ineffektiv wird", nl: "De Phillips Curve is te allen tijde perfect verticaal, waardoor monetair beleid volledig ineffectief wordt" },
          { en: "Inflation depends only on past inflation without any role for expectations or economic slack", es: "La inflación depende solo de la inflación pasada sin ningún papel para las expectativas o la holgura económica", de: "Inflation hängt nur von vergangener Inflation ab ohne Rolle für Erwartungen oder wirtschaftlichen Spielraum", nl: "Inflatie hangt alleen af van verleden inflatie zonder enige rol voor verwachtingen of economische speelruimte" },
          { en: "The curve implies that inflation can be permanently reduced without any output costs", es: "La curva implica que la inflación puede ser reducida permanentemente sin costos de producto", de: "Die Kurve impliziert, dass Inflation dauerhaft ohne Produktionskosten reduziert werden kann", nl: "De curve impliceert dat inflatie permanent kan worden verminderd zonder enige output kosten" }
        ],
        correct: 0,
        explanation: {
          en: "The New Keynesian Phillips Curve incorporates forward-looking inflation expectations and sticky prices, showing that current inflation depends on expected future inflation and the output gap. This framework justifies the ECB's gradual approach and emphasis on anchoring expectations, as well as explaining why monetary policy has persistent real effects through the expectation channel and price adjustment frictions.",
          es: "La Curva de Phillips Neokeynesiana incorpora expectativas de inflación prospectivas y precios rígidos, mostrando que la inflación actual depende de la inflación futura esperada y la brecha del producto. Este marco justifica el enfoque gradual del BCE y el énfasis en anclar expectativas, así como explicar por qué la política monetaria tiene efectos reales persistentes a través del canal de expectativas y fricciones de ajuste de precios.",
          de: "Die Neukeynesianische Phillips-Kurve integriert vorausschauende Inflationserwartungen und klebrige Preise, zeigend dass aktuelle Inflation von erwarteter zukünftiger Inflation und der Produktionslücke abhängt. Dieser Rahmen rechtfertigt die EZBs graduellen Ansatz und Betonung der Erwartungsverankerung, sowie die Erklärung, warum Geldpolitik persistente reale Effekte durch den Erwartungskanal und Preisanpassungsfriktionen hat.",
          nl: "De New Keynesiaanse Phillips Curve incorporeert vooruitkijkende inflatie verwachtingen en kleverige prijzen, tonend dat huidige inflatie afhangt van verwachte toekomstige inflatie en de output gap. Dit raamwerk rechtvaardigt de ECB's geleidelijke benadering en nadruk op het verankeren van verwachtingen, evenals het verklaren waarom monetair beleid persistente reële effecten heeft door het verwachtingskanaal en prijsaanpassingsfricties."
        }
      },
      {
        question: {
          en: "How does the concept of 'financial accelerator' in Bernanke-Gertler-Gilchrist models inform ECB's understanding of credit cycles and macroprudential policy?",
          es: "¿Cómo informa el concepto de 'acelerador financiero' en los modelos de Bernanke-Gertler-Gilchrist el entendimiento del BCE de los ciclos de crédito y la política macroprudencial?",
          de: "Wie informiert das Konzept des 'finanziellen Beschleunigers' in Bernanke-Gertler-Gilchrist-Modellen das EZB-Verständnis von Kreditzyklen und makroprudenzieller Politik?",
          nl: "Hoe informeert het concept van 'financiële versneller' in Bernanke-Gertler-Gilchrist modellen de ECB's begrip van kredietcycli en macroprudentieel beleid?"
        },
        options: [
          { en: "External finance premiums amplify business cycle fluctuations through endogenous changes in borrowing costs based on net worth", es: "Las primas de financiamiento externo amplifican las fluctuaciones del ciclo económico a través de cambios endógenos en los costos de endeudamiento basados en el patrimonio neto", de: "Externe Finanzierungsprämien verstärken Konjunkturschwankungen durch endogene Änderungen der Kreditkosten basierend auf dem Nettovermögen", nl: "Externe financieringspremies versterken conjunctuurschommelingen door endogene veranderingen in leenkosten gebaseerd op netto vermogen" },
          { en: "Financial markets are always perfectly efficient and never amplify economic shocks", es: "Los mercados financieros son siempre perfectamente eficientes y nunca amplifican los choques económicos", de: "Finanzmärkte sind immer perfekt effizient und verstärken niemals wirtschaftliche Schocks", nl: "Financiële markten zijn altijd perfect efficiënt en versterken nooit economische schokken" },
          { en: "Credit cycles are completely independent of monetary policy and central bank actions", es: "Los ciclos de crédito son completamente independientes de la política monetaria y las acciones del banco central", de: "Kreditzyklen sind völlig unabhängig von Geldpolitik und Zentralbankmaßnahmen", nl: "Kredietcycli zijn volledig onafhankelijk van monetair beleid en centrale bank acties" },
          { en: "Financial accelerator effects only operate during periods of financial innovation", es: "Los efectos del acelerador financiero solo operan durante períodos de innovación financiera", de: "Finanzielle Beschleunigereffekte funktionieren nur während Perioden finanzieller Innovation", nl: "Financiële versneller effecten werken alleen tijdens perioden van financiële innovatie" }
        ],
        correct: 0,
        explanation: {
          en: "The financial accelerator mechanism shows how borrower net worth affects external finance premiums, creating feedback loops that amplify business cycles. When net worth falls, borrowing becomes more expensive, reducing investment and further depressing asset values and net worth. This informs ECB's macroprudential approach by highlighting how financial frictions can amplify monetary policy transmission and create systemic risks.",
          es: "El mecanismo del acelerador financiero muestra cómo el patrimonio neto del prestatario afecta las primas de financiamiento externo, creando bucles de retroalimentación que amplifican los ciclos económicos. Cuando el patrimonio neto cae, el endeudamiento se vuelve más caro, reduciendo la inversión y deprimiendo aún más los valores de activos y el patrimonio neto. Esto informa el enfoque macroprudencial del BCE resaltando cómo las fricciones financieras pueden amplificar la transmisión de política monetaria y crear riesgos sistémicos.",
          de: "Der finanzielle Beschleunigermechanismus zeigt, wie das Nettovermögen der Kreditnehmer externe Finanzierungsprämien beeinflusst und Rückkopplungsschleifen schafft, die Konjunkturzyklen verstärken. Wenn das Nettovermögen fällt, wird Kreditaufnahme teurer, was Investitionen reduziert und Vermögenswerte und Nettovermögen weiter drückt. Dies informiert die EZBs makroprudenzielle Herangehensweise durch Hervorhebung, wie Finanzfriktionen geldpolitische Übertragung verstärken und systemische Risiken schaffen können.",
          nl: "Het financiële versneller mechanisme toont hoe lener netto vermogen externe financieringspremies beïnvloedt, waardoor feedback loops ontstaan die conjunctuurcycli versterken. Wanneer netto vermogen daalt, wordt lenen duurder, wat investeringen vermindert en activawaarden en netto vermogen verder drukt. Dit informeert de ECB's macroprudentiële benadering door te benadrukken hoe financiële fricties monetaire beleidstransmissie kunnen versterken en systeemrisico's kunnen creëren."
        }
      },
      {
        question: {
          en: "What is the theoretical significance of the 'Lucas critique' in evaluating ECB's econometric models and policy rule design?",
          es: "¿Cuál es la significancia teórica de la 'crítica de Lucas' en evaluar los modelos econométricos del BCE y el diseño de reglas de política?",
          de: "Was ist die theoretische Bedeutung der 'Lucas-Kritik' bei der Bewertung der ökonometrischen Modelle der EZB und dem Politikregel-Design?",
          nl: "Wat is de theoretische betekenis van de 'Lucas kritiek' in het evalueren van ECB's econometrische modellen en beleidsregel ontwerp?"
        },
        options: [
          { en: "Policy changes alter private sector expectations and behavior, making historical relationships unreliable for policy evaluation", es: "Los cambios de política alteran las expectativas y comportamiento del sector privado, haciendo las relaciones históricas no confiables para la evaluación de políticas", de: "Politikänderungen verändern private Erwartungen und Verhalten, wodurch historische Beziehungen für Politikbewertung unzuverlässig werden", nl: "Beleidsveranderingen veranderen private sector verwachtingen en gedrag, waardoor historische relaties onbetrouwbaar worden voor beleidsevaluatie" },
          { en: "Historical econometric relationships remain stable regardless of policy regime changes", es: "Las relaciones econométricas históricas permanecen estables independientemente de los cambios de régimen de política", de: "Historische ökonometrische Beziehungen bleiben stabil unabhängig von Politikregimewechseln", nl: "Historische econometrische relaties blijven stabiel ongeacht beleidsregime veranderingen" },
          { en: "The critique only applies to fiscal policy and has no relevance for monetary policy analysis", es: "La crítica solo se aplica a la política fiscal y no tiene relevancia para el análisis de política monetaria", de: "Die Kritik gilt nur für Fiskalpolitik und hat keine Relevanz für geldpolitische Analyse", nl: "De kritiek geldt alleen voor fiscaal beleid en heeft geen relevantie voor monetaire beleidsanalyse" },
          { en: "Econometric models become more accurate when policy rules change frequently", es: "Los modelos econométricos se vuelven más precisos cuando las reglas de política cambian frecuentemente", de: "Ökonometrische Modelle werden genauer, wenn sich Politikregeln häufig ändern", nl: "Econometrische modellen worden nauwkeuriger wanneer beleidsregels frequent veranderen" }
        ],
        correct: 0,
        explanation: {
          en: "The Lucas critique argues that econometric relationships estimated under one policy regime may not hold under different regimes because rational agents adjust their behavior when policies change. This has profound implications for ECB modeling, requiring structural approaches that account for expectation formation and policy invariant parameters rather than relying solely on reduced-form historical relationships.",
          es: "La crítica de Lucas argumenta que las relaciones econométricas estimadas bajo un régimen de política pueden no mantenerse bajo regímenes diferentes porque los agentes racionales ajustan su comportamiento cuando las políticas cambian. Esto tiene implicaciones profundas para el modelado del BCE, requiriendo enfoques estructurales que consideren la formación de expectativas y parámetros invariantes de política en lugar de depender solo de relaciones históricas de forma reducida.",
          de: "Die Lucas-Kritik argumentiert, dass ökonometrische Beziehungen, die unter einem Politikregime geschätzt wurden, möglicherweise nicht unter verschiedenen Regimen gelten, weil rationale Akteure ihr Verhalten anpassen, wenn sich Politiken ändern. Dies hat tiefgreifende Implikationen für EZB-Modellierung, die strukturelle Ansätze erfordert, die Erwartungsbildung und politikinvariante Parameter berücksichtigen, anstatt sich nur auf reduzierte historische Beziehungen zu verlassen.",
          nl: "De Lucas kritiek stelt dat econometrische relaties geschat onder één beleidsregime mogelijk niet gelden onder verschillende regimes omdat rationele agenten hun gedrag aanpassen wanneer beleid verandert. Dit heeft diepgaande implicaties voor ECB modellering, wat structurele benaderingen vereist die verwachtingsvorming en beleidsinvariante parameters verantwoorden in plaats van alleen te vertrouwen op gereduceerde historische relaties."
        }
      },
      {
        question: {
          en: "What is the precise legal basis for ECB independence as enshrined in Article 130 TFEU and how does it differ from other central bank independence frameworks?",
          es: "¿Cuál es la base legal precisa para la independencia del BCE consagrada en el Artículo 130 TFEU y cómo difiere de otros marcos de independencia de bancos centrales?",
          de: "Was ist die präzise rechtliche Grundlage für EZB-Unabhängigkeit, wie sie in Artikel 130 AEUV verankert ist, und wie unterscheidet sie sich von anderen Zentralbankunabhängigkeits-Rahmenwerken?",
          nl: "Wat is de precieze juridische basis voor ECB-onafhankelijkheid zoals vastgelegd in Artikel 130 VWEU en hoe verschilt het van andere centrale bank onafhankelijkheidskaders?"
        },
        options: [
          { en: "Institutional independence prohibiting instructions from any government or EU institution, with personal independence through fixed terms and functional independence over monetary policy", es: "Independencia institucional prohibiendo instrucciones de cualquier gobierno o institución de la UE, con independencia personal a través de términos fijos e independencia funcional sobre política monetaria", de: "Institutionelle Unabhängigkeit, die Anweisungen von jeder Regierung oder EU-Institution verbietet, mit persönlicher Unabhängigkeit durch feste Amtszeiten und funktionaler Unabhängigkeit über Geldpolitik", nl: "Institutionele onafhankelijkheid die instructies van elke regering of EU-instelling verbiedt, met persoonlijke onafhankelijkheid door vaste termijnen en functionele onafhankelijkheid over monetair beleid" },
          { en: "Only operational independence with government oversight", es: "Solo independencia operacional con supervisión gubernamental", de: "Nur operative Unabhängigkeit mit staatlicher Aufsicht", nl: "Alleen operationele onafhankelijkheid met overheidstoezicht" },
          { en: "Independence subject to European Parliament approval", es: "Independencia sujeta a aprobación del Parlamento Europeo", de: "Unabhängigkeit vorbehaltlich der Zustimmung des Europäischen Parlaments", nl: "Onafhankelijkheid onderworpen aan goedkeuring van Europees Parlement" },
          { en: "Temporary independence renewable every five years", es: "Independencia temporal renovable cada cinco años", de: "Zeitliche Unabhängigkeit alle fünf Jahre erneuerbar", nl: "Tijdelijke onafhankelijkheid hernieuwbaar elke vijf jaar" }
        ],
        correct: 0,
        explanation: {
          en: "Article 130 TFEU establishes the most comprehensive central bank independence framework globally, prohibiting the ECB and national central banks from seeking or taking instructions from any EU institution, government, or other body. This goes beyond operational independence to include institutional independence (no external interference), personal independence (fixed 8-year non-renewable terms for Executive Board), and functional independence (exclusive competence over monetary policy), creating stronger protection than many other central banks enjoy.",
          es: "El Artículo 130 TFEU establece el marco de independencia de banco central más integral globalmente, prohibiendo al BCE y bancos centrales nacionales buscar o tomar instrucciones de cualquier institución de la UE, gobierno u otro organismo. Esto va más allá de independencia operacional para incluir independencia institucional (sin interferencia externa), independencia personal (términos fijos de 8 años no renovables para Comité Ejecutivo), e independencia funcional (competencia exclusiva sobre política monetaria), creando protección más fuerte que muchos otros bancos centrales disfrutan.",
          de: "Artikel 130 AEUV etabliert das umfassendste Zentralbankunabhängigkeits-Rahmenwerk global, das der EZB und nationalen Zentralbanken verbietet, Anweisungen von jeder EU-Institution, Regierung oder anderen Körperschaft zu suchen oder anzunehmen. Dies geht über operative Unabhängigkeit hinaus und umfasst institutionelle Unabhängigkeit (keine externe Einmischung), persönliche Unabhängigkeit (feste 8-jährige nicht erneuerbare Amtszeiten für Vorstand), und funktionale Unabhängigkeit (ausschließliche Kompetenz über Geldpolitik), wodurch stärkerer Schutz geschaffen wird als viele andere Zentralbanken genießen.",
          nl: "Artikel 130 VWEU vestigt het meest uitgebreide centrale bank onafhankelijkheidskader wereldwijd, dat de ECB en nationale centrale banken verbiedt instructies te zoeken of aan te nemen van elke EU-instelling, regering of ander orgaan. Dit gaat verder dan operationele onafhankelijkheid om institutionele onafhankelijkheid (geen externe inmenging), persoonlijke onafhankelijkheid (vaste 8-jarige niet-hernieuwbare termijnen voor Directie), en functionele onafhankelijkheid (exclusieve competentie over monetair beleid) te omvatten, waardoor sterkere bescherming wordt gecreëerd dan veel andere centrale banken genieten."
        }
      },
      {
        question: {
          en: "How does the constitutional principle of proportionality under EU law apply to ECB monetary policy measures, particularly following the German Constitutional Court's PSPP ruling?",
          es: "¿Cómo se aplica el principio constitucional de proporcionalidad bajo la ley de la UE a las medidas de política monetaria del BCE, particularmente siguiendo la sentencia PSPP del Tribunal Constitucional alemán?",
          de: "Wie gilt das verfassungsrechtliche Verhältnismäßigkeitsprinzip unter EU-Recht für EZB-Geldpolitikmaßnahmen, insbesondere nach dem PSPP-Urteil des deutschen Bundesverfassungsgerichts?",
          nl: "Hoe past het constitutionele proportionaliteitsbeginsel onder EU-recht toe op ECB-monetaire beleidsmaatregelen, met name na de PSPP-uitspraak van het Duitse Constitutionele Hof?"
        },
        options: [
          { en: "ECB must demonstrate measures are suitable, necessary, and proportionate to achieve price stability objectives, balancing monetary goals against potential economic and social side effects", es: "El BCE debe demostrar que las medidas son adecuadas, necesarias y proporcionales para lograr objetivos de estabilidad de precios, equilibrando metas monetarias contra potenciales efectos secundarios económicos y sociales", de: "EZB muss demonstrieren, dass Maßnahmen geeignet, notwendig und verhältnismäßig sind, um Preisstabilitätsziele zu erreichen, und monetäre Ziele gegen potenzielle wirtschaftliche und soziale Nebenwirkungen abwägen", nl: "ECB moet aantonen dat maatregelen geschikt, noodzakelijk en proportioneel zijn om prijsstabiliteitsdoelstellingen te bereiken, waarbij monetaire doelen worden afgewogen tegen potentiële economische en sociale bijwerkingen" },
          { en: "Proportionality only applies to fiscal policy measures", es: "La proporcionalidad solo se aplica a medidas de política fiscal", de: "Verhältnismäßigkeit gilt nur für fiskalpolitische Maßnahmen", nl: "Proportionaliteit geldt alleen voor fiscale beleidsmaatregelen" },
          { en: "ECB actions are exempt from proportionality review", es: "Las acciones del BCE están exentas de revisión de proporcionalidad", de: "EZB-Maßnahmen sind von Verhältnismäßigkeitsprüfung ausgenommen", nl: "ECB-acties zijn vrijgesteld van proportionaliteitstoetsing" },
          { en: "Proportionality requires unanimous member state approval", es: "La proporcionalidad requiere aprobación unánime de estados miembros", de: "Verhältnismäßigkeit erfordert einstimmige Zustimmung der Mitgliedstaaten", nl: "Proportionaliteit vereist unanieme goedkeuring van lidstaten" }
        ],
        correct: 0,
        explanation: {
          en: "The proportionality principle requires ECB monetary policy measures to be suitable (apt to achieve objectives), necessary (no less restrictive alternative available), and proportionate in the narrow sense (benefits outweigh costs and side effects). The German Constitutional Court's 2020 PSPP ruling challenged the ECB and CJEU to provide clearer proportionality assessments, leading to enhanced ECB communication about weighing monetary benefits against potential distributional, financial stability, and fiscal effects of its policies.",
          es: "El principio de proporcionalidad requiere que las medidas de política monetaria del BCE sean adecuadas (aptas para lograr objetivos), necesarias (sin alternativa menos restrictiva disponible), y proporcionales en sentido estricto (beneficios superan costos y efectos secundarios). La sentencia PSPP 2020 del Tribunal Constitucional alemán desafió al BCE y TJUE a proporcionar evaluaciones de proporcionalidad más claras, llevando a comunicación mejorada del BCE sobre sopesar beneficios monetarios contra potenciales efectos distributivos, de estabilidad financiera y fiscales de sus políticas.",
          de: "Das Verhältnismäßigkeitsprinzip erfordert, dass EZB-Geldpolitikmaßnahmen geeignet (geeignet zur Zielerreichung), notwendig (keine weniger restriktive Alternative verfügbar) und verhältnismäßig im engeren Sinne (Vorteile überwiegen Kosten und Nebenwirkungen) sind. Das PSPP-Urteil 2020 des deutschen Bundesverfassungsgerichts forderte EZB und EuGH auf, klarere Verhältnismäßigkeitsbewertungen zu liefern, was zu verbesserter EZB-Kommunikation über das Abwägen monetärer Vorteile gegen potenzielle Verteilungs-, Finanzstabilitäts- und fiskalische Effekte ihrer Politiken führte.",
          nl: "Het proportionaliteitsbeginsel vereist dat ECB-monetaire beleidsmaatregelen geschikt zijn (geschikt om doelstellingen te bereiken), noodzakelijk (geen minder restrictief alternatief beschikbaar), en proportioneel in enge zin (voordelen wegen op tegen kosten en bijwerkingen). De PSPP-uitspraak 2020 van het Duitse Constitutionele Hof daagde de ECB en het HvJ uit om duidelijkere proportionaliteitsbeoordelingen te verstrekken, wat leidde tot verbeterde ECB-communicatie over het afwegen van monetaire voordelen tegen potentiële distributieve, financiële stabiliteits- en fiscale effecten van haar beleid."
        }
      }
    ]
  };

  // Export for use in the quiz application
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = level10;
  } else if (typeof window !== 'undefined') {
    window.level10 = level10;
  }
})();
