(function() {
    const level1Questions = [
        {
            question: {
                en: "When were aerodynamic wings first introduced to Formula 1?",
                es: "¿Cuándo se introdujeron por primera vez las alas aerodinámicas en la Fórmula 1?",
                de: "Wann wurden aerodynamische Flügel erstmals in der Formel 1 eingeführt?",
                nl: "Wanneer werden aerodynamische vleugels voor het eerst geïntroduceerd in Formule 1?"
            },
            options: ["1950s", "1960s", "1970s", "1980s"],
            correct: 1,
            explanation: {
                en: "Wings were first introduced in the late 1960s (1968) to increase downforce.",
                es: "Las alas se introdujeron por primera vez a finales de los años 60 (1968) para aumentar la carga aerodinámica.",
                de: "Flügel wurden erstmals Ende der 1960er Jahre (1968) eingeführt, um den Abtrieb zu erhöhen.",
                nl: "Vleugels werden voor het eerst eind jaren 60 (1968) geïntroduceerd om de neerwaartse druk te verhogen."
            }
        },
        {
            question: {
                en: "What are slick tires in Formula 1?",
                es: "¿Qué son los neumáticos lisos en la Fórmula 1?",
                de: "Was sind Slick-Reifen in der Formel 1?",
                nl: "Wat zijn slicks in Formule 1?"
            },
            options: ["Tires with deep grooves", "Tires without treads", "Winter tires", "All-weather tires"],
            correct: 1,
            explanation: {
                en: "Slick tires have no treads, providing maximum contact with the track in dry conditions.",
                es: "Los neumáticos lisos no tienen dibujo, proporcionando el máximo contacto con la pista en condiciones secas.",
                de: "Slick-Reifen haben kein Profil und bieten maximalen Kontakt zur Strecke bei trockenen Bedingungen.",
                nl: "Slicks hebben geen profiel en bieden maximaal contact met het circuit onder droge omstandigheden."
            }
        },
        {
            question: {
                en: "When were turbocharged engines first used in Formula 1?",
                es: "¿Cuándo se usaron por primera vez los motores turboalimentados en la Fórmula 1?",
                de: "Wann wurden Turbomotoren erstmals in der Formel 1 eingesetzt?",
                nl: "Wanneer werden turbomotoren voor het eerst gebruikt in Formule 1?"
            },
            options: ["1960s", "1970s", "1980s", "1990s"],
            correct: 1,
            explanation: {
                en: "Turbocharged engines were first introduced in 1977 by Renault, revolutionizing F1 power.",
                es: "Los motores turboalimentados se introdujeron por primera vez en 1977 por Renault, revolucionando la potencia en F1.",
                de: "Turbomotoren wurden erstmals 1977 von Renault eingeführt und revolutionierten die F1-Leistung.",
                nl: "Turbomotoren werden in 1977 door Renault geïntroduceerd, wat de F1-kracht revolutioneerde."
            }
        },
        {
            question: {
                en: "What is the ground effect in Formula 1?",
                es: "¿Qué es el efecto suelo en la Fórmula 1?",
                de: "Was ist der Bodeneffekt in der Formel 1?",
                nl: "Wat is het grondeffect in Formule 1?"
            },
            options: ["Effect of tire grip", "Downforce generated by underbody airflow", "Engine power on straights", "Braking efficiency"],
            correct: 1,
            explanation: {
                en: "Ground effect uses underbody airflow to create a low-pressure area that sucks the car to the track.",
                es: "El efecto suelo utiliza el flujo de aire bajo el coche para crear una zona de baja presión que succiona el coche a la pista.",
                de: "Der Bodeneffekt nutzt die Unterbodenströmung, um einen Unterdruck zu erzeugen, der das Auto auf die Strecke saugt.",
                nl: "Het grondeffect gebruikt luchtstroom onder de auto om een lagedrukgebied te creëren dat de auto naar het circuit zuigt."
            }
        },
        {
            question: {
                en: "What does DRS stand for in Formula 1?",
                es: "¿Qué significa DRS en la Fórmula 1?",
                de: "Wofür steht DRS in der Formel 1?",
                nl: "Waar staat DRS voor in Formule 1?"
            },
            options: ["Drag Reduction System", "Direct Racing System", "Downforce Regulation System", "Drive Response System"],
            correct: 0,
            explanation: {
                en: "DRS stands for Drag Reduction System, which opens the rear wing to reduce drag and increase speed.",
                es: "DRS significa Drag Reduction System, que abre el alerón trasero para reducir la resistencia y aumentar la velocidad.",
                de: "DRS steht für Drag Reduction System, das den Heckflügel öffnet, um den Luftwiderstand zu reduzieren.",
                nl: "DRS staat voor Drag Reduction System, dat de achtervleugel opent om weerstand te verminderen en snelheid te verhogen."
            }
        },
        {
            question: {
                en: "What does KERS stand for?",
                es: "¿Qué significa KERS?",
                de: "Wofür steht KERS?",
                nl: "Waar staat KERS voor?"
            },
            options: ["Kinetic Energy Recovery System", "Kinetic Engine Response System", "Kinetic Efficiency Racing System", "Kinetic Energy Regulation System"],
            correct: 0,
            explanation: {
                en: "KERS stands for Kinetic Energy Recovery System, recovering energy from braking.",
                es: "KERS significa Kinetic Energy Recovery System, recuperando energía del frenado.",
                de: "KERS steht für Kinetic Energy Recovery System, das Energie beim Bremsen zurückgewinnt.",
                nl: "KERS staat voor Kinetic Energy Recovery System, dat energie terugwint bij het remmen."
            }
        },
        {
            question: {
                en: "When was the safety car first introduced to Formula 1?",
                es: "¿Cuándo se introdujo por primera vez el coche de seguridad en la Fórmula 1?",
                de: "Wann wurde das Safety Car erstmals in der Formel 1 eingeführt?",
                nl: "Wanneer werd de safety car voor het eerst geïntroduceerd in Formule 1?"
            },
            options: ["1970s", "1980s", "1990s", "2000s"],
            correct: 1,
            explanation: {
                en: "The safety car was first used in 1973, but became a regular feature in the 1980s.",
                es: "El coche de seguridad se usó por primera vez en 1973, pero se convirtió en una característica regular en los años 80.",
                de: "Das Safety Car wurde erstmals 1973 eingesetzt, wurde aber in den 1980er Jahren zum Standard.",
                nl: "De safety car werd voor het eerst gebruikt in 1973, maar werd een vast onderdeel in de jaren 80."
            }
        },
        {
            question: {
                en: "How have pit stops evolved in Formula 1?",
                es: "¿Cómo han evolucionado las paradas en boxes en la Fórmula 1?",
                de: "Wie haben sich die Boxenstopps in der Formel 1 entwickelt?",
                nl: "Hoe zijn pitstops geëvolueerd in Formule 1?"
            },
            options: ["They take longer now", "They became faster and more efficient", "They were eliminated", "They happen less frequently"],
            correct: 1,
            explanation: {
                en: "Pit stops have evolved from minutes in the 1950s to under 2 seconds today with specialized equipment.",
                es: "Las paradas en boxes han evolucionado de minutos en los años 50 a menos de 2 segundos hoy con equipo especializado.",
                de: "Boxenstopps haben sich von Minuten in den 1950ern zu unter 2 Sekunden heute entwickelt.",
                nl: "Pitstops zijn geëvolueerd van minuten in de jaren 50 tot minder dan 2 seconden vandaag met gespecialiseerde apparatuur."
            }
        },
        {
            question: {
                en: "What is telemetry in Formula 1?",
                es: "¿Qué es la telemetría en la Fórmula 1?",
                de: "Was ist Telemetrie in der Formel 1?",
                nl: "Wat is telemetrie in Formule 1?"
            },
            options: ["Driver communication", "Real-time data transmission from car to team", "Tire pressure monitoring", "Fuel consumption tracking"],
            correct: 1,
            explanation: {
                en: "Telemetry transmits real-time data from hundreds of car sensors to the team for analysis.",
                es: "La telemetría transmite datos en tiempo real desde cientos de sensores del coche al equipo para análisis.",
                de: "Telemetrie überträgt Echtzeitdaten von Hunderten von Sensoren im Auto an das Team zur Analyse.",
                nl: "Telemetrie zendt real-time data van honderden sensoren in de auto naar het team voor analyse."
            }
        },
        {
            question: {
                en: "When was the carbon fiber monocoque first introduced?",
                es: "¿Cuándo se introdujo por primera vez el monocasco de fibra de carbono?",
                de: "Wann wurde das Kohlefaser-Monocoque erstmals eingeführt?",
                nl: "Wanneer werd het carbon fiber monocoque voor het eerst geïntroduceerd?"
            },
            options: ["1970s", "1981", "1990s", "2000s"],
            correct: 1,
            explanation: {
                en: "The carbon fiber monocoque was first introduced by McLaren in 1981, revolutionizing car safety and strength.",
                es: "El monocasco de fibra de carbono fue introducido por primera vez por McLaren en 1981, revolucionando la seguridad del coche.",
                de: "Das Kohlefaser-Monocoque wurde erstmals 1981 von McLaren eingeführt und revolutionierte Sicherheit und Festigkeit.",
                nl: "Het carbon fiber monocoque werd in 1981 door McLaren geïntroduceerd, wat de veiligheid revolutioneerde."
            }
        },
        {
            question: {
                en: "What is the primary purpose of the rear wing in Formula 1?",
                es: "¿Cuál es el propósito principal del alerón trasero en la Fórmula 1?",
                de: "Was ist der Hauptzweck des Heckflügels in der Formel 1?",
                nl: "Wat is het hoofddoel van de achtervleugel in Formule 1?"
            },
            options: ["Reduce weight", "Generate downforce", "Improve aesthetics", "Protect the engine"],
            correct: 1,
            explanation: {
                en: "The rear wing generates downforce, pushing the car onto the track for better grip in corners.",
                es: "El alerón trasero genera carga aerodinámica, empujando el coche contra la pista para mejor agarre en curvas.",
                de: "Der Heckflügel erzeugt Abtrieb und drückt das Auto auf die Strecke für besseren Grip in Kurven.",
                nl: "De achtervleugel genereert neerwaartse druk, waardoor de auto beter grip heeft in bochten."
            }
        },
        {
            question: {
                en: "When can drivers use DRS during a race?",
                es: "¿Cuándo pueden los pilotos usar el DRS durante una carrera?",
                de: "Wann können Fahrer während eines Rennens DRS verwenden?",
                nl: "Wanneer kunnen coureurs DRS gebruiken tijdens een race?"
            },
            options: ["Anytime they want", "Only in designated zones when within 1 second of car ahead", "Only on lap 1", "Only during pit stops"],
            correct: 1,
            explanation: {
                en: "DRS can only be used in designated zones when a driver is within 1 second of the car ahead.",
                es: "El DRS solo se puede usar en zonas designadas cuando un piloto está a menos de 1 segundo del coche de delante.",
                de: "DRS kann nur in ausgewiesenen Zonen verwendet werden, wenn ein Fahrer weniger als 1 Sekunde hinter dem Vordermann ist.",
                nl: "DRS kan alleen worden gebruikt in aangewezen zones als een coureur binnen 1 seconde van de auto ervoor zit."
            }
        },
        {
            question: {
                en: "What was the main advantage of turbocharged engines in the 1980s?",
                es: "¿Cuál fue la principal ventaja de los motores turboalimentados en los años 80?",
                de: "Was war der Hauptvorteil von Turbomotoren in den 1980er Jahren?",
                nl: "Wat was het belangrijkste voordeel van turbomotoren in de jaren 80?"
            },
            options: ["Better fuel economy", "Significantly more horsepower", "Lighter weight", "Quieter operation"],
            correct: 1,
            explanation: {
                en: "Turbocharged engines produced significantly more power, with some reaching over 1,000 horsepower in qualifying.",
                es: "Los motores turboalimentados producían significativamente más potencia, algunos alcanzando más de 1,000 caballos en clasificación.",
                de: "Turbomotoren erzeugten deutlich mehr Leistung, einige erreichten im Qualifying über 1.000 PS.",
                nl: "Turbomotoren produceerden aanzienlijk meer vermogen, sommige bereikten meer dan 1.000 pk in de kwalificatie."
            }
        },
        {
            question: {
                en: "What is the purpose of tire blankets in Formula 1?",
                es: "¿Cuál es el propósito de las mantas para neumáticos en la Fórmula 1?",
                de: "Was ist der Zweck von Reifendecken in der Formel 1?",
                nl: "Wat is het doel van bandenwarmers in Formule 1?"
            },
            options: ["Keep tires clean", "Pre-heat tires to optimal temperature", "Protect tires from UV light", "Reduce tire pressure"],
            correct: 1,
            explanation: {
                en: "Tire blankets pre-heat tires to their optimal operating temperature before they are fitted to the car.",
                es: "Las mantas para neumáticos precalientan los neumáticos a su temperatura óptima antes de montarlos en el coche.",
                de: "Reifendecken erwärmen die Reifen vor der Montage auf ihre optimale Betriebstemperatur.",
                nl: "Bandenwarmers warmen banden voor op de optimale werktemperatuur voordat ze op de auto worden gemonteerd."
            }
        },
        {
            question: {
                en: "What is KERS primarily used for?",
                es: "¿Para qué se usa principalmente el KERS?",
                de: "Wofür wird KERS hauptsächlich verwendet?",
                nl: "Waarvoor wordt KERS voornamelijk gebruikt?"
            },
            options: ["Braking assistance", "Temporary power boost", "Fuel saving", "Steering assistance"],
            correct: 1,
            explanation: {
                en: "KERS provides a temporary power boost by recovering energy from braking and releasing it on demand.",
                es: "El KERS proporciona un impulso temporal de potencia al recuperar energía del frenado y liberarla bajo demanda.",
                de: "KERS bietet einen temporären Leistungsschub durch Energierückgewinnung beim Bremsen.",
                nl: "KERS biedt een tijdelijke vermogensboost door energie terug te winnen bij het remmen en deze op verzoek vrij te geven."
            }
        },
        {
            question: {
                en: "Why is carbon fiber used for the monocoque?",
                es: "¿Por qué se usa fibra de carbono para el monocasco?",
                de: "Warum wird Kohlefaser für das Monocoque verwendet?",
                nl: "Waarom wordt carbon fiber gebruikt voor het monocoque?"
            },
            options: ["It's cheaper", "It's very strong yet lightweight", "It's easier to manufacture", "It looks better"],
            correct: 1,
            explanation: {
                en: "Carbon fiber provides exceptional strength and rigidity while being much lighter than traditional materials.",
                es: "La fibra de carbono proporciona resistencia y rigidez excepcionales mientras es mucho más ligera que materiales tradicionales.",
                de: "Kohlefaser bietet außergewöhnliche Festigkeit und Steifigkeit bei viel geringerem Gewicht als traditionelle Materialien.",
                nl: "Carbon fiber biedt uitzonderlijke sterkte en stijfheid terwijl het veel lichter is dan traditionele materialen."
            }
        },
        {
            question: {
                en: "What was ground effect initially created with in the 1970s?",
                es: "¿Con qué se creó inicialmente el efecto suelo en los años 70?",
                de: "Womit wurde der Bodeneffekt in den 1970er Jahren zunächst erzeugt?",
                nl: "Waarmee werd het grondeffect aanvankelijk gecreëerd in de jaren 70?"
            },
            options: ["Wider tires", "Side skirts and underbody shape", "Larger wings", "Turbocharged engines"],
            correct: 1,
            explanation: {
                en: "Ground effect was initially created using side skirts and specially shaped underbodies to seal airflow.",
                es: "El efecto suelo se creó inicialmente usando faldones laterales y fondos con forma especial para sellar el flujo de aire.",
                de: "Der Bodeneffekt wurde zunächst durch Seitenschürzen und speziell geformte Unterböden erzeugt.",
                nl: "Het grondeffect werd aanvankelijk gecreëerd met behulp van zijrokken en speciaal gevormde onderkanten."
            }
        },
        {
            question: {
                en: "What innovation made shifting gears easier for drivers?",
                es: "¿Qué innovación facilitó el cambio de marchas para los pilotos?",
                de: "Welche Innovation erleichterte den Fahrern das Schalten?",
                nl: "Welke innovatie maakte het schakelen makkelijker voor coureurs?"
            },
            options: ["Automatic transmission", "Paddle shifters", "Voice control", "Remote shifting"],
            correct: 1,
            explanation: {
                en: "Paddle shifters behind the steering wheel allow drivers to shift without removing their hands.",
                es: "Las levas de cambio detrás del volante permiten a los pilotos cambiar sin quitar las manos.",
                de: "Schaltpaddles hinter dem Lenkrad ermöglichen das Schalten ohne die Hände zu entfernen.",
                nl: "Paddle shifters achter het stuur stellen coureurs in staat te schakelen zonder hun handen te verwijderen."
            }
        },
        {
            question: {
                en: "When was refueling during races banned in Formula 1?",
                es: "¿Cuándo se prohibió el repostaje durante las carreras en la Fórmula 1?",
                de: "Wann wurde das Nachtanken während der Rennen in der Formel 1 verboten?",
                nl: "Wanneer werd tanken tijdens races verboden in Formule 1?"
            },
            options: ["2000", "2005", "2010", "2015"],
            correct: 2,
            explanation: {
                en: "Refueling during races was banned from the 2010 season for safety and cost reasons.",
                es: "El repostaje durante las carreras se prohibió desde la temporada 2010 por razones de seguridad y costos.",
                de: "Das Nachtanken während der Rennen wurde ab der Saison 2010 aus Sicherheits- und Kostengründen verboten.",
                nl: "Tanken tijdens races werd vanaf het seizoen 2010 verboden om veiligheids- en kostenredenen."
            }
        },
        {
            question: {
                en: "When were hybrid engines introduced to Formula 1?",
                es: "¿Cuándo se introdujeron los motores híbridos en la Fórmula 1?",
                de: "Wann wurden Hybridmotoren in der Formel 1 eingeführt?",
                nl: "Wanneer werden hybride motoren geïntroduceerd in Formule 1?"
            },
            options: ["2010", "2012", "2014", "2016"],
            correct: 2,
            explanation: {
                en: "Hybrid power units with turbo V6 engines and energy recovery systems were introduced in 2014.",
                es: "Las unidades de potencia híbridas con motores V6 turbo y sistemas de recuperación de energía se introdujeron en 2014.",
                de: "Hybrid-Antriebseinheiten mit Turbo-V6-Motoren und Energierückgewinnungssystemen wurden 2014 eingeführt.",
                nl: "Hybride aandrijfeenheden met turbo V6-motoren en energieterugwinsystemen werden in 2014 geïntroduceerd."
            }
        }
    ];

    if (typeof window.questionsByLevel === 'undefined') {
        window.questionsByLevel = {};
    }
    if (typeof window.questionsByLevel['1 F1'] === 'undefined') {
        window.questionsByLevel['1 F1'] = {};
    }
    if (typeof window.questionsByLevel['1 F1']['Auto-innovaties'] === 'undefined') {
        window.questionsByLevel['1 F1']['Auto-innovaties'] = {};
    }
    window.questionsByLevel['1 F1']['Auto-innovaties']['level1'] = level1Questions;
})();
