// Jurassic Dinosaurs Quiz - Level 10: Research-Level Knowledge
(function() {
  const level10 = {
    name: {
      en: "Jurassic Dinosaurs Level 10",
      es: "Dinosaurios Jurásicos Nivel 10",
      de: "Jura Dinosaurier Stufe 10",
      nl: "Jura Dino's Level 10"
    },
    questions: [
      {
        question: {
          en: "What does synchrotron radiation X-ray fluorescence (SR-XRF) mapping reveal about trace element distribution in Allosaurus bone tissue from the Morrison Formation?",
          es: "¿Qué revela el mapeo de fluorescencia de rayos X por radiación sincrotrón (SR-XRF) sobre la distribución de elementos traza en el tejido óseo de Allosaurus de la Formación Morrison?",
          de: "Was zeigt die Synchrotron-Röntgenfluoreszenz-Kartierung (SR-XRF) über die Spurenelement-Verteilung im Knochengewebe von Allosaurus aus der Morrison-Formation?",
          nl: "Wat onthult synchrotron straling röntgenfluorescentie (SR-XRF) kartering over sporenelement distributie in Allosaurus botweefsel uit de Morrison Formatie?"
        },
        options: [
          { en: "Elevated zinc concentrations in osteonal bone indicate high metabolic activity with rapid remodeling rates comparable to modern endothermic vertebrates", es: "Concentraciones elevadas de zinc en hueso osteonado indican alta actividad metabólica con tasas de remodelación rápidas comparables a vertebrados endotérmicos modernos", de: "Erhöhte Zinkkonzentrationen im Osteonal-Knochen deuten auf hohe Stoffwechselaktivität mit schnellen Umbauprozessen vergleichbar mit modernen endothermen Wirbeltieren hin", nl: "Verhoogde zinkconcentraties in osteonaal bot duiden op hoge metabolische activiteit met snelle hermodelleringspercentages vergelijkbaar met moderne endotherme vertebraten" },
          { en: "Uniform element distribution suggests simple bone structure", es: "Distribución uniforme de elementos sugiere estructura ósea simple", de: "Gleichmäßige Elementverteilung deutet auf einfache Knochenstruktur hin", nl: "Uniforme elementverdeling suggereert eenvoudige botstructuur" },
          { en: "Trace elements only indicate fossilization processes", es: "Elementos traza solo indican procesos de fossilización", de: "Spurenelemente zeigen nur Fossilisierungsprozesse", nl: "Sporenelementen duiden alleen op fossilisatieprocessen" },
          { en: "SR-XRF cannot distinguish metabolic signatures", es: "SR-XRF no puede distinguir firmas metabólicas", de: "SR-XRF kann metabolische Signaturen nicht unterscheiden", nl: "SR-XRF kan metabolische handtekeningen niet onderscheiden" }
        ],
        correct: 0,
        explanation: {
          en: "SR-XRF allows non-destructive high-resolution mapping of trace elements like zinc, copper, and strontium in fossil bone. Zinc concentrations in vascular channels and osteons correlate with metabolic rates in modern animals, providing evidence for endothermic metabolism in large theropods.",
          es: "SR-XRF permite mapeo no destructivo de alta resolución de elementos traza como zinc, cobre y estroncio en hueso fósil. Las concentraciones de zinc en canales vasculares y osteones se correlacionan con tasas metabólicas en animales modernos, proporcionando evidencia de metabolismo endotérmico en terópodos grandes.",
          de: "SR-XRF ermöglicht nicht-destruktive hochauflösende Kartierung von Spurenelementen wie Zink, Kupfer und Strontium in fossilem Knochen. Zinkkonzentrationen in vaskulären Kanälen und Osteonen korrelieren mit Stoffwechselraten bei modernen Tieren und liefern Beweise für endothermen Stoffwechsel bei großen Theropoden.",
          nl: "SR-XRF maakt niet-destructieve hoge-resolutie kartering mogelijk van sporenelementen zoals zink, koper en strontium in fossiel bot. Zinkconcentraties in vasculaire kanalen en osteonen correleren met metabolische percentages in moderne dieren, wat bewijs levert voor endotherm metabolisme in grote theropoden."
        }
      },
      {
        question: {
          en: "How does NanoSIMS (nanoscale secondary ion mass spectrometry) isotopic analysis of Brachiosaurus tooth enamel constrain paleodiet reconstruction through carbon and oxygen isotope ratios?",
          es: "¿Cómo el análisis isotópico de NanoSIMS (espectrometría de masas de iones secundarios a nanoescala) del esmalte dental de Brachiosaurus restringe la reconstrucción de paleodieta através de proporciones de isótopos de carbono y oxígeno?",
          de: "Wie grenzt die NanoSIMS-Isotopenanalyse (Nanoskala-Sekundärionen-Massenspektrometrie) des Brachiosaurus-Zahnschmelzes die Paläodiät-Rekonstruktion durch Kohlenstoff- und Sauerstoff-Isotopenverhältnisse ein?",
          nl: "Hoe beperkt NanoSIMS (nanoschaal secundaire ion massacpectrometrie) isotopische analyse van Brachiosaurus tandglazuur paleodieet reconstructie door koolstof en zuurstof isotoop verhoudingen?"
        },
        options: [
          { en: "δ13C values around -8‰ indicate C3 plant consumption with seasonal variation in δ18O suggesting migration between xeric and mesic environments", es: "Valores de δ13C alrededor de -8‰ indican consumo de plantas C3 con variación estacional en δ18O sugiriendo migración entre ambientes xéricos y mésicos", de: "δ13C-Werte um -8‰ deuten auf C3-Pflanzenkonsum mit saisonaler Variation in δ18O hin, was auf Migration zwischen xerischen und mesischen Umgebungen hindeutet", nl: "δ13C waarden rond -8‰ duiden op C3 plant consumptie met seizoensvariatie in δ18O wat migratie tussen xere en mesische omgevingen suggereert" },
          { en: "Isotope ratios only reflect water chemistry", es: "Proporciones de isótopos solo reflejan química del agua", de: "Isotopenverhältnisse spiegeln nur Wasserchemie wider", nl: "Isotoop verhoudingen weerspiegelen alleen waterchemie" },
          { en: "NanoSIMS cannot distinguish diet types", es: "NanoSIMS no puede distinguir tipos de dieta", de: "NanoSIMS kann Diättypen nicht unterscheiden", nl: "NanoSIMS kan dieet types niet onderscheiden" },
          { en: "All sauropods show identical isotope signatures", es: "Todos los saurópodos muestran firmas isotópicas idénticas", de: "Alle Sauropoden zeigen identische Isotopen-Signaturen", nl: "Alle sauropoden tonen identieke isotoop handtekeningen" }
        ],
        correct: 0,
        explanation: {
          en: "NanoSIMS enables ultra-high spatial resolution isotope analysis at the micrometer scale. Carbon isotopes distinguish C3 vs C4 plant consumption, while oxygen isotopes reflect water sources and body water composition. Intra-tooth variation reveals seasonal dietary changes and potential migration patterns.",
          es: "NanoSIMS permite análisis isotópico de ultra alta resolución espacial a escala micrométrica. Los isótopos de carbono distinguen consumo de plantas C3 vs C4, mientras que los isótopos de oxígeno reflejan fuentes de agua y composición de agua corporal. La variación intra-dental revela cambios dietéticos estacionales y patrones potenciales de migración.",
          de: "NanoSIMS ermöglicht Isotopen-Analyse mit ultrahoch räumlicher Auflösung im Mikrometerbereich. Kohlenstoff-Isotope unterscheiden C3- vs. C4-Pflanzenkonsum, während Sauerstoff-Isotope Wasserquellen und Körperwasserzusammensetzung widerspiegeln. Intra-Zahn-Variation enthüllt saisonale Ernährungsänderungen und potenzielle Migrationsmuster.",
          nl: "NanoSIMS maakt ultra-hoge ruimtelijke resolutie isotoop analyse mogelijk op micrometer schaal. Koolstof isotopen onderscheiden C3 vs C4 plant consumptie, terwijl zuurstof isotopen waterbronnen en lichaamswatersamenstelling weerspiegelen. Intra-tand variatie onthult seizoensgebonden dieet veranderingen en potentiële migratiepatronen."
        }
      },
      {
        question: {
          en: "What information does laser ablation inductively coupled plasma mass spectrometry (LA-ICP-MS) of Stegosaurus bone collagen provide about ontogenetic niche partitioning through strontium-calcium ratios?",
          es: "¿Qué información proporciona la espectrometría de masas de plasma acoplado inductivamente por ablación láser (LA-ICP-MS) del colágeno óseo de Stegosaurus sobre partición de nicho ontogenético através de proporciones estroncio-calcio?",
          de: "Welche Informationen liefert die Laserablations-induktiv-gekoppelte Plasma-Massenspektrometrie (LA-ICP-MS) des Stegosaurus-Kollagen über ontogenetische Nischen-Partitionierung durch Strontium-Calcium-Verhältnisse?",
          nl: "Welke informatie levert laser ablatie inductief gekoppelde plasma massacpectrometrie (LA-ICP-MS) van Stegosaurus bot collageen over ontogenetische niche partitionering door strontium-calcium verhoudingen?"
        },
        options: [
          { en: "Elevated Sr/Ca in juveniles indicates higher browse height preference shifting to lower strontium vegetation in adults, demonstrating age-based dietary niche separation", es: "Sr/Ca elevado en juveniles indica preferencia por altura de ramoneo más alta cambiando a vegetación con menor estroncio en adultos, demostrando separación de nicho dietético basada en edad", de: "Erhöhtes Sr/Ca bei Jungtieren deutet auf höhere Fraßhöhen-Präferenz hin, die sich bei Adulten zu Vegetation mit niedrigerem Strontium verschiebt und altersbasierte diätetische Nischen-Trennung demonstriert", nl: "Verhoogd Sr/Ca in juvenielen duidt op hogere browse hoogte voorkeur die verschuift naar lagere strontium vegetatie in volwassenen, wat leeftijdsgebaseerde dieet niche scheiding demonstreert" }
,
          { en: "Sr/Ca ratios are constant across all ages", es: "Proporciones Sr/Ca son constantes en todas las edades", de: "Sr/Ca-Verhältnisse sind über alle Altersgruppen konstant", nl: "Sr/Ca verhoudingen zijn constant over alle leeftijden" },
          { en: "Strontium only indicates water sources", es: "Estroncio solo indica fuentes de agua", de: "Strontium zeigt nur Wasserquellen an", nl: "Strontium duidt alleen op waterbronnen" },
          { en: "LA-ICP-MS cannot resolve ontogenetic changes", es: "LA-ICP-MS no puede resolver cambios ontogenéticos", de: "LA-ICP-MS kann ontogenetische Veränderungen nicht auflösen", nl: "LA-ICP-MS kan ontogenetische veranderingen niet oplossen" }
        ],
        correct: 0,
        explanation: {
          en: "LA-ICP-MS allows high-resolution trace element profiling along growth lines in bone. Strontium substitutes for calcium in bone mineral and varies with dietary plant types and soil chemistry. Sr/Ca ratios can track dietary shifts across ontogeny, revealing ecological niche partitioning between juveniles and adults to reduce intraspecific competition.",
          es: "LA-ICP-MS permite perfilado de elementos traza de alta resolución a lo largo de líneas de crecimiento en hueso. El estroncio sustituye al calcio en mineral óseo y varía con tipos de plantas dietéticas y química del suelo. Las proporciones Sr/Ca pueden rastrear cambios dietéticos através de la ontogenia, revelando partición de nicho ecológico entre juveniles y adultos para reducir competencia intraespecífica.",
          de: "LA-ICP-MS ermöglicht hochauflösendes Spurenelement-Profiling entlang Wachstumslinien im Knochen. Strontium ersetzt Calcium im Knochenmineral und variiert mit diätetischen Pflanzentypen und Bodenchemie. Sr/Ca-Verhältnisse können diätetische Verschiebungen über die Ontogenese verfolgen und ökologische Nischen-Partitionierung zwischen Jungtieren und Adulten zur Reduzierung intraspezifischer Konkurrenz enthüllen.",
          nl: "LA-ICP-MS maakt hoge-resolutie sporenelement profilering mogelijk langs groeilijnen in bot. Strontium vervangt calcium in botmineraal en varieert met dieet plant types en bodemchemie. Sr/Ca verhoudingen kunnen dieet verschuivingen over ontogenie volgen, wat ecologische niche partitionering tussen juvenielen en volwassenen onthult om intraspecifieke competitie te verminderen."
        }
      },
      {
        question: {
          en: "How does computational fluid dynamics (CFD) analysis of digitally reconstructed Dilophosaurus skull morphology constrain hypotheses about olfactory capability and feeding biomechanics?",
          es: "¿Cómo el análisis de dinámica de fluidos computacional (CFD) de la morfología craneal de Dilophosaurus reconstruida digitalmente restringe hipótesis sobre capacidad olfativa y biomecánica de alimentación?",
          de: "Wie grenzt die computergestützte Strömungsdynamik-Analyse (CFD) der digital rekonstruierten Dilophosaurus-Schädelmorphologie Hypothesen über Geruchsfähigkeit und Fraß-Biomechanik ein?",
          nl: "Hoe beperkt computationele vloeistofdynamica (CFD) analyse van digitaal gereconstrueerde Dilophosaurus schedel morfologie hypothesen over reuk capaciteit en voedings biomechanica?"
        },
        options: [
          { en: "Airflow modeling reveals high turbulence in nasal cavity with extensive olfactory epithelium surface area contact, indicating enhanced chemoreception comparable to modern vultures", es: "Modelado de flujo de aire revela alta turbulencia en cavidad nasal con extenso contacto de área superficial de epitelio olfativo, indicando quimiorecepción mejorada comparable a buitres modernos", de: "Luftströmungs-Modellierung enthüllt hohe Turbulenz in Nasenhöhle mit ausgedehntem Kontakt der Riechepithel-Oberfläche, was auf verbesserte Chemorezeption vergleichbar mit modernen Geiern hindeutet", nl: "Luchtstroom modellering onthult hoge turbulentie in neusholte met uitgebreid reukepitheel oppervlakte contact, wat wijst op verbeterde chemoreceptie vergelijkbaar met moderne gieren" },
          { en: "CFD shows poor airflow indicating weak olfaction", es: "CFD muestra flujo de aire pobre indicando olfato débil", de: "CFD zeigt schlechten Luftstrom mit schwachem Geruchssinn", nl: "CFD toont slechte luchtstroom wat wijst op zwakke reuk" },
          { en: "Skull shape has no relationship to sensory abilities", es: "Forma del cráneo no tiene relación con habilidades sensoriales", de: "Schädelform hat keine Beziehung zu sensorischen Fähigkeiten", nl: "Schedelvorm heeft geen relatie met sensorische vaardigheden" },
          { en: "CFD cannot be applied to extinct organisms", es: "CFD no puede aplicarse a organismos extintos", de: "CFD kann nicht auf ausgestorbene Organismen angewendet werden", nl: "CFD kan niet worden toegepast op uitgestorven organismen" }
        ],
        correct: 0,
        explanation: {
          en: "CFD simulates airflow through digital skull reconstructions from CT scans. High turbulence and prolonged air contact with nasal epithelium indicates enhanced olfaction. The technique can also model bite forces, stress distribution during feeding, and thermoregulatory airflow patterns, providing functional interpretations of skull morphology.",
          es: "CFD simula flujo de aire através de reconstrucciones craneales digitales de tomografías computarizadas. Alta turbulencia y contacto prolongado de aire con epitelio nasal indica olfato mejorado. La técnica también puede modelar fuerzas de mordida, distribución de estrés durante alimentación y patrones de flujo de aire termorreguladores, proporcionando interpretaciones funcionales de morfología craneal.",
          de: "CFD simuliert Luftstrom durch digitale Schädelrekonstruktionen aus CT-Scans. Hohe Turbulenz und verlängerter Luftkontakt mit Nasenepithel deutet auf verbesserten Geruchssinn hin. Die Technik kann auch Beißkräfte, Spannungsverteilung während der Nahrungsaufnahme und thermoregulatorische Luftströmungsmuster modellieren und funktionale Interpretationen der Schädelmorphologie liefern.",
          nl: "CFD simuleert luchtstroom door digitale schedel reconstructies van CT-scans. Hoge turbulentie en langdurig luchtcontact met neus epitheel duidt op verbeterde reuk. De techniek kan ook bijtkrachten, stress distributie tijdens voeding en thermoregulatoire luchtstroom patronen modelleren, wat functionele interpretaties van schedel morfologie levert."
        }
      },
      {
        question: {
          en: "What does electron backscatter diffraction (EBSD) analysis of Archaeopteryx feather keratin reveal about the evolutionary origin of asymmetric flight feathers?",
          es: "¿Qué revela el análisis de difracción de electrones retrodispersados (EBSD) de la queratina de plumas de Archaeopteryx sobre el origen evolutivo de plumas de vuelo asimétricas?",
          de: "Was zeigt die Elektronen-Rückstreu-Beugungsanalyse (EBSD) des Archaeopteryx-Feder-Keratins über den evolutionären Ursprung asymmetrischer Flugfedern?",
          nl: "Wat onthult elektronenverstrooiingsdiffractie (EBSD) analyse van Archaeopteryx veer keratine over de evolutionaire oorsprong van asymmetrische vluchtveren?"
        },
        options: [
          { en: "Crystallographic orientation mapping shows aligned β-keratin fibril arrays with hierarchical organization matching modern flying birds, indicating functional aerodynamic feathers", es: "Mapeo de orientación cristalográfica muestra matrices de fibrillas de β-queratina alineadas con organización jerárquica coincidente con aves voladoras modernas, indicando plumas aerodinámicas funcionales", de: "Kristallographische Orientierungs-Kartierung zeigt ausgerichtete β-Keratin-Fibrillen-Arrays mit hierarchischer Organisation, die modernen fliegenden Vögeln entspricht, was auf funktionale aerodynamische Federn hindeutet", nl: "Kristallografische oriëntatie kartering toont uitgelijnde β-keratine fibril arrays met hiërarchische organisatie overeenkomend met moderne vliegende vogels, wat wijst op functionele aerodynamische veren" },
          { en: "Random keratin structure suggests non-functional feathers", es: "Estructura de queratina aleatoria sugiere plumas no funcionales", de: "Zufällige Keratin-Struktur deutet auf nicht-funktionale Federn hin", nl: "Willekeurige keratine structuur suggereert niet-functionele veren" },
          { en: "EBSD cannot analyze fossilized organic material", es: "EBSD no puede analizar material orgánico fossilizado", de: "EBSD kann fossilisiertes organisches Material nicht analysieren", nl: "EBSD kan gefossiliseerd organisch materiaal niet analyseren" },
          { en: "Archaeopteryx feathers lacked organized structure", es: "Plumas de Archaeopteryx carecían de estructura organizada", de: "Archaeopteryx-Federn fehlte organisierte Struktur", nl: "Archaeopteryx veren misten georganiseerde structuur" }
        ],
        correct: 0,
        explanation: {
          en: "EBSD maps crystallographic orientations in materials at the nanoscale. When preserved, fossil keratin retains structural organization. Aligned β-keratin fibrils with hierarchical branching patterns identical to modern flight feathers provide evidence that Archaeopteryx possessed aerodynamically functional feathers capable of generating lift and thrust.",
          es: "EBSD mapea orientaciones cristalográficas en materiales a nanoescala. Cuando se preserva, la queratina fósil retiene organización estructural. Fibrillas de β-queratina alineadas con patrones de ramificación jerárquica idénticos a plumas de vuelo modernas proporcionan evidencia de que Archaeopteryx poseía plumas aerodinámicamente funcionales capaces de generar sustentación y empuje.",
          de: "EBSD kartiert kristallographische Orientierungen in Materialien im Nanomaßstab. Wenn erhalten, behält fossiles Keratin strukturelle Organisation. Ausgerichtete β-Keratin-Fibrillen mit hierarchischen Verzweigungsmustern identisch mit modernen Flugfedern liefern Beweise, dass Archaeopteryx aerodynamisch funktionale Federn besaß, die Auftrieb und Schub erzeugen konnten.",
          nl: "EBSD brengt kristallografische oriëntaties in materialen op nanoschaal in kaart. Wanneer bewaard, behoudt fossiel keratine structurele organisatie. Uitgelijnde β-keratine fibrillen met hiërarchische vertakkingspatronen identiek aan moderne vluchtveren leveren bewijs dat Archaeopteryx aerodynamisch functionele veren bezat die lift en stuwkracht konden genereren."
        }
      },
      {
        question: {
          en: "How does finite element analysis (FEA) of Camarasaurus vertebral pneumatic structures constrain estimates of axial skeleton mass reduction and its implications for sauropod gigantism?",
          es: "¿Cómo el análisis de elementos finitos (FEA) de estructuras neumáticas vertebrales de Camarasaurus restringe estimaciones de reducción de masa del esqueleto axial y sus implicaciones para el gigantismo de saurópodos?",
          de: "Wie grenzt die Finite-Elemente-Analyse (FEA) der pneumatischen Wirbel-Strukturen von Camarasaurus Schätzungen der axialen Skelett-Massenreduktion und deren Implikationen für Sauropoden-Gigantismus ein?",
          nl: "Hoe beperkt eindige elementen analyse (FEA) van Camarasaurus vertebrale pneumatische structuren schattingen van axiale skelet massareductie en de implicaties voor sauropode gigantengroei?"
        },
        options: [
          { en: "Stress distribution modeling shows pneumatic chambers reduce vertebral mass by 40-50% while maintaining structural integrity under 4-6g peak loading, enabling extreme body size evolution", es: "Modelado de distribución de estrés muestra que cámaras neumáticas reducen masa vertebral en 40-50% mientras mantienen integridad estructural bajo carga pico de 4-6g, permitiendo evolución de tamaño corporal extremo", de: "Spannungsverteilungs-Modellierung zeigt, dass pneumatische Kammern die Wirbelmasse um 40-50% reduzieren, während strukturelle Integrität unter 4-6g Spitzenbelastung erhalten bleibt, was extreme Körpergrößen-Evolution ermöglicht", nl: "Stress distributie modellering toont aan dat pneumatische kamers vertebrale massa met 40-50% verminderen terwijl structurele integriteit behouden blijft onder 4-6g piekbelasting, wat extreme lichaamsgrootte evolutie mogelijk maakt" },
          { en: "Pneumatic structures weaken the skeleton", es: "Estructuras neumáticas debilitan el esqueleto", de: "Pneumatische Strukturen schwächen das Skelett", nl: "Pneumatische structuren verzwakken het skelet" },
          { en: "FEA shows no mechanical advantage of pneumaticity", es: "FEA muestra ninguna ventaja mecánica de neumaticidad", de: "FEA zeigt keinen mechanischen Vorteil der Pneumatizität", nl: "FEA toont geen mechanisch voordeel van pneumaticiteit" },
          { en: "Vertebral mass had no impact on body size limits", es: "Masa vertebral no tuvo impacto en límites de tamaño corporal", de: "Wirbelmasse hatte keinen Einfluss auf Körpergrößen-Grenzen", nl: "Vertebrale massa had geen impact op lichaamsgrootte limieten" }
        ],
        correct: 0,
        explanation: {
          en: "FEA models stress and strain distribution in complex 3D structures under loading. Analysis of pneumatic vertebrae shows that air-filled chambers strategically positioned in low-stress regions dramatically reduce mass without compromising strength. This mass reduction was critical for sauropods to overcome square-cube scaling constraints and achieve gigantic body sizes.",
          es: "FEA modela distribución de estrés y tensión en estructuras 3D complejas bajo carga. El análisis de vértebras neumáticas muestra que cámaras llenas de aire posicionadas estratégicamente en regiones de bajo estrés reducen dramáticamente la masa sin comprometer resistencia. Esta reducción de masa fue crítica para que saurópodos superaran restricciones de escalado cuadrado-cúbico y alcanzaran tamaños corporales gigantescos.",
          de: "FEA modelliert Spannungs- und Dehnungsverteilung in komplexen 3D-Strukturen unter Belastung. Analyse pneumatischer Wirbel zeigt, dass luftgefüllte Kammern, die strategisch in Niedrigspannungsregionen positioniert sind, die Masse dramatisch reduzieren, ohne die Festigkeit zu beeinträchtigen. Diese Massenreduktion war kritisch für Sauropoden, um quadratisch-kubische Skalierungsbeschränkungen zu überwinden und gigantische Körpergrößen zu erreichen.",
          nl: "FEA modelleert stress en rek distributie in complexe 3D structuren onder belasting. Analyse van pneumatische wervels toont dat luchtgevulde kamers strategisch gepositioneerd in lage-stress regio's de massa dramatisch verminderen zonder kracht in gevaar te brengen. Deze massareductie was kritiek voor sauropoden om vierkant-kubus schaalbaarheidsbeperkingen te overwinnen en gigantische lichaamsgroottes te bereiken."
        }
      },
      {
        question: {
          en: "What do clumped isotope thermometry (Δ47) measurements from Diplodocus bone bioapatite reveal about body temperature regulation and metabolic thermogenesis?",
          es: "¿Qué revelan las mediciones de termometría de isótopos agrupados (Δ47) de bioapatita ósea de Diplodocus sobre regulación de temperatura corporal y termogénesis metabólica?",
          de: "Was zeigen geclusterte Isotopen-Thermometrie-Messungen (Δ47) von Diplodocus-Knochen-Bioapatit über Körpertemperatur-Regulation und metabolische Thermogenese?",
          nl: "Wat onthullen geclusterde isotoop thermometrie (Δ47) metingen van Diplodocus bot bioapatiet over lichaamstemperatuur regulatie en metabolische thermogenese?"
        },
        options: [
          { en: "Δ47 values indicate body temperatures of 36-38°C independent of ambient temperature, suggesting endothermic homeothermy with metabolic heat generation", es: "Valores de Δ47 indican temperaturas corporales de 36-38°C independientes de temperatura ambiente, sugiriendo homeotermia endotérmica con generación de calor metabólico", de: "Δ47-Werte deuten auf Körpertemperaturen von 36-38°C unabhängig von Umgebungstemperatur hin, was endotherme Homöothermie mit metabolischer Wärmeerzeugung nahelegt", nl: "Δ47 waarden duiden op lichaamstemperaturen van 36-38°C onafhankelijk van omgevingstemperatuur, wat endotherme homeothermie met metabolische warmteproductie suggereert" },
          { en: "Temperature varied with ambient conditions showing ectothermy", es: "Temperatura variaba con condiciones ambientes mostrando ectotermia", de: "Temperatur variierte mit Umgebungsbedingungen und zeigte Ektothermie", nl: "Temperatuur varieerde met omgevingscondities wat ectothermie toont" },
          { en: "Clumped isotopes cannot determine body temperature", es: "Isótopos agrupados no pueden determinar temperatura corporal", de: "Geclusterte Isotopen können Körpertemperatur nicht bestimmen", nl: "Geclusterde isotopen kunnen lichaamstemperatuur niet bepalen" },
          { en: "All dinosaurs show identical temperature values", es: "Todos los dinosaurios muestran valores de temperatura idénticos", de: "Alle Dinosaurier zeigen identische Temperaturwerte", nl: "Alle dinosaurussen tonen identieke temperatuur waarden" }
        ],
        correct: 0,
        explanation: {
          en: "Clumped isotope thermometry measures the temperature-dependent bonding of heavy isotopes (13C-18O) in carbonate, providing direct body temperature estimates. Studies show large sauropods maintained warm, stable body temperatures inconsistent with pure ectothermy, suggesting metabolic heat production combined with gigantothermy for thermal homeostasis.",
          es: "Termometría de isótopos agrupados mide la unión dependiente de temperatura de isótopos pesados (13C-18O) en carbonato, proporcionando estimaciones directas de temperatura corporal. Estudios muestran que saurópodos grandes mantuvieron temperaturas corporales cálidas y estables inconsistentes con ectotermia pura, sugiriendo producción de calor metabólico combinada con giganotermia para homeostasis térmica.",
          de: "Geclusterte Isotopen-Thermometrie misst die temperaturabhängige Bindung schwerer Isotope (13C-18O) im Karbonat und liefert direkte Körpertemperatur-Schätzungen. Studien zeigen, dass große Sauropoden warme, stabile Körpertemperaturen aufrechterhielten, die mit reiner Ektothermie unvereinbar sind, was metabolische Wärmeerzeugung kombiniert mit Gigantothermie für thermale Homöostase nahelegt.",
          nl: "Geclusterde isotoop thermometrie meet de temperatuurafhankelijke binding van zware isotopen (13C-18O) in carbonaat, wat directe lichaamstemperatuur schattingen levert. Studies tonen aan dat grote sauropoden warme, stabiele lichaamstemperaturen handhaafden die inconsistent zijn met pure ectothermie, wat metabolische warmteproductie gecombineerd met gigantothermie voor thermale homeostase suggereert."
        }
      },
      {
        question: {
          en: "How does geometric morphometric analysis combined with phylogenetic comparative methods constrain hypotheses about evolutionary trends in theropod skull shape during the Middle to Late Jurassic?",
          es: "¿Cómo el análisis morfométrico geométrico combinado con métodos comparativos filogenéticos restringe hipótesis sobre tendencias evolutivas en forma craneal de terópodos durante el Jurásico Medio a Tardío?",
          de: "Wie grenzen geometrisch-morphometrische Analysen kombiniert mit phylogenetischen Vergleichsmethoden Hypothesen über evolutionäre Trends in Theropoden-Schädelform während des Mittleren bis Späten Jura ein?",
          nl: "Hoe beperkt geometrische morfometrische analyse gecombineerd met fylogenetische vergelijkende methoden hypothesen over evolutionaire trends in theropode schedelvorm tijdens het Midden tot Laat Jura?"
        },
        options: [
          { en: "Landmark-based principal component analysis with phylogenetic independent contrasts reveals convergent evolution toward elongate snouts and increased gape angle in multiple theropod lineages adapting to different prey sizes", es: "Análisis de componentes principales basado en puntos de referencia con contrastes independientes filogenéticos revela evolución convergente hacia hocicos elongados y aumento de ángulo de abertura en múltiples linajes de terópodos adaptándose a diferentes tamaños de presa", de: "Landmarken-basierte Hauptkomponentenanalyse mit phylogenetischen unabhängigen Kontrasten enthüllt konvergente Evolution zu länglichen Schnauzen und erhöhtem Maulöffnungswinkel in mehreren Theropoden-Linien, die sich an unterschiedliche Beutetiergrößen anpassen", nl: "Landmerk-gebaseerde principale componenten analyse met fylogenetische onafhankelijke contrasten onthult convergente evolutie naar langwerpige snuiten en verhoogde kaakhoek in meerdere theropode lijnen die zich aanpassen aan verschillende prooi groottes" },
          { en: "All theropod skulls evolved in a single linear trend", es: "Todos los cráneos de terópodos evolucionaron en una tendencia lineal única", de: "Alle Theropoden-Schädel entwickelten sich in einem einzigen linearen Trend", nl: "Alle theropode schedels evolueerden in een enkele lineaire trend" },
          { en: "Skull shape changes were random without adaptive pattern", es: "Cambios en forma craneal fueron aleatorios sin patrón adaptativo", de: "Schädelform-Änderungen waren zufällig ohne adaptives Muster", nl: "Schedelvorm veranderingen waren willekeurig zonder adaptief patroon" },
          { en: "Morphometrics cannot distinguish evolutionary trends", es: "Morfometría no puede distinguir tendencias evolutivas", de: "Morphometrie kann evolutionäre Trends nicht unterscheiden", nl: "Morfometrie kan evolutionaire trends niet onderscheiden" }
        ],
        correct: 0,
        explanation: {
          en: "Geometric morphometrics quantifies shape variation using landmark coordinates, while phylogenetic comparative methods account for shared evolutionary history. This combination reveals convergent adaptations versus phylogenetic constraints, showing multiple theropod lineages independently evolved similar skull modifications for different feeding ecologies despite different ancestral conditions.",
          es: "Morfometría geométrica cuantifica variación de forma usando coordenadas de puntos de referencia, mientras métodos comparativos filogenéticos consideran historia evolutiva compartida. Esta combinación revela adaptaciones convergentes versus restricciones filogenéticas, mostrando que múltiples linajes de terópodos evolucionaron independientemente modificaciones craneales similares para diferentes ecologías de alimentación a pesar de condiciones ancestrales diferentes.",
          de: "Geometrische Morphometrie quantifiziert Formvariation unter Verwendung von Landmarken-Koordinaten, während phylogenetische Vergleichsmethoden gemeinsame evolutionäre Geschichte berücksichtigen. Diese Kombination enthüllt konvergente Anpassungen versus phylogenetische Beschränkungen und zeigt, dass mehrere Theropoden-Linien unabhängig ähnliche Schädel-Modifikationen für unterschiedliche Fraßökologien trotz unterschiedlicher Ausgangsbedingungen entwickelten.",
          nl: "Geometrische morfometrie kwantificeert vormvariatie met behulp van landmerk coördinaten, terwijl fylogenetische vergelijkende methoden rekening houden met gedeelde evolutionaire geschiedenis. Deze combinatie onthult convergente aanpassingen versus fylogenetische beperkingen, wat laat zien dat meerdere theropode lijnen onafhankelijk vergelijkbare schedel modificaties evolueerden voor verschillende voedings ecologieën ondanks verschillende voorouderlijke condities."
        }
      },
      {
        question: {
          en: "What does Raman spectroscopy of carbonaceous material associated with Anchiornis specimens reveal about preservation of original biochemical compounds versus diagenetic alteration products?",
          es: "¿Qué revela la espectroscopía Raman de material carbonáceo asociado con especímenes de Anchiornis sobre preservación de compuestos bioquímicos originales versus productos de alteración diagenética?",
          de: "Was zeigt die Raman-Spektroskopie von kohlenstoffhaltigem Material assoziiert mit Anchiornis-Exemplaren über Erhaltung ursprünglicher biochemischer Verbindungen versus diagenetischer Alterationsprodukte?",
          nl: "Wat onthult Raman spectroscopie van koolstofhoudend materiaal geassocieerd met Anchiornis specimens over behoud van originele biochemische verbindingen versus diagenetische alteratie producten?"
        },
        options: [
          { en: "Spectral signatures show preserved melanin with distinct eumelanin and phaeomelanin bands, enabling reconstruction of original feather coloration patterns independent of mineralization artifacts", es: "Firmas espectrales muestran melanina preservada con bandas distintas de eumelanina y feomelanina, permitiendo reconstrucción de patrones de coloración de plumas originales independientes de artefactos de mineralización", de: "Spektrale Signaturen zeigen erhaltenes Melanin mit deutlichen Eumelanin- und Phäomelanin-Banden, was Rekonstruktion ursprünglicher Federfarb-Muster unabhängig von Mineralisierungs-Artefakten ermöglicht", nl: "Spectrale handtekeningen tonen bewaard melanine met verschillende eumelanine en phaeomelanine banden, wat reconstructie van originele veer kleurpatronen mogelijk maakt onafhankelijk van mineralisatie artefacten" },
          { en: "All carbonaceous material is diagenetic contamination", es: "Todo material carbonáceo es contaminación diagenética", de: "Alles kohlenstoffhaltige Material ist diagenetische Kontamination", nl: "Al het koolstofhoudende materiaal is diagenetische verontreiniging" },
          { en: "Raman spectroscopy cannot identify organic compounds", es: "Espectroscopía Raman no puede identificar compuestos orgánicos", de: "Raman-Spektroskopie kann organische Verbindungen nicht identifizieren", nl: "Raman spectroscopie kan organische verbindingen niet identificeren" },
          { en: "Feather color cannot be determined from fossils", es: "Color de pluma no puede determinarse de fósiles", de: "Federfarbe kann nicht aus Fossilien bestimmt werden", nl: "Veer kleur kan niet worden bepaald uit fossielen" }
        ],
        correct: 0,
        explanation: {
          en: "Raman spectroscopy identifies molecular bonds through vibrational frequencies. Different melanin types (eumelanin for black/brown, phaeomelanin for reddish colors) have diagnostic spectral signatures. Combined with melanosome morphology from electron microscopy, this enables accurate reconstruction of original plumage coloration in feathered dinosaurs, revolutionizing understanding of their visual appearance.",
          es: "Espectroscopía Raman identifica enlaces moleculares através de frecuencias vibracionales. Diferentes tipos de melanina (eumelanina para negro/marrón, feomelanina para colores rojizos) tienen firmas espectrales diagnósticas. Combinado con morfología de melanosomas de microscopía electrónica, esto permite reconstrucción precisa de coloración de plumaje original en dinosaurios emplumados, revolucionando comprensión de su apariencia visual.",
          de: "Raman-Spektroskopie identifiziert molekulare Bindungen durch Schwingungsfrequenzen. Verschiedene Melanin-Typen (Eumelanin für Schwarz/Braun, Phäomelanin für rötliche Farben) haben diagnostische spektrale Signaturen. Kombiniert mit Melanosomen-Morphologie aus Elektronenmikroskopie ermöglicht dies genaue Rekonstruktion ursprünglicher Gefiederfarben bei gefiederten Dinosauriern und revolutioniert das Verständnis ihres visuellen Erscheinungsbilds.",
          nl: "Raman spectroscopie identificeert moleculaire bindingen door vibratie frequenties. Verschillende melanine types (eumelanine voor zwart/bruin, phaeomelanine voor roodachtige kleuren) hebben diagnostische spectrale handtekeningen. Gecombineerd met melanosoom morfologie van elektronen microscopie, maakt dit nauwkeurige reconstructie van originele vederkleuring mogelijk bij gevederde dinosaurussen, wat begrip van hun visuele verschijning revolutioneert."
        }
      },
      {
        question: {
          en: "How does U-Pb radiometric dating of zircons from volcanic ash layers bracketing the Morrison Formation refine temporal constraints on Late Jurassic dinosaur faunal turnover events?",
          es: "¿Cómo la datación radiométrica U-Pb de circones de capas de ceniza volcánica que enmarcan la Formación Morrison refinan restricciones temporales sobre eventos de recambio faunístico de dinosaurios del Jurásico Tardío?",
          de: "Wie verfeinern U-Pb-radiometrische Datierungen von Zirkonen aus vulkanischen Ascheschichten, die die Morrison-Formation einrahmen, zeitliche Einschränkungen für Faunen-Turnover-Ereignisse bei Dinosauriern des Späten Jura?",
          nl: "Hoe verfijnt U-Pb radiometrische datering van zirkonen uit vulkanische aslagen die de Morrison Formatie omkaderen temporele beperkingen op Laat Jura dinosaurus faunale turnover gebeurtenissen?"
        },
        options: [
          { en: "High-precision CA-TIMS analysis yields ages of 150.8±0.5 Ma for lower Morrison and 148.1±0.4 Ma for upper Morrison, constraining rapid 2.7 million year dinosaur community replacement during climate shift", es: "Análisis CA-TIMS de alta precisión produce edades de 150.8±0.5 Ma para Morrison inferior y 148.1±0.4 Ma para Morrison superior, restringiendo reemplazo rápido de comunidad de dinosaurios de 2.7 millones de años durante cambio climático", de: "Hochpräzisions-CA-TIMS-Analyse ergibt Alter von 150,8±0,5 Ma für unteren Morrison und 148,1±0,4 Ma für oberen Morrison, was schnellen 2,7 Millionen Jahre Dinosaurier-Gemeinschafts-Ersatz während Klimawandel eingrenzt", nl: "Hoge-precisie CA-TIMS analyse levert leeftijden op van 150.8±0.5 Ma voor onderste Morrison en 148.1±0.4 Ma voor bovenste Morrison, wat snelle 2.7 miljoen jaar dinosaurus gemeenschap vervanging tijdens klimaatverandering beperkt" },
          { en: "Morrison Formation spans 50 million years", es: "Formación Morrison abarca 50 millones de años", de: "Morrison-Formation erstreckt sich über 50 Millionen Jahre", nl: "Morrison Formatie beslaat 50 miljoen jaar" },
          { en: "Zircon dating cannot achieve million-year precision", es: "Datación de circón no puede lograr precisión de millón de años", de: "Zirkon-Datierung kann keine Millionen-Jahre-Präzision erreichen", nl: "Zirkoon datering kan geen miljoen-jaar precisie bereiken" },
          { en: "Faunal changes occurred randomly without temporal pattern", es: "Cambios faunísticos ocurrieron aleatoriamente sin patrón temporal", de: "Faunen-Änderungen traten zufällig ohne zeitliches Muster auf", nl: "Faunale veranderingen vonden willekeurig plaats zonder temporeel patroon" }
        ],
        correct: 0,
        explanation: {
          en: "U-Pb dating of zircon crystals in volcanic ash beds (Chemical Abrasion-Thermal Ionization Mass Spectrometry) provides highly precise absolute ages. Multiple dated ash layers bracket fossil-bearing horizons, establishing tight temporal constraints. This reveals Morrison Formation dinosaur communities underwent rapid turnover over just a few million years, correlating with documented climate shifts from humid to semi-arid conditions.",
          es: "Datación U-Pb de cristales de circón en lechos de ceniza volcánica (Espectrometría de Masas de Ionización Térmica-Abrasión Química) proporciona edades absolutas altamente precisas. Múltiples capas de ceniza datadas enmarcan horizontes fosilíferos, estableciendo restricciones temporales ajustadas. Esto revela que comunidades de dinosaurios de la Formación Morrison experimentaron recambio rápido en solo unos pocos millones de años, correlacionando con cambios climáticos documentados de condiciones húmedas a semiáridas.",
          de: "U-Pb-Datierung von Zirkon-Kristallen in vulkanischen Aschebetten (Chemische Abrasion-Thermische Ionisations-Massenspektrometrie) liefert hochpräzise absolute Alter. Mehrere datierte Ascheschichten umrahmen fossilführende Horizonte und etablieren enge zeitliche Einschränkungen. Dies zeigt, dass Morrison-Formation-Dinosaurier-Gemeinschaften schnellen Umsatz über nur wenige Millionen Jahre erfuhren, korrelierend mit dokumentierten Klimaverschiebungen von feuchten zu semi-ariden Bedingungen.",
          nl: "U-Pb datering van zirkoon kristallen in vulkanische aslagen (Chemische Abrasie-Thermische Ionisatie Massacpectrometrie) levert zeer precieze absolute leeftijden. Meerdere gedateerde aslagen omkaderen fossiel-dragende horizonten, wat strakke temporele beperkingen vastlegt. Dit onthult dat Morrison Formatie dinosaurus gemeenschappen snelle turnover ondergingen over slechts enkele miljoen jaar, wat correleert met gedocumenteerde klimaatveranderingen van vochtige naar semi-aride condities."
        }
      },
      {
        question: {
          en: "What does osteohistological analysis of growth marks (LAGs) in Allosaurus femora reveal about growth rates, age at sexual maturity, and maximum longevity in large theropods?",
          es: "¿Qué revela el análisis osteohistológico de marcas de crecimiento (LAGs) en fémures de Allosaurus sobre tasas de crecimiento, edad de madurez sexual y longevidad máxima en terópodos grandes?",
          de: "Was zeigt osteohistologische Analyse von Wachstumsmarken (LAGs) in Allosaurus-Femora über Wachstumsraten, Alter bei sexueller Reife und maximale Langlebigkeit bei großen Theropoden?",
          nl: "Wat onthult osteohistologische analyse van groeimarkeringen (LAGs) in Allosaurus femora over groeisnelheden, leeftijd bij seksuele rijpheid en maximale levensduur in grote theropoden?"
        },
        options: [
          { en: "LAG counting indicates rapid growth to 70% adult size by age 10-12 years, sexual maturity at 15 years with asymptotic growth, and maximum lifespan of 22-28 years based on external fundamental system formation", es: "Conteo de LAG indica crecimiento rápido a 70% tamaño adulto a edad 10-12 años, madurez sexual a 15 años con crecimiento asintótico, y vida máxima de 22-28 años basado en formación de sistema fundamental externo", de: "LAG-Zählung zeigt schnelles Wachstum auf 70% Adultgröße im Alter von 10-12 Jahren, sexuelle Reife mit 15 Jahren mit asymptotischem Wachstum und maximale Lebensspanne von 22-28 Jahren basierend auf externem fundamentalem Systembildung", nl: "LAG telling duidt op snelle groei tot 70% volwassen grootte op leeftijd 10-12 jaar, seksuele rijpheid op 15 jaar met asymptotische groei, en maximale levensduur van 22-28 jaar gebaseerd op extern fundamenteel systeem formatie" },
          { en: "Growth continued linearly throughout life with no maturation", es: "Crecimiento continuó linealmente durante toda la vida sin maduración", de: "Wachstum setzte sich linear während des gesamten Lebens ohne Reifung fort", nl: "Groei ging lineair door gedurende het hele leven zonder volwassenwording" },
          { en: "LAGs cannot be used to determine age in dinosaurs", es: "LAGs no pueden usarse para determinar edad en dinosaurios", de: "LAGs können nicht zur Altersbestimmung bei Dinosauriern verwendet werden", nl: "LAGs kunnen niet worden gebruikt om leeftijd in dinosaurussen te bepalen" },
          { en: "All theropods lived less than 5 years", es: "Todos los terópodos vivieron menos de 5 años", de: "Alle Theropoden lebten weniger als 5 Jahre", nl: "Alle theropoden leefden minder dan 5 jaar" }
        ],
        correct: 0,
        explanation: {
          en: "Lines of arrested growth (LAGs) are cyclical growth marks in bone, typically annual in dinosaurs. Counting LAGs provides minimum age estimates. Growth curve analysis shows large theropods like Allosaurus had sigmoidal growth with rapid adolescent growth spurts, reaching sexual maturity before maximum size, similar to modern crocodilians and birds but with faster growth rates suggesting elevated metabolism.",
          es: "Líneas de crecimiento arrestado (LAGs) son marcas de crecimiento cíclicas en hueso, típicamente anuales en dinosaurios. Contar LAGs proporciona estimaciones de edad mínima. Análisis de curva de crecimiento muestra que terópodos grandes como Allosaurus tenían crecimiento sigmoidal con rápidos brotes de crecimiento adolescente, alcanzando madurez sexual antes del tamaño máximo, similar a cocodrilos y aves modernos pero con tasas de crecimiento más rápidas sugiriendo metabolismo elevado.",
          de: "Linien arrestierten Wachstums (LAGs) sind zyklische Wachstumsmarken im Knochen, typischerweise jährlich bei Dinosauriern. LAG-Zählung liefert Mindest-Altersschätzungen. Wachstumskurven-Analyse zeigt, dass große Theropoden wie Allosaurus sigmoidales Wachstum mit schnellen jugendlichen Wachstumsschüben hatten, sexuelle Reife vor maximaler Größe erreichten, ähnlich modernen Krokodilen und Vögeln, aber mit schnelleren Wachstumsraten, die erhöhten Stoffwechsel nahelegen.",
          nl: "Lijnen van gearresteerde groei (LAGs) zijn cyclische groeimarkeringen in bot, typisch jaarlijks in dinosaurussen. LAG telling levert minimale leeftijd schattingen. Groeicurve analyse toont aan dat grote theropoden zoals Allosaurus sigmoidale groei hadden met snelle adolescente groeispurts, seksuele rijpheid bereikend voor maximale grootte, vergelijkbaar met moderne krokodillen en vogels maar met snellere groeisnelheden wat verhoogd metabolisme suggereert."
        }
      },
      {
        question: {
          en: "How does micro-CT scanning combined with contrast-enhanced imaging reveal neural anatomy in exceptionally preserved Archaeopteryx specimens, constraining hypotheses about sensory capabilities?",
          es: "¿Cómo el escaneo micro-CT combinado con imágenes mejoradas por contraste revela anatomía neural en especímenes excepcionalmente preservados de Archaeopteryx, restringiendo hipótesis sobre capacidades sensoriales?",
          de: "Wie enthüllt Mikro-CT-Scanning kombiniert mit kontrastverstärkter Bildgebung neuronale Anatomie in außergewöhnlich erhaltenen Archaeopteryx-Exemplaren und grenzt Hypothesen über sensorische Fähigkeiten ein?",
          nl: "Hoe onthult micro-CT scannen gecombineerd met contrast-versterkte beeldvorming neurale anatomie in uitzonderlijk bewaarde Archaeopteryx specimens, wat hypothesen over sensorische capaciteiten beperkt?"
        },
        options: [
          { en: "Endocranial reconstruction shows enlarged optic lobes and cerebellum with floccular structure, indicating advanced visual processing and equilibrium control necessary for powered flight", es: "Reconstrucción endocraneal muestra lóbulos ópticos y cerebelo agrandados con estructura floculosa, indicando procesamiento visual avanzado y control de equilibrio necesario para vuelo motorizado", de: "Endokranielle Rekonstruktion zeigt vergrößerte Sehlappen und Kleinhirn mit Flocculus-Struktur, was auf fortgeschrittene visuelle Verarbeitung und Gleichgewichtskontrolle hinweist, die für motorisierten Flug notwendig sind", nl: "Endocraniale reconstructie toont vergrote optische lobben en cerebellum met flocculaire structuur, wat geavanceerde visuele verwerking en evenwichtscontrole aanduidt die nodig zijn voor aangedreven vlucht" },
          { en: "Brain structure was identical to non-avian theropods", es: "Estructura cerebral era idéntica a terópodos no avianos", de: "Hirnstruktur war identisch mit nicht-avianen Theropoden", nl: "Hersenstructuur was identiek aan niet-vogel theropoden" },
          { en: "Micro-CT cannot reveal soft tissue anatomy", es: "Micro-CT no puede revelar anatomía de tejido blando", de: "Mikro-CT kann Weichteil-Anatomie nicht offenbaren", nl: "Micro-CT kan zacht weefsel anatomie niet onthullen" },
          { en: "Neural features provide no information about behavior", es: "Características neurales no proporcionan información sobre comportamiento", de: "Neuronale Merkmale liefern keine Informationen über Verhalten", nl: "Neurale kenmerken bieden geen informatie over gedrag" }
        ],
        correct: 0,
        explanation: {
          en: "Micro-CT creates high-resolution 3D scans revealing internal structures. Endocranial casts show brain morphology. Enlarged optic lobes indicate enhanced vision, while cerebellar flocculi coordinate eye-head movements and spatial orientation during flight. These neurological features in Archaeopteryx demonstrate the neural prerequisites for active flight behavior existed in this transitional form.",
          es: "Micro-CT crea escaneos 3D de alta resolución revelando estructuras internas. Moldes endocraneales muestran morfología cerebral. Lóbulos ópticos agrandados indican visión mejorada, mientras flóculos cerebelares coordinan movimientos ojo-cabeza y orientación espacial durante vuelo. Estas características neurológicas en Archaeopteryx demuestran que los prerequisitos neurales para comportamiento de vuelo activo existían en esta forma transicional.",
          de: "Mikro-CT erstellt hochauflösende 3D-Scans, die interne Strukturen offenbaren. Endokranielle Abgüsse zeigen Hirnmorphologie. Vergrößerte Sehlappen deuten auf verbesserte Sicht hin, während zerebelläre Flocculi Auge-Kopf-Bewegungen und räumliche Orientierung während des Fluges koordinieren. Diese neurologischen Merkmale in Archaeopteryx demonstrieren, dass die neurologischen Voraussetzungen für aktives Flugverhalten in dieser Übergangsform existierten.",
          nl: "Micro-CT creëert hoge-resolutie 3D scans die interne structuren onthullen. Endocraniale afgietsels tonen hersenmorfologie. Vergrote optische lobben duiden op verbeterd zicht, terwijl cerebellaire flocculi oog-hoofd bewegingen en ruimtelijke oriëntatie tijdens vlucht coördineren. Deze neurologische kenmerken in Archaeopteryx demonstreren dat de neurale vereisten voor actief vlieggedrag bestonden in deze overgangsvorm."
        }
      },
      {
        question: {
          en: "What does phylogenetic analysis using maximum likelihood and Bayesian inference methods with morphological and molecular datasets reveal about the evolutionary position of Haplocheirus and alvarezsauroid origins?",
          es: "¿Qué revela el análisis filogenético usando métodos de máxima verosimilitud e inferencia bayesiana con conjuntos de datos morfológicos y moleculares sobre la posición evolutiva de Haplocheirus y orígenes de alvarezsauroides?",
          de: "Was zeigt phylogenetische Analyse mit Maximum-Likelihood- und Bayesschen Inferenzmethoden mit morphologischen und molekularen Datensätzen über die evolutionäre Position von Haplocheirus und Alvarezsauroid-Ursprünge?",
          nl: "Wat onthult fylogenetische analyse met maximum likelihood en Bayesiaanse inferentie methoden met morfologische en moleculaire datasets over de evolutionaire positie van Haplocheirus en alvarezsauroid oorsprong?"
        },
        options: [
          { en: "Parsimony and Bayesian analyses place alvarezsauroids as basal manuraptorans diverging in Middle Jurassic, with Haplocheirus showing mosaic features including primitive forelimb structure predating extreme specialization", es: "Análisis de parsimonia y bayesiano ubican alvarezsauroides como manuraptorans basales divergiendo en Jurásico Medio, con Haplocheirus mostrando características mosaico incluyendo estructura primitiva de miembro anterior anterior a especialización extrema", de: "Parsimonie- und Bayessche Analysen platzieren Alvarezsauroiden als basale Manuraptoren, die im Mittleren Jura divergieren, wobei Haplocheirus Mosaik-Merkmale zeigt einschließlich primitiver Vordergliedmaßen-Struktur vor extremer Spezialisierung", nl: "Parsimony en Bayesiaanse analyses plaatsen alvarezsauroiden als basale manuraptoren die divergeren in Midden Jura, met Haplocheirus die mozaïek kenmerken toont inclusief primitieve voorpoot structuur voorafgaand aan extreme specialisatie" },
          { en: "Alvarezsauroids are ornithischians unrelated to theropods", es: "Alvarezsauroides son ornitisquios no relacionados con terópodos", de: "Alvarezsauroiden sind Ornithischier, die nicht mit Theropoden verwandt sind", nl: "Alvarezsauroiden zijn ornithischiërs niet gerelateerd aan theropoden" },
          { en: "Phylogenetic methods cannot resolve dinosaur relationships", es: "Métodos filogenéticos no pueden resolver relaciones de dinosaurios", de: "Phylogenetische Methoden können Dinosaurier-Beziehungen nicht auflösen", nl: "Fylogenetische methoden kunnen dinosaurus relaties niet oplossen" },
          { en: "All alvarezsauroids appeared simultaneously in Late Cretaceous", es: "Todos los alvarezsauroides aparecieron simultáneamente en Cretácico Tardío", de: "Alle Alvarezsauroiden erschienen gleichzeitig in der späten Kreidezeit", nl: "Alle alvarezsauroiden verschenen gelijktijdig in Laat Krijt" }
        ],
        correct: 0,
        explanation: {
          en: "Phylogenetic analysis uses computational algorithms to determine evolutionary relationships from character data. Maximum likelihood and Bayesian methods assess probability of different tree topologies. Multiple analyses consistently place alvarezsauroids within Maniraptora. Haplocheirus from the Middle-Late Jurassic shows alvarezsauroids originated earlier than previously thought, with gradual evolution toward the highly specialized insectivorous adaptations seen in later forms.",
          es: "Análisis filogenético usa algoritmos computacionales para determinar relaciones evolutivas de datos de caracteres. Métodos de máxima verosimilitud y bayesianos evalúan probabilidad de diferentes topologías de árboles. Múltiples análisis ubican consistentemente alvarezsauroides dentro de Maniraptora. Haplocheirus del Jurásico Medio-Tardío muestra que alvarezsauroides se originaron antes de lo pensado, con evolución gradual hacia adaptaciones insectívoras altamente especializadas vistas en formas posteriores.",
          de: "Phylogenetische Analyse verwendet Rechenalgorithmen, um evolutionäre Beziehungen aus Merkmalsdaten zu bestimmen. Maximum-Likelihood- und Bayessche Methoden bewerten Wahrscheinlichkeit verschiedener Baumtopologien. Mehrere Analysen platzieren Alvarezsauroiden konsistent innerhalb Maniraptora. Haplocheirus aus dem Mittleren-Späten Jura zeigt, dass Alvarezsauroiden früher entstanden als bisher angenommen, mit gradueller Evolution zu den hochspezialisierten insektivoren Anpassungen späterer Formen.",
          nl: "Fylogenetische analyse gebruikt computationele algoritmen om evolutionaire relaties te bepalen uit karakter data. Maximum likelihood en Bayesiaanse methoden beoordelen waarschijnlijkheid van verschillende boom topologieën. Meerdere analyses plaatsen alvarezsauroiden consistent binnen Maniraptora. Haplocheirus uit het Midden-Laat Jura toont aan dat alvarezsauroiden eerder ontstonden dan eerder gedacht, met geleidelijke evolutie naar de zeer gespecialiseerde insectivore aanpassingen gezien in latere vormen."
        }
      },
      {
        question: {
          en: "How does taphonomic analysis using sedimentological and taphofacies approaches constrain interpretations of mass mortality assemblages like the Cleveland-Lloyd Quarry Allosaurus accumulation?",
          es: "¿Cómo el análisis tafonómico usando enfoques sedimentológicos y de tafofacies restringe interpretaciones de ensamblajes de mortalidad masiva como la acumulación de Allosaurus de Cleveland-Lloyd Quarry?",
          de: "Wie grenzen taphonomische Analysen mit sedimentologischen und Taphofazies-Ansätzen Interpretationen von Massen-Mortalitäts-Versammlungen wie der Cleveland-Lloyd-Quarry-Allosaurus-Ansammlung ein?",
          nl: "Hoe beperkt tafonomische analyse met sedimentologische en taphofacies benaderingen interpretaties van massa mortaliteit verzamelingen zoals de Cleveland-Lloyd Quarry Allosaurus accumulatie?"
        },
        options: [
          { en: "Disarticulation patterns, bone orientation data, and microfacies analysis indicate episodic drought-related deaths at ephemeral water source with predator trap dynamics concentrating theropods over multiple seasons", es: "Patrones de desarticulación, datos de orientación de huesos y análisis de microfacies indican muertes episódicas relacionadas con sequía en fuente de agua efímera con dinámicas de trampa de depredadores concentrando terópodos durante múltiples temporadas", de: "Disartikulationsmuster, Knochenorientierungs-Daten und Mikrofazies-Analyse deuten auf episodische dürrebedingte Tode an ephemerer Wasserquelle mit Raubtier-Fallen-Dynamiken hin, die Theropoden über mehrere Jahreszeiten konzentrierten", nl: "Disarticulatie patronen, bot oriëntatie data en microfacies analyse duiden op episodische droogte-gerelateerde sterfgevallen bij efemere waterbron met roofdier val dynamiek die theropoden concentreerde over meerdere seizoenen" },
          { en: "All bones were transported from distant locations", es: "Todos los huesos fueron transportados desde ubicaciones distantes", de: "Alle Knochen wurden von entfernten Standorten transportiert", nl: "Alle botten werden getransporteerd van verre locaties" },
          { en: "Taphonomic analysis cannot distinguish accumulation mechanisms", es: "Análisis tafonómico no puede distinguir mecanismos de acumulación", de: "Taphonomische Analyse kann Akkumulationsmechanismen nicht unterscheiden", nl: "Tafonomische analyse kan accumulatie mechanismen niet onderscheiden" },
          { en: "The assemblage formed instantaneously in single event", es: "El ensamblaje se formó instantáneamente en un solo evento", de: "Die Versammlung bildete sich instantan in einem einzigen Ereignis", nl: "De verzameling vormde zich onmiddellijk in een enkele gebeurtenis" }
        ],
        correct: 0,
        explanation: {
          en: "Taphonomy studies post-mortem processes affecting fossil preservation. Detailed analysis of bone weathering stages, articulation states, size sorting, preferred orientations, and associated sedimentary structures distinguishes different accumulation mechanisms. Cleveland-Lloyd shows evidence of attritional accumulation over time at a drought-stressed water hole that attracted and trapped predators, explaining the unusual theropod-dominated assemblage.",
          es: "Tafonomía estudia procesos post-mortem que afectan preservación fósil. Análisis detallado de etapas de meteorización ósea, estados de articulación, clasificación por tamaño, orientaciones preferidas y estructuras sedimentarias asociadas distingue diferentes mecanismos de acumulación. Cleveland-Lloyd muestra evidencia de acumulación por desgaste a lo largo del tiempo en un pozo de agua estresado por sequía que atrajo y atrapó depredadores, explicando el inusual ensamblaje dominado por terópodos.",
          de: "Taphonomie untersucht post-mortem Prozesse, die fossile Erhaltung beeinflussen. Detaillierte Analyse von Knochenverwitterungs-Stadien, Artikulationszuständen, Größensortierung, bevorzugten Orientierungen und assoziierten sedimentären Strukturen unterscheidet verschiedene Akkumulationsmechanismen. Cleveland-Lloyd zeigt Beweise für Abnutzungs-Akkumulation über Zeit an einem dürregestressten Wasserloch, das Raubtiere anzog und fing, was die ungewöhnliche von Theropoden dominierte Versammlung erklärt.",
          nl: "Tafonomie bestudeert post-mortem processen die fossiel behoud beïnvloeden. Gedetailleerde analyse van bot verwerings stadia, articulatie toestanden, grootte sortering, geprefereerde oriëntaties en geassocieerde sedimentaire structuren onderscheidt verschillende accumulatie mechanismen. Cleveland-Lloyd toont bewijs van attritionale accumulatie over tijd bij een droogte-gestrest watergat dat roofdieren aantrok en vasthield, wat de ongebruikelijke theropode-gedomineerde verzameling verklaart."
        }
      },
      {
        question: {
          en: "What does quantitative paleobiogeographic analysis using dispersal-vicariance analysis (DIVA) reveal about Morrison Formation dinosaur distribution patterns and their relationship to Jurassic continental configurations?",
          es: "¿Qué revela el análisis paleobiogeográfico cuantitativo usando análisis de dispersión-vicarianza (DIVA) sobre patrones de distribución de dinosaurios de la Formación Morrison y su relación con configuraciones continentales del Jurásico?",
          de: "Was zeigt quantitative paläobiogeographische Analyse mit Dispersions-Vikarianz-Analyse (DIVA) über Morrison-Formation-Dinosaurier-Verteilungsmuster und ihre Beziehung zu jurassischen Kontinentalkonfigurationen?",
          nl: "Wat onthult kwantitatieve paleobiogeografische analyse met behulp van dispersie-vicariantie analyse (DIVA) over Morrison Formatie dinosaurus distributie patronen en hun relatie tot Jura continentale configuraties?"
        },
        options: [
          { en: "DIVA optimization indicates Morrison taxa represent endemic North American radiation with limited faunal exchange across Tethys, consistent with geographic barriers despite Pangaean proximity during Kimmeridgian-Tithonian", es: "Optimización DIVA indica que taxones de Morrison representan radiación endémica de América del Norte con intercambio faunístico limitado a través de Tetis, consistente con barreras geográficas a pesar de proximidad de Pangea durante Kimmeridgiense-Titoniense", de: "DIVA-Optimierung zeigt, dass Morrison-Taxa endemische nordamerikanische Radiation mit begrenztem faunistischem Austausch über Tethys repräsentieren, konsistent mit geographischen Barrieren trotz Pangaea-Nähe während Kimmeridgium-Tithonium", nl: "DIVA optimalisatie duidt aan dat Morrison taxa endemische Noord-Amerikaanse radiatie vertegenwoordigen met beperkte faunale uitwisseling over Tethys, consistent met geografische barrières ondanks Pangaeïsche nabijheid tijdens Kimmeridgian-Tithonian" },
          { en: "Morrison dinosaurs show identical distribution to Asian faunas", es: "Dinosaurios de Morrison muestran distribución idéntica a faunas asiáticas", de: "Morrison-Dinosaurier zeigen identische Verteilung zu asiatischen Faunen", nl: "Morrison dinosaurussen tonen identieke distributie aan Aziatische fauna's" },
          { en: "Paleobiogeography cannot be analyzed quantitatively", es: "Paleobiogeografía no puede analizarse cuantitativamente", de: "Paläobiogeographie kann nicht quantitativ analysiert werden", nl: "Paleobiogeografie kan niet kwantitatief worden geanalyseerd" },
          { en: "Continental position had no effect on dinosaur distribution", es: "Posición continental no tuvo efecto en distribución de dinosaurios", de: "Kontinentale Position hatte keinen Effekt auf Dinosaurier-Verteilung", nl: "Continentale positie had geen effect op dinosaurus distributie" }
        ],
        correct: 0,
        explanation: {
          en: "DIVA is a parsimony-based method optimizing dispersal and vicariance events on phylogenies overlaid with geographic distributions. Analysis shows Morrison Formation dinosaurs form a distinctive fauna with endemic taxa, despite living during the Pangaean supercontinent. This indicates climatic and topographic barriers limited faunal interchange, with North America's inland sea and arid zones creating biogeographic provinciality within the supercontinent.",
          es: "DIVA es un método basado en parsimonia que optimiza eventos de dispersión y vicarianza en filogenias superpuestas con distribuciones geográficas. El análisis muestra que dinosaurios de la Formación Morrison forman una fauna distintiva con taxones endémicos, a pesar de vivir durante el supercontinente Pangea. Esto indica que barreras climáticas y topográficas limitaron intercambio faunístico, con mar interior de América del Norte y zonas áridas creando provincialidad biogeográfica dentro del supercontinente.",
          de: "DIVA ist eine parsimonie-basierte Methode, die Dispersions- und Vikarianz-Ereignisse auf Phylogenien optimiert, die mit geographischen Verteilungen überlagert sind. Analyse zeigt, dass Morrison-Formation-Dinosaurier eine unterscheidbare Fauna mit endemischen Taxa bilden, trotz Leben während des Pangaea-Superkontinents. Dies deutet darauf hin, dass klimatische und topographische Barrieren faunistischen Austausch begrenzten, wobei Nordamerikas Binnenmeer und aride Zonen biogeographische Provinzialität innerhalb des Superkontinents schufen.",
          nl: "DIVA is een parsimony-gebaseerde methode die dispersie en vicariantie gebeurtenissen optimaliseert op fylogenieën die bedekt zijn met geografische distributies. Analyse toont aan dat Morrison Formatie dinosaurussen een onderscheidende fauna vormen met endemische taxa, ondanks dat ze leefden tijdens het Pangaeïsche supercontinent. Dit duidt aan dat klimatologische en topografische barrières faunale uitwisseling beperkten, met Noord-Amerika's binnenlandse zee en aride zones die biogeografische provincialiteit binnen het supercontinent creëerden."
        }
      },
      {
        question: {
          en: "How does application of neutral theory and metabolic scaling laws to Morrison Formation dinosaur community structure constrain ecological models of species coexistence and niche partitioning?",
          es: "¿Cómo la aplicación de teoría neutral y leyes de escalamiento metabólico a estructura de comunidad de dinosaurios de la Formación Morrison restringe modelos ecológicos de coexistencia de especies y partición de nicho?",
          de: "Wie grenzt die Anwendung neutraler Theorie und metabolischer Skalierungsgesetze auf Morrison-Formation-Dinosaurier-Gemeinschaftsstruktur ökologische Modelle von Arten-Koexistenz und Nischen-Partitionierung ein?",
          nl: "Hoe beperkt toepassing van neutrale theorie en metabolische schaalwetten op Morrison Formatie dinosaurus gemeenschap structuur ecologische modellen van soorten co-existentie en niche partitionering?"
        },
        options: [
          { en: "Body size distribution deviates significantly from neutral predictions, with size-frequency gaps indicating metabolically-structured guilds and ontogenetic niche shifts reducing interspecific competition through allometric scaling", es: "Distribución de tamaño corporal se desvía significativamente de predicciones neutrales, con brechas de frecuencia de tamaño indicando gremios estructurados metabólicamente y cambios de nicho ontogenéticos reduciendo competencia interespecífica através de escalamiento alométrico", de: "Körpergrößen-Verteilung weicht signifikant von neutralen Vorhersagen ab, wobei Größen-Frequenz-Lücken metabolisch strukturierte Gilden und ontogenetische Nischen-Verschiebungen anzeigen, die interspezifische Konkurrenz durch allometrische Skalierung reduzieren", nl: "Lichaamsgrootte distributie wijkt significant af van neutrale voorspellingen, met grootte-frequentie hiaten die metabolisch-gestructureerde gilden en ontogenetische niche verschuivingen aangeven die interspecifieke competitie verminderen door allometrische schaling" },
          { en: "Community structure perfectly matches neutral model predictions", es: "Estructura comunitaria coincide perfectamente con predicciones de modelo neutral", de: "Gemeinschaftsstruktur entspricht perfekt neutralen Modellvorhersagen", nl: "Gemeenschap structuur komt perfect overeen met neutrale model voorspellingen" },
          { en: "Metabolic scaling has no ecological relevance", es: "Escalamiento metabólico no tiene relevancia ecológica", de: "Metabolische Skalierung hat keine ökologische Relevanz", nl: "Metabolische schaling heeft geen ecologische relevantie" },
          { en: "Species coexistence occurred randomly without niche partitioning", es: "Coexistencia de especies ocurrió aleatoriamente sin partición de nicho", de: "Arten-Koexistenz trat zufällig ohne Nischen-Partitionierung auf", nl: "Soorten co-existentie vond willekeurig plaats zonder niche partitionering" }
        ],
        correct: 0,
        explanation: {
          en: "Neutral theory predicts community structure based on random processes, while niche theory emphasizes resource partitioning. Metabolic scaling laws relate body size to energy requirements. Morrison Formation shows non-random size distributions with gaps between size classes, suggesting species were sorted by metabolic requirements and ecological roles. Juveniles occupied different size classes than adults, reducing competition and enabling multiple large predators to coexist.",
          es: "Teoría neutral predice estructura comunitaria basada en procesos aleatorios, mientras teoría de nicho enfatiza partición de recursos. Leyes de escalamiento metabólico relacionan tamaño corporal con requerimientos energéticos. Formación Morrison muestra distribuciones de tamaño no aleatorias con brechas entre clases de tamaño, sugiriendo que especies fueron ordenadas por requerimientos metabólicos y roles ecológicos. Juveniles ocuparon clases de tamaño diferentes que adultos, reduciendo competencia y permitiendo que múltiples depredadores grandes coexistieran.",
          de: "Neutrale Theorie sagt Gemeinschaftsstruktur basierend auf zufälligen Prozessen vorher, während Nischentheorie Ressourcen-Partitionierung betont. Metabolische Skalierungsgesetze beziehen Körpergröße auf Energieanforderungen. Morrison-Formation zeigt nicht-zufällige Größenverteilungen mit Lücken zwischen Größenklassen, was darauf hindeutet, dass Arten nach metabolischen Anforderungen und ökologischen Rollen sortiert wurden. Jungtiere besetzten andere Größenklassen als Adulte, wodurch Konkurrenz reduziert und mehreren großen Raubtieren Koexistenz ermöglicht wurde.",
          nl: "Neutrale theorie voorspelt gemeenschap structuur gebaseerd op willekeurige processen, terwijl niche theorie benadrukt resource partitionering. Metabolische schaalwetten relateren lichaamsgrootte aan energie vereisten. Morrison Formatie toont niet-willekeurige grootte distributies met hiaten tussen grootte klassen, wat suggereert dat soorten gesorteerd werden door metabolische vereisten en ecologische rollen. Juvenielen bezetten verschillende grootte klassen dan volwassenen, wat competitie verminderde en meerdere grote roofdieren in staat stelde te co-existeren."
        }
      },
      {
        question: {
          en: "What does integrative analysis combining ichnological, skeletal, and soft tissue evidence reveal about the biomechanical feasibility of tripodal resting posture in large Morrison Formation theropods?",
          es: "¿Qué revela el análisis integrativo combinando evidencia icnológica, esquelética y de tejido blando sobre la viabilidad biomecánica de postura de descanso tripodal en terópodos grandes de la Formación Morrison?",
          de: "Was zeigt integrative Analyse, die ichnologische, skelettale und Weichteil-Beweise kombiniert, über die biomechanische Machbarkeit tripodaler Ruhehaltung bei großen Morrison-Formation-Theropoden?",
          nl: "Wat onthult integratieve analyse die ichnologisch, skeletaal en zacht weefsel bewijs combineert over de biomechanische haalbaarheid van tripodale rusthouding in grote Morrison Formatie theropoden?"
        },
        options: [
          { en: "Caudofemoral muscle reconstruction, pubic boot morphology, and rare sitting traces indicate theropods could adopt tripodal posture with tail and ischial region supporting body weight during rest, reducing metabolic costs", es: "Reconstrucción muscular caudofemoral, morfología de bota púbica y rastros de sentado raros indican que terópodos podían adoptar postura tripodal con cola y región isquial soportando peso corporal durante descanso, reduciendo costos metabólicos", de: "Caudofemorale Muskel-Rekonstruktion, Schambeinstiefel-Morphologie und seltene Sitz-Spuren deuten darauf hin, dass Theropoden tripodale Haltung mit Schwanz und Ischialregion, die Körpergewicht während Ruhe unterstützen, einnehmen konnten, wodurch metabolische Kosten reduziert wurden", nl: "Caudofemorale spier reconstructie, pubische laars morfologie en zeldzame zit sporen duiden aan dat theropoden tripodale houding konden aannemen met staart en ischiale regio die lichaamsgewicht ondersteunden tijdens rust, metabolische kosten verminderend" },
          { en: "Large theropods could only stand on two legs at all times", es: "Terópodos grandes solo podían pararse sobre dos patas en todo momento", de: "Große Theropoden konnten nur jederzeit auf zwei Beinen stehen", nl: "Grote theropoden konden alleen te allen tijde op twee benen staan" },
          { en: "No evidence exists for theropod resting behavior", es: "No existe evidencia de comportamiento de descanso de terópodos", de: "Es gibt keine Beweise für Theropoden-Ruheverhalten", nl: "Er bestaat geen bewijs voor theropode rust gedrag" },
          { en: "Biomechanical analysis contradicts tripodal posture possibility", es: "Análisis biomecánico contradice posibilidad de postura tripodal", de: "Biomechanische Analyse widerspricht tripodaler Haltungsmöglichkeit", nl: "Biomechanische analyse tegenspreekt tripodale houding mogelijkheid" }
        ],
        correct: 0,
        explanation: {
          en: "Multiple lines of evidence support tripodal resting in large theropods. The enlarged pubic boot provided a third point of contact with the ground. Robust caudofemoral muscles could support the tail. Rare trace fossils show impressions consistent with this posture. This behavior would reduce energy expenditure during rest, important for large, potentially warm-blooded predators with high metabolic demands.",
          es: "Múltiples líneas de evidencia apoyan descanso tripodal en terópodos grandes. La bota púbica agrandada proporcionó un tercer punto de contacto con el suelo. Músculos caudofemorales robustos podían soportar la cola. Fósiles traza raros muestran impresiones consistentes con esta postura. Este comportamiento reduciría gasto energético durante descanso, importante para depredadores grandes, potencialmente de sangre caliente, con altas demandas metabólicas.",
          de: "Mehrere Beweislinien unterstützen tripodale Ruhe bei großen Theropoden. Der vergrößerte Schambeinstiefel bot einen dritten Kontaktpunkt mit dem Boden. Robuste caudofemorale Muskeln konnten den Schwanz unterstützen. Seltene Spurenfossilien zeigen Abdrücke, die mit dieser Haltung konsistent sind. Dieses Verhalten würde Energieaufwand während Ruhe reduzieren, wichtig für große, potenziell warmblütige Raubtiere mit hohen metabolischen Anforderungen.",
          nl: "Meerdere bewijslijnen ondersteunen tripodale rust in grote theropoden. De vergrote pubische laars bood een derde contactpunt met de grond. Robuste caudofemorale spieren konden de staart ondersteunen. Zeldzame spoor fossielen tonen afdrukken consistent met deze houding. Dit gedrag zou energie uitgaven tijdens rust verminderen, belangrijk voor grote, potentieel warmbloedige roofdieren met hoge metabolische eisen."
        }
      },
      {
        question: {
          en: "How does application of specimen-level phylogenetic analysis combined with stratigraphic range data constrain temporal patterns of anagenetic versus cladogenetic change in Allosaurus lineages within the Morrison Formation?",
          es: "¿Cómo la aplicación de análisis filogenético a nivel de especimen combinado con datos de rango estratigráfico restringe patrones temporales de cambio anagenético versus cladogenético en linajes de Allosaurus dentro de la Formación Morrison?",
          de: "Wie grenzt die Anwendung von Exemplar-Ebenen-phylogenetischer Analyse kombiniert mit stratigraphischen Bereichsdaten zeitliche Muster anagenctischer versus kladogenetischer Veränderung in Allosaurus-Linien innerhalb der Morrison-Formation ein?",
          nl: "Hoe beperkt toepassing van specimen-niveau fylogenetische analyse gecombineerd met stratigrafische bereik data temporele patronen van anagenetische versus cladogenetische verandering in Allosaurus lijnen binnen de Morrison Formatie?"
        },
        options: [
          { en: "Stratocladistic analysis reveals primarily anagenetic change within Allosaurus fragilis lineage across Lower to Upper Morrison, with limited cladogenesis and morphological stasis punctuated by rapid transitions at formation boundaries", es: "Análisis estratocladístico revela cambio principalmente anagenético dentro del linaje de Allosaurus fragilis a través de Morrison Inferior a Superior, con cladogénesis limitada y estasis morfológica puntuada por transiciones rápidas en límites de formación", de: "Stratokladistische Analyse zeigt primär anagenetische Veränderung innerhalb der Allosaurus fragilis-Linie über Unterer bis Oberer Morrison, mit begrenzter Kladogenese und morphologischer Stase, unterbrochen von schnellen Übergängen an Formationsgrenzen", nl: "Stratocladistische analyse onthult voornamelijk anagenetische verandering binnen Allosaurus fragilis lijn over Onderste tot Bovenste Morrison, met beperkte cladogenese en morfologische stasis onderbroken door snelle transities bij formatie grenzen" },
          { en: "Allosaurus shows constant rapid speciation throughout Morrison", es: "Allosaurus muestra especiación rápida constante durante toda Morrison", de: "Allosaurus zeigt konstante schnelle Artbildung während des gesamten Morrison", nl: "Allosaurus toont constante snelle soortvorming gedurende hele Morrison" },
          { en: "No temporal patterns can be detected in fossil data", es: "No se pueden detectar patrones temporales en datos fósiles", de: "Keine zeitlichen Muster können in fossilen Daten erkannt werden", nl: "Geen temporele patronen kunnen worden gedetecteerd in fossiel data" },
          { en: "Stratigraphic position is irrelevant to phylogenetic analysis", es: "Posición estratigráfica es irrelevante para análisis filogenético", de: "Stratigraphische Position ist für phylogenetische Analyse irrelevant", nl: "Stratigrafische positie is irrelevant voor fylogenetische analyse" }
        ],
        correct: 0,
        explanation: {
          en: "Stratocladistics incorporates stratigraphic information into phylogenetic analysis, testing evolutionary mode hypotheses. Analysis of Morrison Allosaurus specimens with precise stratigraphic provenance shows gradual morphological change within lineages (anagenesis) rather than frequent splitting events (cladogenesis). This pattern of evolutionary stasis with punctuated change at environmental transitions supports species selection models over gradual continuous transformation.",
          es: "Estratocladística incorpora información estratigráfica en análisis filogenético, probando hipótesis de modo evolutivo. Análisis de especímenes de Allosaurus de Morrison con procedencia estratigráfica precisa muestra cambio morfológico gradual dentro de linajes (anagénesis) en lugar de eventos frecuentes de división (cladogénesis). Este patrón de estasis evolutiva con cambio puntuado en transiciones ambientales apoya modelos de selección de especies sobre transformación continua gradual.",
          de: "Stratokladistik integriert stratigraphische Informationen in phylogenetische Analyse und testet evolutionäre Modus-Hypothesen. Analyse von Morrison-Allosaurus-Exemplaren mit präziser stratigraphischer Herkunft zeigt graduelle morphologische Veränderung innerhalb von Linien (Anagenese) statt häufiger Spaltungsereignisse (Kladogenese). Dieses Muster evolutionärer Stase mit unterbrochener Veränderung bei Umweltübergängen unterstützt Arten-Selektions-Modelle gegenüber gradueller kontinuierlicher Transformation.",
          nl: "Stratocladistiek incorporeert stratigrafische informatie in fylogenetische analyse, wat evolutionaire modus hypothesen test. Analyse van Morrison Allosaurus specimens met precieze stratigrafische herkomst toont geleidelijke morfologische verandering binnen lijnen (anagenese) in plaats van frequente splitsings gebeurtenissen (cladogenese). Dit patroon van evolutionaire stasis met onderbroken verandering bij omgevings transities ondersteunt soorten selectie modellen boven geleidelijke continue transformatie."
        }
      },
      {
        question: {
          en: "What does tooth wear microtexture analysis using confocal microscopy reveal about feeding behavior differences between Morrison Formation herbivorous dinosaurs and their implications for vegetation structure?",
          es: "¿Qué revela el análisis de microtextura de desgaste dental usando microscopía confocal sobre diferencias de comportamiento de alimentación entre dinosaurios herbívoros de la Formación Morrison y sus implicaciones para estructura de vegetación?",
          de: "Was zeigt Zahnabnutzungs-Mikrotextur-Analyse mit konfokaler Mikroskopie über Fraßverhalten-Unterschiede zwischen Morrison-Formation-herbivoren Dinosauriern und deren Implikationen für Vegetationsstruktur?",
          nl: "Wat onthult tand slijtage microtextuur analyse met behulp van confocale microscopie over voedings gedrag verschillen tussen Morrison Formatie herbivore dinosaurussen en hun implicaties voor vegetatie structuur?"
        },
        options: [
          { en: "Dental microwear texture analysis shows Camarasaurus exhibits high scratch complexity from processing tough vegetation while Diplodocus shows lower complexity consistent with selective soft-plant browsing, indicating vegetational heterogeneity", es: "Análisis de textura de microdesgaste dental muestra que Camarasaurus exhibe alta complejidad de rayas por procesar vegetación resistente mientras Diplodocus muestra menor complejidad consistente con ramoneo selectivo de plantas blandas, indicando heterogeneidad vegetacional", de: "Dentale Mikroabnutzungs-Textur-Analyse zeigt, dass Camarasaurus hohe Kratz-Komplexität durch Verarbeitung zäher Vegetation aufweist, während Diplodocus niedrigere Komplexität zeigt, konsistent mit selektivem Weichpflanzen-Fraß, was auf Vegetations-Heterogenität hindeutet", nl: "Dentale microslijtage textuur analyse toont aan dat Camarasaurus hoge kras complexiteit vertoont door verwerking van taaie vegetatie terwijl Diplodocus lagere complexiteit toont consistent met selectief zachte-plant browsen, wat vegetationele heterogeniteit aanduidt" },
          { en: "All sauropods show identical tooth wear patterns", es: "Todos los saurópodos muestran patrones de desgaste dental idénticos", de: "Alle Sauropoden zeigen identische Zahnabnutzungsmuster", nl: "Alle sauropoden tonen identieke tand slijtage patronen" },
          { en: "Tooth wear provides no dietary information", es: "Desgaste dental no proporciona información dietética", de: "Zahnabnutzung liefert keine diätetischen Informationen", nl: "Tand slijtage levert geen dieet informatie" },
          { en: "Morrison Formation vegetation was homogeneous", es: "Vegetación de Formación Morrison era homogénea", de: "Morrison-Formation-Vegetation war homogen", nl: "Morrison Formatie vegetatie was homogeen" }
        ],
        correct: 0,
        explanation: {
          en: "Dental microwear texture analysis quantifies microscopic scratches and pits on tooth enamel surfaces using confocal microscopy and 3D surface analysis. Different foods create distinctive wear patterns. Morrison sauropods show different microwear signatures indicating dietary specialization and niche partitioning. This implies diverse vegetation types coexisted, from soft ferns and aquatic plants to tougher conifers and cycads, supporting a complex plant community structure.",
          es: "Análisis de textura de microdesgaste dental cuantifica rayas y picaduras microscópicas en superficies de esmalte dental usando microscopía confocal y análisis de superficie 3D. Diferentes alimentos crean patrones de desgaste distintivos. Saurópodos de Morrison muestran diferentes firmas de microdesgaste indicando especialización dietética y partición de nicho. Esto implica que diversos tipos de vegetación coexistieron, desde helechos blandos y plantas acuáticas hasta coníferas y cícadas más resistentes, apoyando una estructura de comunidad vegetal compleja.",
          de: "Dentale Mikroabnutzungs-Textur-Analyse quantifiziert mikroskopische Kratzer und Vertiefungen auf Zahnschmelz-Oberflächen mit konfokaler Mikroskopie und 3D-Oberflächenanalyse. Verschiedene Nahrungsmittel erzeugen unterscheidbare Abnutzungsmuster. Morrison-Sauropoden zeigen unterschiedliche Mikroabnutzungs-Signaturen, die auf diätetische Spezialisierung und Nischen-Partitionierung hindeuten. Dies impliziert, dass diverse Vegetationstypen koexistierten, von weichen Farnen und Wasserpflanzen bis zu zäheren Nadelbäumen und Palmfarnen, was eine komplexe Pflanzengemeinschafts-Struktur unterstützt.",
          nl: "Dentale microslijtage textuur analyse kwantificeert microscopische krassen en putjes op tandglazuur oppervlakken met behulp van confocale microscopie en 3D oppervlakte analyse. Verschillende voedsel creëert onderscheidende slijtage patronen. Morrison sauropoden tonen verschillende microslijtage handtekeningen die dieet specialisatie en niche partitionering aangeven. Dit impliceert dat diverse vegetatie types co-existeerden, van zachte varens en aquatische planten tot taaiere coniferen en cycadeeën, wat een complexe plantengemeenschap structuur ondersteunt."
        }
      },
      {
        question: {
          en: "How does application of digital restoration techniques combined with musculoskeletal modeling constrain biomechanical hypotheses about neck function and feeding envelope in Mamenchisaurus and related Chinese Jurassic sauropods?",
          es: "¿Cómo la aplicación de técnicas de restauración digital combinadas con modelado musculoesquelético restringe hipótesis biomecánicas sobre función del cuello y envolvente de alimentación en Mamenchisaurus y saurópodos jurásicos chinos relacionados?",
          de: "Wie grenzt die Anwendung digitaler Restaurationstechniken kombiniert mit muskuloskelettaler Modellierung biomechanische Hypothesen über Halsfunktion und Fraß-Hülle bei Mamenchisaurus und verwandten chinesischen Jura-Sauropoden ein?",
          nl: "Hoe beperkt toepassing van digitale restauratie technieken gecombineerd met musculoskeletale modellering biomechanische hypothesen over nek functie en voedings envelop in Mamenchisaurus en gerelateerde Chinese Jura sauropoden?"
        },
        options: [
          { en: "Osteological neutral pose reconstruction with cervical rib articulation constraints indicates Mamenchisaurus held neck sub-horizontally with limited dorsoflexion, maximizing lateral rather than vertical feeding range through extensive horizontal sweeping", es: "Reconstrucción de pose neutral osteológica con restricciones de articulación de costilla cervical indica que Mamenchisaurus mantuvo cuello sub-horizontalmente con dorsiflexión limitada, maximizando rango de alimentación lateral en lugar de vertical através de barrido horizontal extenso", de: "Osteologische neutrale Haltungs-Rekonstruktion mit zervikalen Rippen-Artikulations-Beschränkungen deutet darauf hin, dass Mamenchisaurus den Hals sub-horizontal mit begrenzter Dorsoflexion hielt und laterale statt vertikale Fraß-Reichweite durch ausgedehntes horizontales Schwenken maximierte", nl: "Osteologische neutrale houding reconstructie met cervicale rib articulatie beperkingen duidt aan dat Mamenchisaurus nek sub-horizontaal hield met beperkte dorsiflexie, laterale in plaats van verticale voedings bereik maximalisend door uitgebreid horizontaal zwaaien" },
          { en: "Long-necked sauropods held necks vertically like giraffes", es: "Saurópodos de cuello largo mantenían cuellos verticalmente como jirafas", de: "Langhals-Sauropoden hielten Hälse vertikal wie Giraffen", nl: "Langneklige sauropoden hielden nekken verticaal zoals giraffen" },
          { en: "Neck posture cannot be determined from skeletal evidence", es: "Postura del cuello no puede determinarse de evidencia esquelética", de: "Halshaltung kann nicht aus skelettalen Beweisen bestimmt werden", nl: "Nek houding kan niet worden bepaald uit skeletaal bewijs" },
          { en: "Musculoskeletal modeling is irrelevant to feeding behavior", es: "Modelado musculoesquelético es irrelevante para comportamiento de alimentación", de: "Muskuloskelettale Modellierung ist für Fraßverhalten irrelevant", nl: "Musculoskeletale modellering is irrelevant voor voedings gedrag" }
        ],
        correct: 0,
        explanation: {
          en: "Digital restoration establishes anatomically consistent neutral poses based on bone articulations and soft tissue constraints. For extremely long-necked sauropods, analysis of cervical rib overlap, zygapophyseal joint surfaces, and muscle lever arms indicates habitual horizontal neck carriage was biomechanically optimal. This maximized ground-level browsing area accessible through lateral neck movements while minimizing cardiac work against gravity, an efficient feeding strategy for giant herbivores.",
          es: "Restauración digital establece poses neutrales anatómicamente consistentes basadas en articulaciones óseas y restricciones de tejido blando. Para saurópodos de cuello extremadamente largo, análisis de superposición de costilla cervical, superficies articulares zigapofiseales y brazos de palanca muscular indica que transporte de cuello horizontal habitual era biomecánicamente óptimo. Esto maximizó área de ramoneo a nivel del suelo accesible através de movimientos laterales de cuello mientras minimizaba trabajo cardíaco contra gravedad, una estrategia de alimentación eficiente para herbívoros gigantes.",
          de: "Digitale Restauration etabliert anatomisch konsistente neutrale Posen basierend auf Knochenartikulation und Weichteil-Beschränkungen. Für extrem langhalsige Sauropoden zeigt Analyse von zervikaler Rippen-Überlappung, Zygapophyseal-Gelenkflächen und Muskel-Hebelarmen, dass habituelle horizontale Halshaltung biomechanisch optimal war. Dies maximierte Boden-Ebenen-Fraß-Bereich, der durch laterale Hals-Bewegungen zugänglich war, während kardialer Arbeit gegen Schwerkraft minimiert wurde, eine effiziente Fraß-Strategie für gigantische Herbivoren.",
          nl: "Digitale restauratie vestigt anatomisch consistente neutrale houdingen gebaseerd op bot articulaties en zacht weefsel beperkingen. Voor extreem langnekkige sauropoden duidt analyse van cervicale rib overlap, zygapofyseale gewrichtsoppervlakken en spier hefboomarmen aan dat habituele horizontale nek houding biomechanisch optimaal was. Dit maximaliseerde grond-niveau browse gebied toegankelijk door laterale nek bewegingen terwijl cardiale werk tegen zwaartekracht geminimaliseerd werd, een efficiënte voedings strategie voor gigantische herbivoren."
        }
      }
    ]
  };

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = level10;
  } else if (typeof window !== 'undefined') {
    window.level10 = level10;
  }
})();
