// Quiz Level 8: Drinken - Sappen (Advanced Juice Science)
(function() {
  const level8 = {
    name: {
      en: "Advanced Juice Science",
      es: "Ciencia Avanzada de Jugos",
      de: "Fortgeschrittene Saftwissenschaft",
      nl: "Geavanceerde Sapwetenschap"
    },
    questions: [
      {
        question: {
          en: "What is the molecular mechanism behind enzymatic browning in apple juice and how does it differ from non-enzymatic browning?",
          es: "¿Cuál es el mecanismo molecular detrás del pardeamiento enzimático en jugo de manzana y cómo difiere del pardeamiento no enzimático?",
          de: "Was ist der molekulare Mechanismus hinter enzymatischer Bräunung in Apfelsaft und wie unterscheidet er sich von nicht-enzymatischer Bräunung?",
          nl: "Wat is het moleculaire mechanisme achter enzymatische bruining in appelsap en hoe verschilt het van niet-enzymatische bruining?"
        },
        options: [
          { en: "Polyphenol oxidase converts phenolic compounds to quinones via copper cofactors, while non-enzymatic browning involves Maillard reactions between reducing sugars and amino acids", es: "La polifenol oxidasa convierte compuestos fenólicos a quinonas vía cofactores de cobre, mientras que el pardeamiento no enzimático involucra reacciones de Maillard entre azúcares reductores y aminoácidos", de: "Polyphenoloxidase wandelt phenolische Verbindungen über Kupfer-Cofaktoren zu Chinonen um, während nicht-enzymatische Bräunung Maillard-Reaktionen zwischen reduzierenden Zuckern und Aminosäuren beinhaltet", nl: "Polyfenol oxidase zet fenolische verbindingen om naar quinonen via koper cofactoren, terwijl niet-enzymatische bruining Maillard reacties tussen reducerende suikers en aminozuren behelst" },
          { en: "Only temperature affects browning", es: "Solo la temperatura afecta el pardeamiento", de: "Nur Temperatur beeinflusst Bräunung", nl: "Alleen temperatuur beïnvloedt bruining" },
          { en: "Both mechanisms are identical", es: "Ambos mecanismos son idénticos", de: "Beide Mechanismen sind identisch", nl: "Beide mechanismen zijn identiek" },
          { en: "Only pH changes cause browning", es: "Solo los cambios de pH causan pardeamiento", de: "Nur pH-Änderungen verursachen Bräunung", nl: "Alleen pH veranderingen veroorzaken bruining" }
        ],
        correct: 0,
        explanation: {
          en: "Enzymatic browning occurs when polyphenol oxidase (PPO) enzyme catalyzes the oxidation of phenolic substrates like chlorogenic acid to quinones using copper as a cofactor. These quinones then polymerize to form brown pigments. Non-enzymatic browning occurs through Maillard reactions between reducing sugars and amino acids at elevated temperatures, producing different chemical pathways and flavor compounds.",
          es: "El pardeamiento enzimático ocurre cuando la enzima polifenol oxidasa (PPO) cataliza la oxidación de sustratos fenólicos como ácido clorogénico a quinonas usando cobre como cofactor. Estas quinonas luego se polimerizan para formar pigmentos marrones. El pardeamiento no enzimático ocurre a través de reacciones de Maillard entre azúcares reductores y aminoácidos a temperaturas elevadas, produciendo diferentes vías químicas y compuestos de sabor.",
          de: "Enzymatische Bräunung tritt auf, wenn das Polyphenoloxidase (PPO) Enzym die Oxidation phenolischer Substrate wie Chlorogensäure zu Chinonen unter Verwendung von Kupfer als Cofaktor katalysiert. Diese Chinone polymerisieren dann zu braunen Pigmenten. Nicht-enzymatische Bräunung erfolgt durch Maillard-Reaktionen zwischen reduzierenden Zuckern und Aminosäuren bei erhöhten Temperaturen, wodurch verschiedene chemische Wege und Geschmacksverbindungen entstehen.",
          nl: "Enzymatische bruining treedt op wanneer het polyfenol oxidase (PPO) enzym de oxidatie van fenolische substraten zoals chlorogeenzuur naar quinonen katalyseert met koper als cofactor. Deze quinonen polymeriseren vervolgens tot bruine pigmenten. Niet-enzymatische bruining vindt plaats door Maillard reacties tussen reducerende suikers en aminozuren bij verhoogde temperaturen, wat verschillende chemische paden en smaakverbindingen produceert."
        }
      },
      {
        question: {
          en: "How does the glass transition temperature (Tg) affect the stability of concentrated fruit juice powders during storage?",
          es: "¿Cómo afecta la temperatura de transición vítrea (Tg) la estabilidad de polvos de jugo de frutas concentrados durante el almacenamiento?",
          de: "Wie beeinflusst die Glasübergangstemperatur (Tg) die Stabilität konzentrierter Fruchtsaftpulver während der Lagerung?",
          nl: "Hoe beïnvloedt de glasovergangstemperatuur (Tg) de stabiliteit van geconcentreerde vruchtensappoeders tijdens opslag?"
        },
        options: [
          { en: "Storage below Tg maintains glassy state preventing molecular mobility, collapse, and chemical degradation reactions", es: "Almacenamiento debajo de Tg mantiene estado vítreo previniendo movilidad molecular, colapso y reacciones de degradación química", de: "Lagerung unter Tg erhält glasigen Zustand und verhindert molekulare Mobilität, Kollaps und chemische Abbaureaktionen", nl: "Opslag onder Tg handhaaft glazige toestand waardoor moleculaire mobiliteit, ineenstorting en chemische degradatiereacties worden voorkomen" },
          { en: "Glass transition has no effect on powder stability", es: "La transición vítrea no tiene efecto en la estabilidad del polvo", de: "Glasübergang hat keinen Einfluss auf Pulverstabilität", nl: "Glasovergang heeft geen effect op poeder stabiliteit" },
          { en: "Only humidity affects powder quality", es: "Solo la humedad afecta la calidad del polvo", de: "Nur Luftfeuchtigkeit beeinflusst Pulverqualität", nl: "Alleen vochtigheid beïnvloedt poederkwaliteit" },
          { en: "Temperature changes are irrelevant", es: "Los cambios de temperatura son irrelevantes", de: "Temperaturänderungen sind irrelevant", nl: "Temperatuurveranderingen zijn irrelevant" }
        ],
        correct: 0,
        explanation: {
          en: "The glass transition temperature is critical for powder stability. Below Tg, the powder exists in a glassy state with restricted molecular mobility, which inhibits degradation reactions, prevents structural collapse, and maintains product quality. Above Tg, the material becomes rubbery with increased molecular mobility, leading to stickiness, caking, accelerated chemical reactions, and loss of bioactive compounds.",
          es: "La temperatura de transición vítrea es crítica para la estabilidad del polvo. Debajo de Tg, el polvo existe en estado vítreo con movilidad molecular restringida, lo que inhibe reacciones de degradación, previene colapso estructural y mantiene calidad del producto. Encima de Tg, el material se vuelve gomoso con movilidad molecular aumentada, llevando a pegajosidad, apelmazamiento, reacciones químicas aceleradas y pérdida de compuestos bioactivos.",
          de: "Die Glasübergangstemperatur ist kritisch für Pulverstabilität. Unter Tg existiert das Pulver in glasigem Zustand mit eingeschränkter molekularer Mobilität, was Abbaureaktionen hemmt, strukturellen Kollaps verhindert und Produktqualität erhält. Über Tg wird das Material gummiartig mit erhöhter molekularer Mobilität, was zu Klebrigkeit, Verklumpung, beschleunigten chemischen Reaktionen und Verlust bioaktiver Verbindungen führt.",
          nl: "De glasovergangstemperatuur is cruciaal voor poederstabiliteit. Onder Tg bestaat het poeder in glazige toestand met beperkte moleculaire mobiliteit, wat degradatiereacties remt, structurele ineenstorting voorkomt en productkwaliteit handhaaft. Boven Tg wordt het materiaal rubberachtig met verhoogde moleculaire mobiliteit, wat leidt tot kleefheid, samenklitten, versnelde chemische reacties en verlies van bioactieve verbindingen."
        }
      },
      {
        question: {
          en: "What is the role of water activity and the Monod equation in predicting microbial growth kinetics in fruit juice concentrates?",
          es: "¿Cuál es el papel de la actividad del agua y la ecuación de Monod en predecir cinéticas de crecimiento microbiano en concentrados de jugo de frutas?",
          de: "Welche Rolle spielen Wasseraktivität und die Monod-Gleichung bei der Vorhersage mikrobieller Wachstumskinetik in Fruchtsaftkonzentraten?",
          nl: "Wat is de rol van wateractiviteit en de Monod vergelijking in het voorspellen van microbiële groeikinetiek in vruchtensapconcentraten?"
        },
        options: [
          { en: "Water activity determines available water for microbial metabolism while Monod equation describes growth rate as function of limiting substrate concentration", es: "La actividad del agua determina agua disponible para metabolismo microbiano mientras que ecuación de Monod describe tasa de crecimiento como función de concentración de sustrato limitante", de: "Wasseraktivität bestimmt verfügbares Wasser für mikrobiellen Stoffwechsel während Monod-Gleichung Wachstumsrate als Funktion der limitierenden Substratkonzentration beschreibt", nl: "Wateractiviteit bepaalt beschikbaar water voor microbiële stofwisseling terwijl Monod vergelijking groeisnelheid beschrijft als functie van beperkende substraatconcentratie" },
          { en: "Both concepts are unrelated to food science", es: "Ambos conceptos no están relacionados con ciencia alimentaria", de: "Beide Konzepte sind nicht mit Lebensmittelwissenschaft verwandt", nl: "Beide concepten zijn niet gerelateerd aan voedingswetenschap" },
          { en: "Only temperature affects microbial growth", es: "Solo la temperatura afecta el crecimiento microbiano", de: "Nur Temperatur beeinflusst mikrobielles Wachstum", nl: "Alleen temperatuur beïnvloedt microbiële groei" },
          { en: "pH is the only limiting factor", es: "El pH es el único factor limitante", de: "pH ist der einzige limitierende Faktor", nl: "pH is de enige beperkende factor" }
        ],
        correct: 0,
        explanation: {
          en: "Water activity (aw) represents the ratio of water vapor pressure in the food to pure water, determining water availability for microbial growth. Most bacteria require aw > 0.95, yeasts > 0.88, and molds > 0.70. The Monod equation (μ = μmax[S]/(Ks + [S])) describes specific growth rate (μ) as a function of substrate concentration [S], with μmax as maximum growth rate and Ks as half-saturation constant. Together, they predict microbial behavior in juice concentrates.",
          es: "La actividad del agua (aw) representa la relación de presión de vapor de agua en el alimento al agua pura, determinando disponibilidad de agua para crecimiento microbiano. La mayoría de bacterias requieren aw > 0.95, levaduras > 0.88, y mohos > 0.70. La ecuación de Monod (μ = μmax[S]/(Ks + [S])) describe tasa de crecimiento específica (μ) como función de concentración de sustrato [S], con μmax como tasa máxima de crecimiento y Ks como constante de media saturación. Juntas, predicen comportamiento microbiano en concentrados de jugo.",
          de: "Wasseraktivität (aw) repräsentiert das Verhältnis des Wasserdampfdrucks im Lebensmittel zu reinem Wasser und bestimmt Wasserverfügbarkeit für mikrobielles Wachstum. Die meisten Bakterien benötigen aw > 0.95, Hefen > 0.88, und Schimmelpilze > 0.70. Die Monod-Gleichung (μ = μmax[S]/(Ks + [S])) beschreibt spezifische Wachstumsrate (μ) als Funktion der Substratkonzentration [S], mit μmax als maximale Wachstumsrate und Ks als Halbsättigungskonstante. Zusammen sagen sie mikrobielles Verhalten in Saftkonzentraten voraus.",
          nl: "Wateractiviteit (aw) vertegenwoordigt de verhouding van waterdampdruk in het voedsel tot zuiver water, waardoor waterbeschikbaarheid voor microbiële groei wordt bepaald. De meeste bacteriën vereisen aw > 0.95, gisten > 0.88, en schimmels > 0.70. De Monod vergelijking (μ = μmax[S]/(Ks + [S])) beschrijft specifieke groeisnelheid (μ) als functie van substraatconcentratie [S], met μmax als maximale groeisnelheid en Ks als half-verzadigingsconstante. Samen voorspellen ze microbieel gedrag in sapconcentraten."
        }
      },
      {
        question: {
          en: "How do rheological properties change during juice concentration and what is the significance of the power law model in describing flow behavior?",
          es: "¿Cómo cambian las propiedades reológicas durante la concentración de jugos y cuál es la significancia del modelo de ley de potencia en describir comportamiento de flujo?",
          de: "Wie verändern sich rheologische Eigenschaften während der Saftkonzentration und welche Bedeutung hat das Potenzgesetz-Modell bei der Beschreibung des Fließverhaltens?",
          nl: "Hoe veranderen reologische eigenschappen tijdens sapconcentratie en wat is de betekenis van het machtwet model bij het beschrijven van stroomgedrag?"
        },
        options: [
          { en: "Viscosity increases exponentially with concentration following power law τ = K(γ̇)ⁿ, where n<1 indicates shear-thinning behavior typical of fruit juices", es: "La viscosidad aumenta exponencialmente con concentración siguiendo ley de potencia τ = K(γ̇)ⁿ, donde n<1 indica comportamiento de adelgazamiento por corte típico de jugos de frutas", de: "Viskosität steigt exponentiell mit Konzentration nach Potenzgesetz τ = K(γ̇)ⁿ, wobei n<1 scherverdünnendes Verhalten typisch für Fruchtsäfte anzeigt", nl: "Viscositeit neemt exponentieel toe met concentratie volgens machtwet τ = K(γ̇)ⁿ, waarbij n<1 shear-thinning gedrag typisch voor vruchtensappen aangeeft" },
          { en: "Rheology remains constant during concentration", es: "La reología permanece constante durante concentración", de: "Rheologie bleibt während Konzentration konstant", nl: "Reologie blijft constant tijdens concentratie" },
          { en: "Only temperature affects viscosity", es: "Solo la temperatura afecta la viscosidad", de: "Nur Temperatur beeinflusst Viskosität", nl: "Alleen temperatuur beïnvloedt viscositeit" },
          { en: "Fruit juices always behave as Newtonian fluids", es: "Los jugos de frutas siempre se comportan como fluidos newtonianos", de: "Fruchtsäfte verhalten sich immer als Newton'sche Flüssigkeiten", nl: "Vruchtensappen gedragen zich altijd als Newtoniaanse vloeistoffen" }
        ],
        correct: 0,
        explanation: {
          en: "During concentration, juice viscosity increases dramatically due to higher solids content and molecular interactions. The power law model τ = K(γ̇)ⁿ describes the relationship between shear stress (τ) and shear rate (γ̇), where K is consistency index and n is flow behavior index. For fruit juices, n < 1 indicates pseudoplastic (shear-thinning) behavior, meaning viscosity decreases with increasing shear rate. This is crucial for pump design, heat transfer calculations, and processing equipment sizing.",
          es: "Durante concentración, la viscosidad del jugo aumenta dramáticamente debido a mayor contenido de sólidos e interacciones moleculares. El modelo de ley de potencia τ = K(γ̇)ⁿ describe la relación entre esfuerzo cortante (τ) y tasa de corte (γ̇), donde K es índice de consistencia y n es índice de comportamiento de flujo. Para jugos de frutas, n < 1 indica comportamiento pseudoplástico (adelgazamiento por corte), significando que viscosidad disminuye con tasa de corte creciente. Esto es crucial para diseño de bombas, cálculos de transferencia de calor y dimensionamiento de equipos de procesamiento.",
          de: "Während der Konzentration steigt die Saftviskosität dramatisch aufgrund höheren Feststoffgehalts und molekularer Wechselwirkungen. Das Potenzgesetz-Modell τ = K(γ̇)ⁿ beschreibt die Beziehung zwischen Scherspannung (τ) und Scherrate (γ̇), wobei K Konsistenzindex und n Fließverhaltensindex ist. Für Fruchtsäfte zeigt n < 1 pseudoplastisches (scherverdünnendes) Verhalten an, was bedeutet, dass Viskosität mit steigender Scherrate abnimmt. Dies ist entscheidend für Pumpendesign, Wärmeübertragungsberechnungen und Dimensionierung von Verarbeitungsgeräten.",
          nl: "Tijdens concentratie neemt sapviscositeit dramatisch toe door hoger vaste stof gehalte en moleculaire interacties. Het machtwet model τ = K(γ̇)ⁿ beschrijft de relatie tussen shear stress (τ) en shear rate (γ̇), waarbij K consistentie index en n flow gedrag index is. Voor vruchtensappen geeft n < 1 pseudoplastisch (shear-thinning) gedrag aan, wat betekent dat viscositeit afneemt bij toenemende shear rate. Dit is cruciaal voor pompontwerp, warmteoverdracht berekeningen en procesapparatuur dimensionering."
        }
      },
      {
        question: {
          en: "What is the thermodynamic basis for osmotic dehydration in fruit pieces and how does the Flory-Huggins equation predict water activity?",
          es: "¿Cuál es la base termodinámica para deshidratación osmótica en piezas de fruta y cómo predice la ecuación de Flory-Huggins la actividad del agua?",
          de: "Was ist die thermodynamische Grundlage für osmotische Dehydratation in Fruchtstücken und wie sagt die Flory-Huggins-Gleichung Wasseraktivität voraus?",
          nl: "Wat is de thermodynamische basis voor osmotische dehydratie in fruitstukken en hoe voorspelt de Flory-Huggins vergelijking wateractiviteit?"
        },
        options: [
          { en: "Water chemical potential difference drives mass transfer, Flory-Huggins equation: ln(aw) = ln(xw) + (1-xw) + χ(1-xw)² accounts for polymer-solvent interactions", es: "Diferencia de potencial químico del agua impulsa transferencia de masa, ecuación Flory-Huggins: ln(aw) = ln(xw) + (1-xw) + χ(1-xw)² considera interacciones polímero-solvente", de: "Wasserpotentialdifferenz treibt Massentransfer an, Flory-Huggins-Gleichung: ln(aw) = ln(xw) + (1-xw) + χ(1-xw)² berücksichtigt Polymer-Lösungsmittel-Wechselwirkungen", nl: "Water chemisch potentiaal verschil drijft massaoverdracht aan, Flory-Huggins vergelijking: ln(aw) = ln(xw) + (1-xw) + χ(1-xw)² houdt rekening met polymeer-oplosmiddel interacties" },
          { en: "Only concentration gradients matter", es: "Solo importan gradientes de concentración", de: "Nur Konzentrationsgradienten sind wichtig", nl: "Alleen concentratie gradiënten zijn belangrijk" },
          { en: "Temperature is the only driving force", es: "La temperatura es la única fuerza motriz", de: "Temperatur ist die einzige Triebkraft", nl: "Temperatuur is de enige drijvende kracht" },
          { en: "Osmotic pressure has no thermodynamic basis", es: "La presión osmótica no tiene base termodinámica", de: "Osmotischer Druck hat keine thermodynamische Grundlage", nl: "Osmotische druk heeft geen thermodynamische basis" }
        ],
        correct: 0,
        explanation: {
          en: "Osmotic dehydration is driven by chemical potential differences between water in the fruit tissue and the osmotic solution. Water moves from higher to lower chemical potential until equilibrium. The Flory-Huggins equation describes water activity in food systems containing polymers (like pectin, cellulose): ln(aw) = ln(xw) + (1-xw) + χ(1-xw)², where xw is water mole fraction and χ is the interaction parameter reflecting polymer-water interactions. This accounts for non-ideal solution behavior in food matrices.",
          es: "La deshidratación osmótica es impulsada por diferencias de potencial químico entre agua en tejido de fruta y solución osmótica. El agua se mueve de mayor a menor potencial químico hasta equilibrio. La ecuación Flory-Huggins describe actividad del agua en sistemas alimentarios conteniendo polímeros (como pectina, celulosa): ln(aw) = ln(xw) + (1-xw) + χ(1-xw)², donde xw es fracción molar de agua y χ es parámetro de interacción reflejando interacciones polímero-agua. Esto considera comportamiento de solución no ideal en matrices alimentarias.",
          de: "Osmotische Dehydratation wird durch chemische Potentialdifferenzen zwischen Wasser im Fruchtgewebe und der osmotischen Lösung angetrieben. Wasser bewegt sich von höherem zu niedrigerem chemischen Potential bis zum Gleichgewicht. Die Flory-Huggins-Gleichung beschreibt Wasseraktivität in Lebensmittelsystemen mit Polymeren (wie Pektin, Cellulose): ln(aw) = ln(xw) + (1-xw) + χ(1-xw)², wobei xw Wassermolanteil und χ Wechselwirkungsparameter ist, der Polymer-Wasser-Wechselwirkungen widerspiegelt. Dies berücksichtigt nicht-ideales Lösungsverhalten in Lebensmittelmatrizen.",
          nl: "Osmotische dehydratie wordt gedreven door chemisch potentiaal verschillen tussen water in fruitweefsel en de osmotische oplossing. Water beweegt van hoger naar lager chemisch potentiaal tot evenwicht. De Flory-Huggins vergelijking beschrijft wateractiviteit in voedselsystemen die polymeren bevatten (zoals pectine, cellulose): ln(aw) = ln(xw) + (1-xw) + χ(1-xw)², waarbij xw watermolfractie is en χ de interactieparameter die polymeer-water interacties weergeeft. Dit houdt rekening met niet-ideaal oplossingsgedrag in voedselmatrices."
        }
      },
      {
        question: {
          en: "How does the kinetic theory explain diffusion coefficients in fruit juice clarification using Fick's laws and the Stokes-Einstein equation?",
          es: "¿Cómo explica la teoría cinética los coeficientes de difusión en clarificación de jugo de frutas usando leyes de Fick y ecuación de Stokes-Einstein?",
          de: "Wie erklärt die kinetische Theorie Diffusionskoeffizienten in der Fruchtsaft-Klärung unter Verwendung der Fick'schen Gesetze und der Stokes-Einstein-Gleichung?",
          nl: "Hoe verklaart de kinetische theorie diffusiecoëfficiënten in vruchtensapklaring met behulp van Fick's wetten en de Stokes-Einstein vergelijking?"
        },
        options: [
          { en: "Fick's first law J = -D∇C describes steady-state flux, Stokes-Einstein D = kT/(6πηr) relates diffusivity to particle size and viscosity", es: "Primera ley de Fick J = -D∇C describe flujo estado estacionario, Stokes-Einstein D = kT/(6πηr) relaciona difusividad con tamaño de partícula y viscosidad", de: "Ficksches erstes Gesetz J = -D∇C beschreibt stationären Fluss, Stokes-Einstein D = kT/(6πηr) verknüpft Diffusivität mit Partikelgröße und Viskosität", nl: "Fick's eerste wet J = -D∇C beschrijft steady-state flux, Stokes-Einstein D = kT/(6πηr) relateert diffusiviteit aan deeltjesgrootte en viscositeit" },
          { en: "Diffusion only depends on temperature", es: "La difusión solo depende de la temperatura", de: "Diffusion hängt nur von der Temperatur ab", nl: "Diffusie hangt alleen af van temperatuur" },
          { en: "Particle size has no effect on diffusion", es: "El tamaño de partícula no tiene efecto en difusión", de: "Partikelgröße hat keinen Einfluss auf Diffusion", nl: "Deeltjesgrootte heeft geen effect op diffusie" },
          { en: "Viscosity is irrelevant to clarification", es: "La viscosidad es irrelevante para clarificación", de: "Viskosität ist irrelevant für Klärung", nl: "Viscositeit is irrelevant voor klaring" }
        ],
        correct: 0,
        explanation: {
          en: "Fick's first law (J = -D∇C) describes diffusion flux as proportional to concentration gradient, while Fick's second law (∂C/∂t = D∇²C) describes time-dependent concentration changes. The Stokes-Einstein equation D = kT/(6πηr) shows that diffusion coefficient is inversely proportional to particle radius (r) and solution viscosity (η), and directly proportional to temperature (T). In juice clarification, larger particles (pulp, pectin aggregates) diffuse slower than smaller molecules, enabling separation based on size differences.",
          es: "La primera ley de Fick (J = -D∇C) describe flujo de difusión como proporcional al gradiente de concentración, mientras que la segunda ley de Fick (∂C/∂t = D∇²C) describe cambios de concentración dependientes del tiempo. La ecuación Stokes-Einstein D = kT/(6πηr) muestra que coeficiente de difusión es inversamente proporcional al radio de partícula (r) y viscosidad de solución (η), y directamente proporcional a temperatura (T). En clarificación de jugo, partículas más grandes (pulpa, agregados de pectina) se difunden más lento que moléculas más pequeñas, permitiendo separación basada en diferencias de tamaño.",
          de: "Ficksches erstes Gesetz (J = -D∇C) beschreibt Diffusionsfluss als proportional zum Konzentrationsgradienten, während Ficksches zweites Gesetz (∂C/∂t = D∇²C) zeitabhängige Konzentrationsänderungen beschreibt. Die Stokes-Einstein-Gleichung D = kT/(6πηr) zeigt, dass Diffusionskoeffizient umgekehrt proportional zu Partikelradius (r) und Lösungsviskosität (η) und direkt proportional zur Temperatur (T) ist. Bei Saftklärung diffundieren größere Partikel (Pulpe, Pektin-Aggregate) langsamer als kleinere Moleküle, was Trennung basierend auf Größenunterschieden ermöglicht.",
          nl: "Fick's eerste wet (J = -D∇C) beschrijft diffusie flux als evenredig aan concentratie gradient, terwijl Fick's tweede wet (∂C/∂t = D∇²C) tijdsafhankelijke concentratieveranderingen beschrijft. De Stokes-Einstein vergelijking D = kT/(6πηr) toont dat diffusiecoëfficiënt omgekeerd evenredig is aan deeltjesradius (r) en oplossingsviscositeit (η), en direct evenredig aan temperatuur (T). Bij sapklaring diffunderen grotere deeltjes (pulp, pectine aggregaten) langzamer dan kleinere moleculen, waardoor scheiding op basis van grootteverschillen mogelijk wordt."
        }
      },
      {
        question: {
          en: "What is the molecular basis of gelation in pectin-containing fruit juices and how does the thermodynamic sol-gel transition occur?",
          es: "¿Cuál es la base molecular de gelificación en jugos de frutas conteniendo pectina y cómo ocurre la transición termodinámica sol-gel?",
          de: "Was ist die molekulare Grundlage der Gelierung in pektinhaltigen Fruchtsäften und wie erfolgt der thermodynamische Sol-Gel-Übergang?",
          nl: "Wat is de moleculaire basis van gelering in pectine-bevattende vruchtensappen en hoe vindt de thermodynamische sol-gel overgang plaats?"
        },
        options: [
          { en: "Pectin forms junction zones through hydrogen bonding and electrostatic interactions, sol-gel transition follows percolation theory with critical concentration", es: "Pectina forma zonas de unión a través de enlaces de hidrógeno e interacciones electrostáticas, transición sol-gel sigue teoría de percolación con concentración crítica", de: "Pektin bildet Verbindungszonen durch Wasserstoffbrücken und elektrostatische Wechselwirkungen, Sol-Gel-Übergang folgt Perkolationstheorie mit kritischer Konzentration", nl: "Pectine vormt verbindingszones door waterstofbruggen en elektrostatische interacties, sol-gel overgang volgt percolatietheorie met kritieke concentratie" },
          { en: "Gelation is purely physical without molecular interactions", es: "La gelificación es puramente física sin interacciones moleculares", de: "Gelierung ist rein physikalisch ohne molekulare Wechselwirkungen", nl: "Gelering is puur fysiek zonder moleculaire interacties" },
          { en: "Only temperature controls gel formation", es: "Solo la temperatura controla formación de gel", de: "Nur Temperatur kontrolliert Gelbildung", nl: "Alleen temperatuur controleert gelvorming" },
          { en: "Pectin cannot form gels in fruit juices", es: "La pectina no puede formar geles en jugos de frutas", de: "Pektin kann keine Gele in Fruchtsäften bilden", nl: "Pectine kan geen gels vormen in vruchtensappen" }
        ],
        correct: 0,
        explanation: {
          en: "Pectin gelation involves formation of junction zones where polymer chains associate through hydrogen bonding between hydroxyl groups and electrostatic interactions with divalent cations (Ca²⁺). The sol-gel transition is a critical phenomenon described by percolation theory, where a continuous network forms above a critical pectin concentration (typically 0.5-1.0%). The gel modulus follows power law G ∝ (c-c₀)ᵗ, where c₀ is critical concentration and t is the critical exponent. This creates the three-dimensional network that traps water and solutes.",
          es: "La gelificación de pectina involucra formación de zonas de unión donde cadenas poliméricas se asocian a través de enlaces de hidrógeno entre grupos hidroxilo e interacciones electrostáticas con cationes divalentes (Ca²⁺). La transición sol-gel es fenómeno crítico descrito por teoría de percolación, donde red continua se forma encima de concentración crítica de pectina (típicamente 0.5-1.0%). El módulo de gel sigue ley de potencia G ∝ (c-c₀)ᵗ, donde c₀ es concentración crítica y t es exponente crítico. Esto crea red tridimensional que atrapa agua y solutos.",
          de: "Pektin-Gelierung beinhaltet Bildung von Verbindungszonen, wo Polymerketten sich durch Wasserstoffbrücken zwischen Hydroxylgruppen und elektrostatische Wechselwirkungen mit zweiwertigen Kationen (Ca²⁺) assoziieren. Der Sol-Gel-Übergang ist kritisches Phänomen beschrieben durch Perkolationstheorie, wo kontinuierliches Netzwerk über kritischer Pektinkonzentration (typisch 0.5-1.0%) entsteht. Gelmodul folgt Potenzgesetz G ∝ (c-c₀)ᵗ, wobei c₀ kritische Konzentration und t kritischer Exponent ist. Dies schafft dreidimensionales Netzwerk, das Wasser und gelöste Stoffe einfängt.",
          nl: "Pectine gelering behelst vorming van verbindingszones waar polymeerketens associëren door waterstofbruggen tussen hydroxylgroepen en elektrostatische interacties met divalente kationen (Ca²⁺). De sol-gel overgang is kritiek fenomeen beschreven door percolatietheorie, waarbij een continu netwerk vormt boven kritieke pectineconcentratie (typisch 0.5-1.0%). De gelmodulus volgt machtwet G ∝ (c-c₀)ᵗ, waarbij c₀ kritieke concentratie en t de kritieke exponent is. Dit creëert driedimensionaal netwerk dat water en opgeloste stoffen vasthoudt."
        }
      },
      {
        question: {
          en: "How do interfacial phenomena and surface tension influence emulsion stability in fruit juice-based beverages containing lipid phases?",
          es: "¿Cómo influyen fenómenos interfaciales y tensión superficial en estabilidad de emulsión en bebidas basadas en jugo de frutas conteniendo fases lipídicas?",
          de: "Wie beeinflussen Grenzflächenphänomene und Oberflächenspannung die Emulsionsstabilität in fruchtsaftbasierten Getränken mit Lipidphasen?",
          nl: "Hoe beïnvloeden interfaciale fenomenen en oppervlaktespanning emulsiestabiliteit in op vruchtensap gebaseerde dranken die lipide fasen bevatten?"
        },
        options: [
          { en: "Surface tension minimization through emulsifiers creates thermodynamic stability, Young-Laplace equation ΔP = γ(1/R₁ + 1/R₂) governs pressure differences across curved interfaces", es: "Minimización de tensión superficial a través de emulsificantes crea estabilidad termodinámica, ecuación Young-Laplace ΔP = γ(1/R₁ + 1/R₂) gobierna diferencias de presión a través de interfaces curvadas", de: "Oberflächenspannungsminimierung durch Emulgatoren schafft thermodynamische Stabilität, Young-Laplace-Gleichung ΔP = γ(1/R₁ + 1/R₂) regelt Druckunterschiede über gekrümmte Grenzflächen", nl: "Oppervlaktespanning minimalisatie door emulgatoren creëert thermodynamische stabiliteit, Young-Laplace vergelijking ΔP = γ(1/R₁ + 1/R₂) beheerst drukverschillen over gekromde interfaces" },
          { en: "Emulsions are always thermodynamically stable", es: "Las emulsiones son siempre termodinámicamente estables", de: "Emulsionen sind immer thermodynamisch stabil", nl: "Emulsies zijn altijd thermodynamisch stabiel" },
          { en: "Surface tension has no effect on emulsions", es: "La tensión superficial no tiene efecto en emulsiones", de: "Oberflächenspannung hat keinen Einfluss auf Emulsionen", nl: "Oppervlaktespanning heeft geen effect op emulsies" },
          { en: "Only particle size matters for stability", es: "Solo el tamaño de partícula importa para estabilidad", de: "Nur Partikelgröße ist wichtig für Stabilität", nl: "Alleen deeltjesgrootte is belangrijk voor stabiliteit" }
        ],
        correct: 0,
        explanation: {
          en: "Emulsion stability depends on interfacial tension between oil and water phases. The Young-Laplace equation ΔP = γ(1/R₁ + 1/R₂) describes pressure difference across curved interfaces, where γ is surface tension and R₁, R₂ are radii of curvature. Lower surface tension (achieved by emulsifiers) reduces Laplace pressure, preventing coalescence. DLVO theory explains colloidal stability through van der Waals attraction and electrostatic repulsion. Emulsifiers reduce interfacial energy and provide steric or electrostatic stabilization, preventing phase separation in juice-oil systems.",
          es: "La estabilidad de emulsión depende de tensión interfacial entre fases de aceite y agua. La ecuación Young-Laplace ΔP = γ(1/R₁ + 1/R₂) describe diferencia de presión a través de interfaces curvadas, donde γ es tensión superficial y R₁, R₂ son radios de curvatura. Menor tensión superficial (lograda por emulsificantes) reduce presión de Laplace, previniendo coalescencia. Teoría DLVO explica estabilidad coloidal a través de atracción van der Waals y repulsión electrostática. Emulsificantes reducen energía interfacial y proporcionan estabilización estérica o electrostática, previniendo separación de fases en sistemas jugo-aceite.",
          de: "Emulsionsstabilität hängt von Grenzflächenspannung zwischen Öl- und Wasserphasen ab. Die Young-Laplace-Gleichung ΔP = γ(1/R₁ + 1/R₂) beschreibt Druckdifferenz über gekrümmte Grenzflächen, wobei γ Oberflächenspannung und R₁, R₂ Krümmungsradien sind. Niedrigere Oberflächenspannung (durch Emulgatoren erreicht) reduziert Laplace-Druck und verhindert Koaleszenz. DLVO-Theorie erklärt kolloidale Stabilität durch van der Waals-Anziehung und elektrostatische Abstoßung. Emulgatoren reduzieren Grenzflächenenergie und bieten sterische oder elektrostatische Stabilisierung, verhindern Phasentrennung in Saft-Öl-Systemen.",
          nl: "Emulsiestabiliteit hangt af van interfaciale spanning tussen olie en water fasen. De Young-Laplace vergelijking ΔP = γ(1/R₁ + 1/R₂) beschrijft drukverschil over gekromde interfaces, waarbij γ oppervlaktespanning is en R₁, R₂ krommingsradius. Lagere oppervlaktespanning (bereikt door emulgatoren) vermindert Laplace druk, voorkomt coalescence. DLVO theorie verklaart colloïdale stabiliteit door van der Waals aantrekking en elektrostatische afstoting. Emulgatoren verminderen interfaciale energie en bieden sterische of elektrostatische stabilisatie, voorkomen fasescheiding in sap-olie systemen."
        }
      },
      {
        question: {
          en: "What is the quantum mechanical basis for UV-Vis spectroscopy in determining anthocyanin concentrations and how do molecular orbitals affect absorption spectra?",
          es: "¿Cuál es la base mecánico-cuántica para espectroscopia UV-Vis en determinar concentraciones de antocianinas y cómo afectan orbitales moleculares los espectros de absorción?",
          de: "Was ist die quantenmechanische Grundlage für UV-Vis-Spektroskopie bei der Bestimmung von Anthocyanin-Konzentrationen und wie beeinflussen Molekülorbitale Absorptionsspektren?",
          nl: "Wat is de kwantummechanische basis voor UV-Vis spectroscopie bij het bepalen van anthocyanine concentraties en hoe beïnvloeden moleculaire orbitalen absorptiespectra?"
        },
        options: [
          { en: "Electronic transitions between HOMO and LUMO orbitals absorb specific wavelengths, Beer-Lambert law A = εbc relates absorbance to concentration", es: "Transiciones electrónicas entre orbitales HOMO y LUMO absorben longitudes de onda específicas, ley Beer-Lambert A = εbc relaciona absorbancia con concentración", de: "Elektronische Übergänge zwischen HOMO- und LUMO-Orbitalen absorbieren spezifische Wellenlängen, Beer-Lambert-Gesetz A = εbc verknüpft Absorption mit Konzentration", nl: "Elektronische overgangen tussen HOMO en LUMO orbitalen absorberen specifieke golflengten, Beer-Lambert wet A = εbc relateert absorptie aan concentratie" },
          { en: "Color is only due to physical light scattering", es: "El color se debe solo a dispersión física de luz", de: "Farbe ist nur auf physikalische Lichtstreuung zurückzuführen", nl: "Kleur is alleen te wijten aan fysieke lichtverstrooiing" },
          { en: "Molecular structure has no effect on absorption", es: "La estructura molecular no tiene efecto en absorción", de: "Molekularstruktur hat keinen Einfluss auf Absorption", nl: "Moleculaire structuur heeft geen effect op absorptie" },
          { en: "All organic compounds absorb the same wavelengths", es: "Todos los compuestos orgánicos absorben las mismas longitudes de onda", de: "Alle organischen Verbindungen absorbieren dieselben Wellenlängen", nl: "Alle organische verbindingen absorberen dezelfde golflengten" }
        ],
        correct: 0,
        explanation: {
          en: "UV-Vis spectroscopy is based on electronic transitions between molecular orbitals. When photons with energy E = hν match the energy gap between highest occupied molecular orbital (HOMO) and lowest unoccupied molecular orbital (LUMO), electrons are promoted to higher energy states. Anthocyanins have extended conjugated π-electron systems that create narrow HOMO-LUMO gaps, absorbing visible light (500-550 nm range). The Beer-Lambert law A = εbc relates absorbance (A) to molar absorptivity (ε), path length (b), and concentration (c), enabling quantitative analysis.",
          es: "La espectroscopia UV-Vis se basa en transiciones electrónicas entre orbitales moleculares. Cuando fotones con energía E = hν coinciden con brecha de energía entre orbital molecular ocupado más alto (HOMO) y orbital molecular no ocupado más bajo (LUMO), electrones son promovidos a estados de mayor energía. Antocianinas tienen sistemas π-electrónicos conjugados extendidos que crean brechas HOMO-LUMO estrechas, absorbiendo luz visible (rango 500-550 nm). La ley Beer-Lambert A = εbc relaciona absorbancia (A) con absortividad molar (ε), longitud de camino (b), y concentración (c), permitiendo análisis cuantitativo.",
          de: "UV-Vis-Spektroskopie basiert auf elektronischen Übergängen zwischen Molekülorbitalen. Wenn Photonen mit Energie E = hν der Energielücke zwischen höchstem besetztem Molekülorbital (HOMO) und niedrigstem unbesetztem Molekülorbital (LUMO) entsprechen, werden Elektronen zu höheren Energiezuständen angeregt. Anthocyane haben ausgedehnte konjugierte π-Elektronensysteme, die schmale HOMO-LUMO-Lücken schaffen und sichtbares Licht (500-550 nm Bereich) absorbieren. Das Beer-Lambert-Gesetz A = εbc verknüpft Absorption (A) mit molarer Absorptivität (ε), Pfadlänge (b) und Konzentration (c), ermöglicht quantitative Analyse.",
          nl: "UV-Vis spectroscopie is gebaseerd op elektronische overgangen tussen moleculaire orbitalen. Wanneer fotonen met energie E = hν overeenkomen met de energiekloof tussen hoogst bezette moleculaire orbitaal (HOMO) en laagst onbezette moleculaire orbitaal (LUMO), worden elektronen gepromoveerd naar hogere energietoestanden. Anthocyanines hebben uitgebreide geconjugeerde π-elektron systemen die smalle HOMO-LUMO kloven creëren, waardoor zichtbaar licht wordt geabsorbeerd (500-550 nm bereik). De Beer-Lambert wet A = εbc relateert absorptie (A) aan molaire absorptiviteit (ε), padlengte (b), en concentratie (c), waardoor kwantitatieve analyse mogelijk wordt."
        }
      },
      {
        question: {
          en: "How does the Arrhenius equation describe enzyme kinetics in fruit juice processing and what is the relationship to transition state theory?",
          es: "¿Cómo describe la ecuación de Arrhenius la cinética enzimática en procesamiento de jugo de frutas y cuál es la relación con teoría de estado de transición?",
          de: "Wie beschreibt die Arrhenius-Gleichung Enzymkinetik in der Fruchtsaftverarbeitung und wie verhält sie sich zur Übergangszustandstheorie?",
          nl: "Hoe beschrijft de Arrhenius vergelijking enzym kinetiek in vruchtensapverwerking en wat is de relatie tot transitie staat theorie?"
        },
        options: [
          { en: "k = Ae^(-Ea/RT) describes temperature dependence, transition state theory k = (kT/h)e^(-ΔG‡/RT) relates to free energy barrier", es: "k = Ae^(-Ea/RT) describe dependencia de temperatura, teoría de estado de transición k = (kT/h)e^(-ΔG‡/RT) se relaciona con barrera de energía libre", de: "k = Ae^(-Ea/RT) beschreibt Temperaturabhängigkeit, Übergangszustandstheorie k = (kT/h)e^(-ΔG‡/RT) bezieht sich auf freie Energiebarriere", nl: "k = Ae^(-Ea/RT) beschrijft temperatuurafhankelijkheid, transitie staat theorie k = (kT/h)e^(-ΔG‡/RT) relateert aan vrije energie barrière" },
          { en: "Enzyme activity is independent of temperature", es: "La actividad enzimática es independiente de la temperatura", de: "Enzymaktivität ist temperaturunabhängig", nl: "Enzymactiviteit is onafhankelijk van temperatuur" },
          { en: "Activation energy has no meaning for enzymes", es: "La energía de activación no tiene significado para enzimas", de: "Aktivierungsenergie hat keine Bedeutung für Enzyme", nl: "Activeringsenergie heeft geen betekenis voor enzymen" },
          { en: "Only concentration affects enzyme kinetics", es: "Solo la concentración afecta la cinética enzimática", de: "Nur Konzentration beeinflusst Enzymkinetik", nl: "Alleen concentratie beïnvloedt enzymkinetiek" }
        ],
        correct: 0,
        explanation: {
          en: "The Arrhenius equation k = Ae^(-Ea/RT) describes how reaction rate constant (k) depends exponentially on temperature, where Ea is activation energy, A is pre-exponential factor, R is gas constant, and T is absolute temperature. Transition state theory provides molecular interpretation: k = (kT/h)e^(-ΔG‡/RT), where ΔG‡ is free energy of activation. For enzymes, this explains temperature optimization - higher temperatures increase molecular motion and enzyme-substrate encounters, but excessive heat denatures enzyme structure, creating optimal temperature ranges for juice processing applications.",
          es: "La ecuación de Arrhenius k = Ae^(-Ea/RT) describe cómo constante de velocidad de reacción (k) depende exponencialmente de temperatura, donde Ea es energía de activación, A es factor pre-exponencial, R es constante de gas, y T es temperatura absoluta. Teoría de estado de transición proporciona interpretación molecular: k = (kT/h)e^(-ΔG‡/RT), donde ΔG‡ es energía libre de activación. Para enzimas, esto explica optimización de temperatura - temperaturas más altas aumentan movimiento molecular y encuentros enzima-sustrato, pero calor excesivo desnaturaliza estructura enzimática, creando rangos de temperatura óptimos para aplicaciones de procesamiento de jugo.",
          de: "Die Arrhenius-Gleichung k = Ae^(-Ea/RT) beschreibt, wie Reaktionsgeschwindigkeitskonstante (k) exponentiell von Temperatur abhängt, wobei Ea Aktivierungsenergie, A Präexponentialfaktor, R Gaskonstante und T absolute Temperatur ist. Übergangszustandstheorie bietet molekulare Interpretation: k = (kT/h)e^(-ΔG‡/RT), wobei ΔG‡ freie Aktivierungsenergie ist. Für Enzyme erklärt dies Temperaturoptimierung - höhere Temperaturen erhöhen molekulare Bewegung und Enzym-Substrat-Begegnungen, aber übermäßige Hitze denaturiert Enzymstruktur, wodurch optimale Temperaturbereiche für Saftverarbeitungsanwendungen entstehen.",
          nl: "De Arrhenius vergelijking k = Ae^(-Ea/RT) beschrijft hoe reactiesnelheidsconstante (k) exponentieel afhangt van temperatuur, waarbij Ea activeringsenergie is, A pre-exponentiële factor, R gasconstante, en T absolute temperatuur. Transitie staat theorie biedt moleculaire interpretatie: k = (kT/h)e^(-ΔG‡/RT), waarbij ΔG‡ vrije activeringsenergie is. Voor enzymen verklaart dit temperatuuroptimalisatie - hogere temperaturen verhogen moleculaire beweging en enzym-substraat ontmoetingen, maar overmatige warmte denatureert enzymstructuur, waardoor optimale temperatuurbereiken voor sapverwerkingstoepassingen ontstaan."
        }
      },
      {
        question: {
          en: "What is the thermodynamic basis for water activity (aw) control in juice stability and how does the Clausius-Clapeyron equation relate to vapor pressure?",
          es: "¿Cuál es la base termodinámica para control de actividad de agua (aw) en estabilidad de jugo y cómo se relaciona la ecuación de Clausius-Clapeyron con presión de vapor?",
          de: "Was ist die thermodynamische Grundlage für Wasseraktivitätskontrolle (aw) in Saftstabilität und wie bezieht sich die Clausius-Clapeyron-Gleichung auf Dampfdruck?",
          nl: "Wat is de thermodynamische basis voor water activiteit (aw) controle in sapstabiliteit en hoe relateert de Clausius-Clapeyron vergelijking aan dampdruk?"
        },
        options: [
          { en: "aw = p/p₀ (vapor pressure ratio), d(ln p)/dT = ΔHvap/RT² describes temperature dependence of vapor pressure", es: "aw = p/p₀ (razón de presión de vapor), d(ln p)/dT = ΔHvap/RT² describe dependencia de temperatura de presión de vapor", de: "aw = p/p₀ (Dampfdruckverhältnis), d(ln p)/dT = ΔHvap/RT² beschreibt Temperaturabhängigkeit des Dampfdrucks", nl: "aw = p/p₀ (dampdruk verhouding), d(ln p)/dT = ΔHvap/RT² beschrijft temperatuurafhankelijkheid van dampdruk" },
          { en: "Water activity is unrelated to thermodynamics", es: "La actividad de agua no está relacionada con termodinámica", de: "Wasseraktivität ist nicht mit Thermodynamik verbunden", nl: "Water activiteit is niet gerelateerd aan thermodynamica" },
          { en: "Only pH affects juice stability", es: "Solo el pH afecta la estabilidad del jugo", de: "Nur pH beeinflusst Saftstabilität", nl: "Alleen pH beïnvloedt sapstabiliteit" },
          { en: "Vapor pressure is constant at all temperatures", es: "La presión de vapor es constante a todas las temperaturas", de: "Dampfdruck ist bei allen Temperaturen konstant", nl: "Dampdruk is constant bij alle temperaturen" }
        ],
        correct: 0,
        explanation: {
          en: "Water activity aw = p/p₀ represents ratio of vapor pressure (p) of water in juice to vapor pressure of pure water (p₀) at same temperature. The Clausius-Clapeyron equation d(ln p)/dT = ΔHvap/RT² relates vapor pressure temperature dependence to enthalpy of vaporization. Low aw (<0.6) prevents microbial growth by limiting water availability. Concentration (sugar addition, evaporation) reduces aw through colligative properties and water molecule binding. Critical for juice concentrate and intermediate moisture products.",
          es: "La actividad de agua aw = p/p₀ representa la razón de presión de vapor (p) de agua en jugo a presión de vapor de agua pura (p₀) a misma temperatura. La ecuación de Clausius-Clapeyron d(ln p)/dT = ΔHvap/RT² relaciona dependencia de temperatura de presión de vapor con entalpía de vaporización. aw baja (<0.6) previene crecimiento microbiano limitando disponibilidad de agua. Concentración (adición de azúcar, evaporación) reduce aw a través de propiedades coligativas y enlace de moléculas de agua. Crítico para concentrado de jugo y productos de humedad intermedia.",
          de: "Wasseraktivität aw = p/p₀ repräsentiert Verhältnis von Dampfdruck (p) von Wasser in Saft zu Dampfdruck reinen Wassers (p₀) bei gleicher Temperatur. Die Clausius-Clapeyron-Gleichung d(ln p)/dT = ΔHvap/RT² verknüpft Dampfdrucktemperaturabhängigkeit mit Verdampfungsenthalpie. Niedrige aw (<0.6) verhindert mikrobielles Wachstum durch Begrenzung der Wasserverfügbarkeit. Konzentration (Zuckerzugabe, Verdampfung) reduziert aw durch kolligative Eigenschaften und Wassermolekülbindung. Kritisch für Saftkonzentrat und Produkte mit mittlerer Feuchtigkeit.",
          nl: "Water activiteit aw = p/p₀ vertegenwoordigt verhouding van dampdruk (p) van water in sap tot dampdruk van zuiver water (p₀) bij dezelfde temperatuur. De Clausius-Clapeyron vergelijking d(ln p)/dT = ΔHvap/RT² relateert dampdruk temperatuurafhankelijkheid aan verdampingsenthalpie. Lage aw (<0.6) voorkomt microbiële groei door water beschikbaarheid te beperken. Concentratie (suiker toevoeging, verdamping) vermindert aw door colligatieve eigenschappen en water molecuul binding. Kritiek voor sapconcentraat en tussenliggende vochtproducten."
        }
      },
      {
        question: {
          en: "How does the Michaelis-Menten equation describe enzyme kinetics in juice processing and what are the implications of competitive vs non-competitive inhibition?",
          es: "¿Cómo describe la ecuación de Michaelis-Menten la cinética enzimática en procesamiento de jugo y cuáles son implicaciones de inhibición competitiva vs no competitiva?",
          de: "Wie beschreibt die Michaelis-Menten-Gleichung Enzymkinetik in der Saftverarbeitung und was sind die Implikationen kompetitiver vs nicht-kompetitiver Hemmung?",
          nl: "Hoe beschrijft de Michaelis-Menten vergelijking enzym kinetiek in sapverwerking en wat zijn de implicaties van competitieve vs niet-competitieve remming?"
        },
        options: [
          { en: "v = Vmax[S]/(Km + [S]); competitive inhibition increases apparent Km, non-competitive decreases Vmax", es: "v = Vmax[S]/(Km + [S]); inhibición competitiva aumenta Km aparente, no competitiva disminuye Vmax", de: "v = Vmax[S]/(Km + [S]); kompetitive Hemmung erhöht scheinbaren Km, nicht-kompetitive verringert Vmax", nl: "v = Vmax[S]/(Km + [S]); competitieve remming verhoogt schijnbare Km, niet-competitieve verlaagt Vmax" },
          { en: "Enzyme kinetics follow zero-order only", es: "Cinética enzimática sigue solo orden cero", de: "Enzymkinetik folgt nur nullter Ordnung", nl: "Enzym kinetiek volgt alleen nulde orde" },
          { en: "Substrate concentration has no effect", es: "Concentración de sustrato no tiene efecto", de: "Substratkonzentration hat keinen Effekt", nl: "Substraat concentratie heeft geen effect" },
          { en: "All inhibitors work identically", es: "Todos los inhibidores funcionan idénticamente", de: "Alle Inhibitoren wirken identisch", nl: "Alle remmers werken identiek" }
        ],
        correct: 0,
        explanation: {
          en: "Michaelis-Menten equation v = Vmax[S]/(Km + [S]) describes enzyme reaction velocity (v) as function of substrate concentration [S], where Vmax is maximum velocity and Km (Michaelis constant) represents substrate concentration at v = Vmax/2. Competitive inhibitors (e.g., citric acid inhibiting polyphenol oxidase) bind active site, increasing apparent Km but not affecting Vmax (overcome by high [S]). Non-competitive inhibitors bind allosteric sites, decreasing Vmax without changing Km. Lineweaver-Burk plots (1/v vs 1/[S]) distinguish mechanisms: competitive shows y-intercept unchanged, non-competitive shows slope unchanged.",
          es: "La ecuación de Michaelis-Menten v = Vmax[S]/(Km + [S]) describe velocidad de reacción enzimática (v) como función de concentración de sustrato [S], donde Vmax es velocidad máxima y Km (constante de Michaelis) representa concentración de sustrato a v = Vmax/2. Inhibidores competitivos (ej., ácido cítrico inhibiendo polifenol oxidasa) unen sitio activo, aumentando Km aparente pero no afectando Vmax (superado por alta [S]). Inhibidores no competitivos unen sitios alostéricos, disminuyendo Vmax sin cambiar Km. Gráficos Lineweaver-Burk (1/v vs 1/[S]) distinguen mecanismos: competitivo muestra intersección y sin cambios, no competitivo muestra pendiente sin cambios.",
          de: "Michaelis-Menten-Gleichung v = Vmax[S]/(Km + [S]) beschreibt Enzymreaktionsgeschwindigkeit (v) als Funktion der Substratkonzentration [S], wobei Vmax maximale Geschwindigkeit und Km (Michaelis-Konstante) Substratkonzentration bei v = Vmax/2 darstellt. Kompetitive Inhibitoren (z.B. Zitronensäure hemmt Polyphenoloxidase) binden aktives Zentrum, erhöhen scheinbares Km ohne Vmax zu beeinflussen (durch hohe [S] überwunden). Nicht-kompetitive Inhibitoren binden allosterische Stellen, verringern Vmax ohne Km zu ändern. Lineweaver-Burk-Diagramme (1/v vs 1/[S]) unterscheiden Mechanismen: kompetitiv zeigt unveränderter y-Achsenabschnitt, nicht-kompetitiv zeigt unveränderter Steigung.",
          nl: "Michaelis-Menten vergelijking v = Vmax[S]/(Km + [S]) beschrijft enzym reactie snelheid (v) als functie van substraat concentratie [S], waarbij Vmax maximum snelheid is en Km (Michaelis constante) substraat concentratie bij v = Vmax/2 vertegenwoordigt. Competitieve remmers (bijv. citroenzuur remmend polyfenol oxidase) binden actieve site, verhogen schijnbare Km maar beïnvloeden Vmax niet (overwonnen door hoge [S]). Niet-competitieve remmers binden allosterische sites, verlagen Vmax zonder Km te veranderen. Lineweaver-Burk plots (1/v vs 1/[S]) onderscheiden mechanismen: competitief toont y-intercept onveranderd, niet-competitief toont helling onveranderd."
        }
      },
      {
        question: {
          en: "What is the molecular mechanism of high-pressure processing (HPP) on protein denaturation and microbial inactivation via Le Chatelier's principle?",
          es: "¿Cuál es el mecanismo molecular de procesamiento de alta presión (HPP) en desnaturalización de proteínas e inactivación microbiana vía principio de Le Chatelier?",
          de: "Was ist der molekulare Mechanismus von Hochdruckverarbeitung (HPP) auf Proteindenaturierung und mikrobielle Inaktivierung über Le Chateliers Prinzip?",
          nl: "Wat is het moleculaire mechanisme van hoge druk verwerking (HPP) op eiwit denaturatie en microbiële inactivatie via Le Chatelier's principe?"
        },
        options: [
          { en: "Pressure (400-600 MPa) shifts equilibrium toward states with smaller volume (ΔV < 0), disrupting hydrophobic interactions and hydrogen bonds", es: "Presión (400-600 MPa) desplaza equilibrio hacia estados con menor volumen (ΔV < 0), interrumpiendo interacciones hidrofóbicas y enlaces de hidrógeno", de: "Druck (400-600 MPa) verschiebt Gleichgewicht zu Zuständen mit kleinerem Volumen (ΔV < 0), stört hydrophobe Wechselwirkungen und Wasserstoffbrücken", nl: "Druk (400-600 MPa) verschuift evenwicht naar toestanden met kleiner volume (ΔV < 0), verstoort hydrofobe interacties en waterstofbruggen" },
          { en: "Pressure only heats the liquid", es: "Presión solo calienta el líquido", de: "Druck erwärmt nur die Flüssigkeit", nl: "Druk verwarmt alleen de vloeistof" },
          { en: "Pressure has no effect on proteins", es: "Presión no tiene efecto en proteínas", de: "Druck hat keinen Effekt auf Proteine", nl: "Druk heeft geen effect op eiwitten" },
          { en: "Only temperature affects microbial inactivation", es: "Solo temperatura afecta inactivación microbiana", de: "Nur Temperatur beeinflusst mikrobielle Inaktivierung", nl: "Alleen temperatuur beïnvloedt microbiële inactivatie" }
        ],
        correct: 0,
        explanation: {
          en: "HPP (400-600 MPa) exploits Le Chatelier's principle: pressure favors states with reduced volume. Protein folding involves hydrophobic core collapse with negative volume change (ΔV < 0). Pressure denatures proteins by disrupting non-covalent interactions (hydrophobic, electrostatic, hydrogen bonds) causing unfolding (positive ΔV). Microbial inactivation occurs through membrane disruption (lipid bilayer compression, phase transitions) and enzyme inactivation. Covalent bonds (disulfides, peptide) remain intact, preserving flavor compounds. Temperature increase is minimal (~3°C per 100 MPa), making HPP a cold pasteurization method.",
          es: "HPP (400-600 MPa) explota principio de Le Chatelier: presión favorece estados con volumen reducido. Plegamiento de proteínas involucra colapso de núcleo hidrofóbico con cambio de volumen negativo (ΔV < 0). Presión desnaturaliza proteínas interrumpiendo interacciones no covalentes (hidrofóbicas, electrostáticas, enlaces de hidrógeno) causando desplegamiento (ΔV positivo). Inactivación microbiana ocurre a través de interrupción de membrana (compresión de bicapa lipídica, transiciones de fase) e inactivación enzimática. Enlaces covalentes (disulfuros, péptido) permanecen intactos, preservando compuestos de sabor. Aumento de temperatura es mínimo (~3°C por 100 MPa), haciendo HPP método de pasteurización en frío.",
          de: "HPP (400-600 MPa) nutzt Le Chateliers Prinzip: Druck begünstigt Zustände mit reduziertem Volumen. Proteinfaltung beinhaltet hydrophoben Kernkollaps mit negativer Volumenänderung (ΔV < 0). Druck denaturiert Proteine durch Störung nicht-kovalenter Wechselwirkungen (hydrophob, elektrostatisch, Wasserstoffbrücken), verursacht Entfaltung (positives ΔV). Mikrobielle Inaktivierung erfolgt durch Membranstörung (Lipiddoppelschichtkompression, Phasenübergänge) und Enzyminaktivierung. Kovalente Bindungen (Disulfide, Peptid) bleiben intakt, bewahren Geschmacksverbindungen. Temperaturanstieg ist minimal (~3°C pro 100 MPa), macht HPP zu kalter Pasteurisierungsmethode.",
          nl: "HPP (400-600 MPa) benut Le Chatelier's principe: druk begunstigt toestanden met verminderd volume. Eiwit vouwen omvat hydrofobe kern ineenstorting met negatieve volume verandering (ΔV < 0). Druk denatureert eiwitten door niet-covalente interacties (hydrofoob, elektrostatisch, waterstofbruggen) te verstoren wat ontvouwing veroorzaakt (positief ΔV). Microbiële inactivatie vindt plaats door membraan verstoring (lipide dubbellaag compressie, fase overgangen) en enzym inactivatie. Covalente bindingen (disulfiden, peptide) blijven intact, behouden smaakverbindingen. Temperatuurstijging is minimaal (~3°C per 100 MPa), maakt HPP een koude pasteurisatie methode."
        }
      },
      {
        question: {
          en: "How does the Flory-Huggins theory describe polymer solution behavior in pectin-stabilized juice systems?",
          es: "¿Cómo describe la teoría de Flory-Huggins el comportamiento de solución de polímero en sistemas de jugo estabilizados con pectina?",
          de: "Wie beschreibt die Flory-Huggins-Theorie Polymerlösungsverhalten in pektinstabilisierten Saftsystemen?",
          nl: "Hoe beschrijft de Flory-Huggins theorie polymeer oplossing gedrag in pectine-gestabiliseerde sapsystemen?"
        },
        options: [
          { en: "ΔGmix/RT = (n₁/N₁)ln φ₁ + (n₂/N₂)ln φ₂ + χφ₁φ₂ describes mixing thermodynamics; χ parameter controls phase separation", es: "ΔGmix/RT = (n₁/N₁)ln φ₁ + (n₂/N₂)ln φ₂ + χφ₁φ₂ describe termodinámica de mezcla; parámetro χ controla separación de fase", de: "ΔGmix/RT = (n₁/N₁)ln φ₁ + (n₂/N₂)ln φ₂ + χφ₁φ₂ beschreibt Mischungsthermodynamik; χ-Parameter kontrolliert Phasenseparation", nl: "ΔGmix/RT = (n₁/N₁)ln φ₁ + (n₂/N₂)ln φ₂ + χφ₁φ₂ beschrijft menging thermodynamica; χ parameter controleert fase scheiding" },
          { en: "Polymers behave identically to small molecules", es: "Polímeros se comportan idénticamente a moléculas pequeñas", de: "Polymere verhalten sich identisch wie kleine Moleküle", nl: "Polymeren gedragen zich identiek aan kleine moleculen" },
          { en: "Pectin has no thermodynamic interactions", es: "Pectina no tiene interacciones termodinámicas", de: "Pektin hat keine thermodynamischen Wechselwirkungen", nl: "Pectine heeft geen thermodynamische interacties" },
          { en: "Concentration has no effect on stability", es: "Concentración no tiene efecto en estabilidad", de: "Konzentration hat keinen Effekt auf Stabilität", nl: "Concentratie heeft geen effect op stabiliteit" }
        ],
        correct: 0,
        explanation: {
          en: "Flory-Huggins theory describes polymer-solvent mixing thermodynamics: ΔGmix/RT = (n₁/N₁)ln φ₁ + (n₂/N₂)ln φ₂ + χφ₁φ₂, where φ is volume fraction, n is moles, N is degree of polymerization, and χ is interaction parameter. For pectin-water systems, χ depends on temperature, pH, ionic strength. When χ > 0.5, polymer-polymer interactions dominate over polymer-solvent, causing phase separation (cloud instability). Low χ (good solvent conditions) promotes stable cloud. Degree of esterification affects pectin-water χ: high-methoxyl pectin (HM) has higher χ than low-methoxyl (LM). Theory explains calcium-induced gelation and depletion flocculation phenomena.",
          es: "La teoría de Flory-Huggins describe termodinámica de mezcla polímero-solvente: ΔGmix/RT = (n₁/N₁)ln φ₁ + (n₂/N₂)ln φ₂ + χφ₁φ₂, donde φ es fracción de volumen, n es moles, N es grado de polimerización, y χ es parámetro de interacción. Para sistemas pectina-agua, χ depende de temperatura, pH, fuerza iónica. Cuando χ > 0.5, interacciones polímero-polímero dominan sobre polímero-solvente, causando separación de fase (inestabilidad de nube). χ bajo (buenas condiciones de solvente) promueve nube estable. Grado de esterificación afecta χ pectina-agua: pectina alta metoxilada (HM) tiene χ mayor que baja metoxilada (LM). Teoría explica gelificación inducida por calcio y fenómenos de floculación por agotamiento.",
          de: "Flory-Huggins-Theorie beschreibt Polymer-Lösungsmittel-Mischungsthermodynamik: ΔGmix/RT = (n₁/N₁)ln φ₁ + (n₂/N₂)ln φ₂ + χφ₁φ₂, wobei φ Volumenanteil, n Mol, N Polymerisationsgrad und χ Wechselwirkungsparameter ist. Für Pektin-Wasser-Systeme hängt χ von Temperatur, pH, Ionenstärke ab. Wenn χ > 0.5, dominieren Polymer-Polymer-Wechselwirkungen über Polymer-Lösungsmittel, verursacht Phasenseparation (Wolkeninstabilität). Niedriges χ (gute Lösungsmittelbedingungen) fördert stabile Wolke. Veresterungsgrad beeinflusst Pektin-Wasser-χ: Hochmethyliertes Pektin (HM) hat höheres χ als niedrigmethyliertes (LM). Theorie erklärt calciuminduzierte Gelierung und Verarmungsflockulationsphänomene.",
          nl: "Flory-Huggins theorie beschrijft polymeer-oplosmiddel menging thermodynamica: ΔGmix/RT = (n₁/N₁)ln φ₁ + (n₂/N₂)ln φ₂ + χφ₁φ₂, waarbij φ volumefractie is, n mol, N polymerisatiegraad, en χ interactie parameter. Voor pectine-water systemen hangt χ af van temperatuur, pH, ionsterkte. Wanneer χ > 0.5, domineren polymeer-polymeer interacties over polymeer-oplosmiddel, veroorzakend fase scheiding (wolk instabiliteit). Lage χ (goede oplosmiddel condities) bevordert stabiele wolk. Veresteringsgraad beïnvloedt pectine-water χ: hoog-methoxyl pectine (HM) heeft hogere χ dan laag-methoxyl (LM). Theorie verklaart calcium-geïnduceerde gelering en depletie flocculatie fenomenen."
        }
      },
      {
        question: {
          en: "What is the quantum yield of photodegradation reactions in vitamin C and how does it relate to reactive oxygen species generation?",
          es: "¿Cuál es el rendimiento cuántico de reacciones de fotodegradación en vitamina C y cómo se relaciona con generación de especies reactivas de oxígeno?",
          de: "Was ist die Quantenausbeute von Photoabbaureaktionen bei Vitamin C und wie bezieht sie sich auf Erzeugung reaktiver Sauerstoffspezies?",
          nl: "Wat is de kwantumopbrengst van fotodegradatie reacties in vitamine C en hoe relateert het aan reactieve zuurstof species generatie?"
        },
        options: [
          { en: "Φ = molecules degraded/photons absorbed; UV radiation (λ<400nm) generates ¹O₂, •OH radicals causing chain oxidation", es: "Φ = moléculas degradadas/fotones absorbidos; radiación UV (λ<400nm) genera ¹O₂, radicales •OH causando oxidación en cadena", de: "Φ = abgebaute Moleküle/absorbierte Photonen; UV-Strahlung (λ<400nm) erzeugt ¹O₂, •OH-Radikale, verursacht Kettenoxidation", nl: "Φ = afgebroken moleculen/geabsorbeerde fotonen; UV straling (λ<400nm) genereert ¹O₂, •OH radicalen veroorzakend keten oxidatie" },
          { en: "Light has no effect on vitamin stability", es: "Luz no tiene efecto en estabilidad de vitaminas", de: "Licht hat keinen Effekt auf Vitaminstabilität", nl: "Licht heeft geen effect op vitamine stabiliteit" },
          { en: "Only temperature affects vitamin degradation", es: "Solo temperatura afecta degradación de vitaminas", de: "Nur Temperatur beeinflusst Vitaminabbau", nl: "Alleen temperatuur beïnvloedt vitamine afbraak" },
          { en: "Quantum yield is always 100%", es: "Rendimiento cuántico es siempre 100%", de: "Quantenausbeute ist immer 100%", nl: "Kwantumopbrengst is altijd 100%" }
        ],
        correct: 0,
        explanation: {
          en: "Quantum yield Φ = number of molecules degraded per photon absorbed measures photochemical efficiency. For ascorbic acid, UV light (λ<400nm) absorption promotes electrons to excited states. Energy transfer to O₂ generates singlet oxygen (¹O₂) and hydroxyl radicals (•OH) through photosensitization. These reactive oxygen species (ROS) initiate chain oxidation: ascorbic acid → dehydroascorbic acid → 2,3-diketogulonic acid → furfural compounds (browning). Φ typically 0.01-0.1 for vitamin C, meaning chain reactions amplify damage. Protection: opaque/amber packaging, UV-blocking additives (flavonoids), oxygen scavengers, refrigeration to slow propagation steps.",
          es: "Rendimiento cuántico Φ = número de moléculas degradadas por fotón absorbido mide eficiencia fotoquímica. Para ácido ascórbico, absorción de luz UV (λ<400nm) promueve electrones a estados excitados. Transferencia de energía a O₂ genera oxígeno singlete (¹O₂) y radicales hidroxilo (•OH) a través de fotosensibilización. Estas especies reactivas de oxígeno (ROS) inician oxidación en cadena: ácido ascórbico → ácido deshidroascórbico → ácido 2,3-dicetogulónico → compuestos furfurales (pardeamiento). Φ típicamente 0.01-0.1 para vitamina C, significando reacciones en cadena amplifican daño. Protección: empaque opaco/ámbar, aditivos bloqueadores UV (flavonoides), secuestradores de oxígeno, refrigeración para ralentizar pasos de propagación.",
          de: "Quantenausbeute Φ = Anzahl abgebauter Moleküle pro absorbiertem Photon misst photochemische Effizienz. Für Ascorbinsäure fördert UV-Lichtabsorption (λ<400nm) Elektronen zu angeregten Zuständen. Energietransfer auf O₂ erzeugt Singulett-Sauerstoff (¹O₂) und Hydroxylradikale (•OH) durch Photosensibilisierung. Diese reaktiven Sauerstoffspezies (ROS) initiieren Kettenoxidation: Ascorbinsäure → Dehydroascorbinsäure → 2,3-Diketogulonsäure → Furfuralverbindungen (Bräunung). Φ typischerweise 0.01-0.1 für Vitamin C, bedeutet Kettenreaktionen verstärken Schaden. Schutz: opake/Bernsteinverpackung, UV-blockierende Zusätze (Flavonoide), Sauerstofffänger, Kühlung zur Verlangsamung von Propagationsschritten.",
          nl: "Kwantumopbrengst Φ = aantal afgebroken moleculen per geabsorbeerd foton meet fotochemische efficiëntie. Voor ascorbinezuur bevordert UV-licht (λ<400nm) absorptie elektronen naar aangeslagen toestanden. Energie overdracht aan O₂ genereert singlet zuurstof (¹O₂) en hydroxyl radicalen (•OH) door fotosensitisatie. Deze reactieve zuurstof species (ROS) initiëren keten oxidatie: ascorbinezuur → dehydroascorbinezuur → 2,3-diketogulonzuur → furfural verbindingen (bruinering). Φ typisch 0.01-0.1 voor vitamine C, betekent keten reacties versterken schade. Bescherming: ondoorzichtige/amber verpakking, UV-blokkerende additieven (flavonoïden), zuurstof scavengers, koeling om propagatie stappen te vertragen."
        }
      },
      {
        question: {
          en: "How does the Stokes-Einstein equation relate to diffusion-limited enzyme kinetics and mass transfer in juice clarification?",
          es: "¿Cómo se relaciona la ecuación de Stokes-Einstein con cinética enzimática limitada por difusión y transferencia de masa en clarificación de jugo?",
          de: "Wie bezieht sich die Stokes-Einstein-Gleichung auf diffusionslimitierte Enzymkinetik und Stofftransfer in Saftkla¨rung?",
          nl: "Hoe relateert de Stokes-Einstein vergelijking aan diffusie-gelimiteerde enzym kinetiek en massa overdracht in sapklarering?"
        },
        options: [
          { en: "D = kT/(6πηr) relates diffusion coefficient to viscosity; kcat/Km approaches diffusion limit ~10⁸-10⁹ M⁻¹s⁻¹", es: "D = kT/(6πηr) relaciona coeficiente de difusión con viscosidad; kcat/Km se aproxima a límite de difusión ~10⁸-10⁹ M⁻¹s⁻¹", de: "D = kT/(6πηr) verknüpft Diffusionskoeffizient mit Viskosität; kcat/Km nähert sich Diffusionsgrenze ~10⁸-10⁹ M⁻¹s⁻¹", nl: "D = kT/(6πηr) relateert diffusie coëfficiënt aan viscositeit; kcat/Km benadert diffusie limiet ~10⁸-10⁹ M⁻¹s⁻¹" },
          { en: "Diffusion is independent of temperature", es: "Difusión es independiente de temperatura", de: "Diffusion ist temperaturunabhängig", nl: "Diffusie is onafhankelijk van temperatuur" },
          { en: "Viscosity has no effect on reactions", es: "Viscosidad no tiene efecto en reacciones", de: "Viskosität hat keinen Effekt auf Reaktionen", nl: "Viscositeit heeft geen effect op reacties" },
          { en: "Enzymes always work at maximum rate", es: "Enzimas siempre trabajan a velocidad máxima", de: "Enzyme arbeiten immer mit maximaler Rate", nl: "Enzymen werken altijd op maximum snelheid" }
        ],
        correct: 0,
        explanation: {
          en: "Stokes-Einstein equation D = kT/(6πηr) relates diffusion coefficient (D) to temperature (T), viscosity (η), and particle radius (r), where k is Boltzmann constant. For pectinase clarification, substrate (pectin) and product diffusion to/from enzyme active site can be rate-limiting. Maximum enzyme efficiency kcat/Km is diffusion-limited at ~10⁸-10⁹ M⁻¹s⁻¹ (Smoluchowski limit). High juice viscosity (high pulp, concentrated) reduces D, slowing clarification. Solutions: temperature increase (reduces η), mechanical agitation (reduces boundary layer), enzyme immobilization on supports (enhances local substrate concentration). Critical for optimizing industrial clarification residence times.",
          es: "La ecuación de Stokes-Einstein D = kT/(6πηr) relaciona coeficiente de difusión (D) con temperatura (T), viscosidad (η), y radio de partícula (r), donde k es constante de Boltzmann. Para clarificación con pectinasa, difusión de sustrato (pectina) y producto hacia/desde sitio activo de enzima puede ser limitante de velocidad. Eficiencia enzimática máxima kcat/Km está limitada por difusión a ~10⁸-10⁹ M⁻¹s⁻¹ (límite de Smoluchowski). Alta viscosidad de jugo (alta pulpa, concentrado) reduce D, ralentizando clarificación. Soluciones: aumento de temperatura (reduce η), agitación mecánica (reduce capa límite), inmovilización de enzima en soportes (mejora concentración de sustrato local). Crítico para optimizar tiempos de residencia de clarificación industrial.",
          de: "Stokes-Einstein-Gleichung D = kT/(6πηr) verknüpft Diffusionskoeffizienten (D) mit Temperatur (T), Viskosität (η) und Partikelradius (r), wobei k Boltzmann-Konstante ist. Für Pektinase-Klärung kann Substrat-(Pektin) und Produktdiffusion zum/vom Enzymaktiven Zentrum geschwindigkeitsbegrenzend sein. Maximale Enzymeffizienz kcat/Km ist diffusionslimitiert bei ~10⁸-10⁹ M⁻¹s⁻¹ (Smoluchowski-Grenze). Hohe Saftviskosität (hohe Pulpa, konzentriert) reduziert D, verlangsamt Klärung. Lösungen: Temperaturerhöhung (reduziert η), mechanische Rührung (reduziert Grenzschicht), Enzymimmobilisierung auf Trägern (verbessert lokale Substratkonzentration). Kritisch für Optimierung industrieller Klärverweilzeiten.",
          nl: "Stokes-Einstein vergelijking D = kT/(6πηr) relateert diffusie coëfficiënt (D) aan temperatuur (T), viscositeit (η), en deeltjesradius (r), waarbij k Boltzmann constante is. Voor pectinase klaring kan substraat (pectine) en product diffusie naar/van enzym actieve site snelheidsbepalend zijn. Maximum enzym efficiëntie kcat/Km is diffusie-gelimiteerd bij ~10⁸-10⁹ M⁻¹s⁻¹ (Smoluchowski limiet). Hoge sap viscositeit (hoge pulp, geconcentreerd) vermindert D, vertraagt klaring. Oplossingen: temperatuur verhoging (vermindert η), mechanische agitatie (vermindert grenslaag), enzym immobilisatie op dragers (verbetert lokale substraat concentratie). Kritiek voor optimaliseren industriële klaring verblijftijden."
        }
      },
      {
        question: {
          en: "What is the role of Gibbs free energy in membrane filtration driving force and how does it relate to osmotic pressure?",
          es: "¿Cuál es el papel de energía libre de Gibbs en fuerza impulsora de filtración por membrana y cómo se relaciona con presión osmótica?",
          de: "Welche Rolle spielt Gibbs freie Energie bei der Antriebskraft der Membranfiltration und wie bezieht sie sich auf osmotischen Druck?",
          nl: "Wat is de rol van Gibbs vrije energie in membraan filtratie drijfkracht en hoe relateert het aan osmotische druk?"
        },
        options: [
          { en: "ΔG = -RT ln(c₁/c₂); transmembrane pressure ΔP must exceed osmotic pressure π = cRT to drive flux", es: "ΔG = -RT ln(c₁/c₂); presión transmembrana ΔP debe exceder presión osmótica π = cRT para impulsar flujo", de: "ΔG = -RT ln(c₁/c₂); Transmembrandruck ΔP muss osmotischen Druck π = cRT überschreiten, um Fluss anzutreiben", nl: "ΔG = -RT ln(c₁/c₂); transmembraan druk ΔP moet osmotische druk π = cRT overtreffen om flux te drijven" },
          { en: "Free energy is irrelevant to filtration", es: "Energía libre es irrelevante para filtración", de: "Freie Energie ist irrelevant für Filtration", nl: "Vrije energie is irrelevant voor filtratie" },
          { en: "Only mechanical pressure matters", es: "Solo presión mecánica importa", de: "Nur mechanischer Druck ist wichtig", nl: "Alleen mechanische druk is belangrijk" },
          { en: "Concentration has no thermodynamic effect", es: "Concentración no tiene efecto termodinámico", de: "Konzentration hat keinen thermodynamischen Effekt", nl: "Concentratie heeft geen thermodynamisch effect" }
        ],
        correct: 0,
        explanation: {
          en: "Gibbs free energy change ΔG = -RT ln(c₁/c₂) quantifies spontaneity of concentration gradients. For reverse osmosis juice concentration, applied pressure ΔP must overcome osmotic pressure π = cRT (van't Hoff equation, where c is solute concentration). Effective driving force: ΔPeff = ΔP - Δπ. As concentration increases during filtration, π rises, reducing flux (concentration polarization). Limiting flux J = k ln(cw/cb), where cw is wall concentration, cb is bulk. High sugar content in juice generates significant π (5-10 bar at 10-20°Brix), requiring higher operating pressures (40-80 bar RO). Energy efficiency optimization balances pressure requirements against concentration polarization and fouling.",
          es: "Cambio de energía libre de Gibbs ΔG = -RT ln(c₁/c₂) cuantifica espontaneidad de gradientes de concentración. Para concentración de jugo por ósmosis inversa, presión aplicada ΔP debe superar presión osmótica π = cRT (ecuación van't Hoff, donde c es concentración de soluto). Fuerza impulsora efectiva: ΔPeff = ΔP - Δπ. A medida que concentración aumenta durante filtración, π aumenta, reduciendo flujo (polarización de concentración). Flujo limitante J = k ln(cw/cb), donde cw es concentración de pared, cb es a granel. Alto contenido de azúcar en jugo genera π significativa (5-10 bar a 10-20°Brix), requiriendo presiones operativas más altas (40-80 bar RO). Optimización de eficiencia energética equilibra requisitos de presión contra polarización de concentración y ensuciamiento.",
          de: "Änderung der Gibbs freien Energie ΔG = -RT ln(c₁/c₂) quantifiziert Spontaneität von Konzentrationsgradienten. Für Umkehrosmose-Saftkonzentration muss angelegter Druck ΔP osmotischen Druck π = cRT überschreiten (van't Hoff-Gleichung, wobei c Gelöstkonzentration ist). Effektive Antriebskraft: ΔPeff = ΔP - Δπ. Mit steigender Konzentration während Filtration steigt π, reduziert Fluss (Konzentrationspolarisation). Begrenzender Fluss J = k ln(cw/cb), wobei cw Wandkonzentration, cb Volumenkonzentration ist. Hoher Zuckergehalt in Saft erzeugt signifikanten π (5-10 bar bei 10-20°Brix), erfordert höhere Betriebsdrücke (40-80 bar RO). Energieeffizienzoptimierung gleicht Druckanforderungen gegen Konzentrationspolarisation und Fouling aus.",
          nl: "Gibbs vrije energie verandering ΔG = -RT ln(c₁/c₂) kwantificeert spontaniteit van concentratie gradiënten. Voor omgekeerde osmose sapconcentratie moet toegepaste druk ΔP osmotische druk π = cRT overtreffen (van't Hoff vergelijking, waarbij c opgeloste stof concentratie is). Effectieve drijfkracht: ΔPeff = ΔP - Δπ. Naarmate concentratie toeneemt tijdens filtratie, stijgt π, vermindert flux (concentratie polarisatie). Beperkende flux J = k ln(cw/cb), waarbij cw wand concentratie is, cb bulk. Hoog suikergehalte in sap genereert significante π (5-10 bar bij 10-20°Brix), vereist hogere bedrijfsdrukken (40-80 bar RO). Energie efficiëntie optimalisatie balanceert druk vereisten tegen concentratie polarisatie en fouling."
        }
      },
      {
        question: {
          en: "How does the D-value and z-value relate to thermal death kinetics and how are they derived from Arrhenius parameters?",
          es: "¿Cómo se relacionan valor-D y valor-z con cinética de muerte térmica y cómo se derivan de parámetros de Arrhenius?",
          de: "Wie beziehen sich D-Wert und z-Wert auf thermische Absterbekinetik und wie werden sie aus Arrhenius-Parametern abgeleitet?",
          nl: "Hoe relateren D-waarde en z-waarde aan thermische dood kinetiek en hoe worden ze afgeleid van Arrhenius parameters?"
        },
        options: [
          { en: "D = time for 1-log reduction at temperature T; z = temperature change for 10-fold D change; z = 2.303RT²/Ea", es: "D = tiempo para reducción 1-log a temperatura T; z = cambio de temperatura para cambio de D 10 veces; z = 2.303RT²/Ea", de: "D = Zeit für 1-log-Reduktion bei Temperatur T; z = Temperaturänderung für 10-fache D-Änderung; z = 2.303RT²/Ea", nl: "D = tijd voor 1-log reductie bij temperatuur T; z = temperatuur verandering voor 10-voudig D verandering; z = 2.303RT²/Ea" },
          { en: "D-value is constant at all temperatures", es: "Valor-D es constante a todas temperaturas", de: "D-Wert ist bei allen Temperaturen konstant", nl: "D-waarde is constant bij alle temperaturen" },
          { en: "z-value has no relationship to activation energy", es: "Valor-z no tiene relación con energía de activación", de: "z-Wert hat keine Beziehung zu Aktivierungsenergie", nl: "z-waarde heeft geen relatie met activeringsenergie" },
          { en: "Thermal processing is temperature-independent", es: "Procesamiento térmico es independiente de temperatura", de: "Thermische Verarbeitung ist temperaturunabhängig", nl: "Thermische verwerking is temperatuur-onafhankelijk" }
        ],
        correct: 0,
        explanation: {
          en: "D-value (decimal reduction time) is time at temperature T to reduce microbial population by 90% (1-log). Follows first-order kinetics: log(N/N₀) = -t/D. z-value is temperature change causing 10-fold D-value change: log(D₁/D₂) = (T₂-T₁)/z. Relates to Arrhenius activation energy: z = 2.303RT²/Ea (approximately at reference temperature). For juice pasteurization, E. coli D₇₂°C ≈ 0.2s, z ≈ 5°C; enables calculation of equivalent thermal processes: F = Σ(10^((T-Tref)/z) × Δt). Allows HTST optimization: shorter time at higher temperature achieves same lethality (F₀) while better preserving quality. Critical for FDA/HACCP process validation.",
          es: "Valor-D (tiempo de reducción decimal) es tiempo a temperatura T para reducir población microbiana en 90% (1-log). Sigue cinética de primer orden: log(N/N₀) = -t/D. Valor-z es cambio de temperatura causando cambio de valor-D 10 veces: log(D₁/D₂) = (T₂-T₁)/z. Se relaciona con energía de activación de Arrhenius: z = 2.303RT²/Ea (aproximadamente a temperatura de referencia). Para pasteurización de jugo, E. coli D₇₂°C ≈ 0.2s, z ≈ 5°C; permite cálculo de procesos térmicos equivalentes: F = Σ(10^((T-Tref)/z) × Δt). Permite optimización HTST: tiempo más corto a mayor temperatura logra misma letalidad (F₀) preservando mejor calidad. Crítico para validación de proceso FDA/HACCP.",
          de: "D-Wert (Dezimalreduktionszeit) ist Zeit bei Temperatur T zur Reduktion mikrobieller Population um 90% (1-log). Folgt Kinetik erster Ordnung: log(N/N₀) = -t/D. z-Wert ist Temperaturänderung, die 10-fache D-Wert-Änderung verursacht: log(D₁/D₂) = (T₂-T₁)/z. Bezieht sich auf Arrhenius-Aktivierungsenergie: z = 2.303RT²/Ea (ungefähr bei Referenztemperatur). Für Saftpasteurisierung, E. coli D₇₂°C ≈ 0.2s, z ≈ 5°C; ermöglicht Berechnung äquivalenter thermischer Prozesse: F = Σ(10^((T-Tref)/z) × Δt). Ermöglicht HTST-Optimierung: kürzere Zeit bei höherer Temperatur erreicht gleiche Letalität (F₀) bei besserer Qualitätserhaltung. Kritisch für FDA/HACCP-Prozessvalidierung.",
          nl: "D-waarde (decimale reductie tijd) is tijd bij temperatuur T om microbiële populatie te reduceren met 90% (1-log). Volgt eerste-orde kinetiek: log(N/N₀) = -t/D. z-waarde is temperatuur verandering veroorzakend 10-voudige D-waarde verandering: log(D₁/D₂) = (T₂-T₁)/z. Relateert aan Arrhenius activeringsenergie: z = 2.303RT²/Ea (ongeveer bij referentie temperatuur). Voor sappasteurisatie, E. coli D₇₂°C ≈ 0.2s, z ≈ 5°C; maakt berekening van equivalente thermische processen mogelijk: F = Σ(10^((T-Tref)/z) × Δt). Staat HTST optimalisatie toe: kortere tijd bij hogere temperatuur bereikt zelfde letaliteit (F₀) terwijl kwaliteit beter behouden blijft. Kritiek voor FDA/HACCP proces validatie."
        }
      },
      {
        question: {
          en: "What is the molecular basis for anthocyanin color changes with pH and how does the flavylium cation equilibrium system work?",
          es: "¿Cuál es la base molecular para cambios de color de antocianinas con pH y cómo funciona el sistema de equilibrio de catión flavilio?",
          de: "Was ist die molekulare Grundlage für Anthocyanin-Farbänderungen mit pH und wie funktioniert das Flavylium-Kation-Gleichgewichtssystem?",
          nl: "Wat is de moleculaire basis voor anthocyanine kleur veranderingen met pH en hoe werkt het flavylium kation evenwicht systeem?"
        },
        options: [
          { en: "pH controls equilibrium: flavylium cation (red, pH<2) ⇌ quinoidal bases (purple, pH 3-6) ⇌ chalcones (colorless, pH>7)", es: "pH controla equilibrio: catión flavilio (rojo, pH<2) ⇌ bases quinoidales (púrpura, pH 3-6) ⇌ chalconas (incoloro, pH>7)", de: "pH kontrolliert Gleichgewicht: Flavylium-Kation (rot, pH<2) ⇌ Chinoide Basen (lila, pH 3-6) ⇌ Chalkone (farblos, pH>7)", nl: "pH controleert evenwicht: flavylium kation (rood, pH<2) ⇌ quinoidale basen (paars, pH 3-6) ⇌ chalconen (kleurloos, pH>7)" },
          { en: "pH has no effect on anthocyanin structure", es: "pH no tiene efecto en estructura de antocianinas", de: "pH hat keinen Effekt auf Anthocyanin-Struktur", nl: "pH heeft geen effect op anthocyanine structuur" },
          { en: "All anthocyanins are always red", es: "Todas las antocianinas son siempre rojas", de: "Alle Anthocyane sind immer rot", nl: "Alle anthocyanines zijn altijd rood" },
          { en: "Color is only due to concentration", es: "Color se debe solo a concentración", de: "Farbe ist nur auf Konzentration zurückzuführen", nl: "Kleur is alleen te wijten aan concentratie" }
        ],
        correct: 0,
        explanation: {
          en: "Anthocyanins undergo pH-dependent structural transformations through flavylium cation equilibrium. At pH<2: red flavylium cation (AH⁺) predominates with oxonium ion. pH 2-4: hydration forms colorless carbinol pseudobase. pH 4-6: deprotonation yields purple/blue quinoidal bases (A). pH>7: ring opening produces colorless chalcone. Equilibrium constants: pKa1 ≈ 2-4 (flavylium → carbinol), pKa2 ≈ 6-7 (quinoidal base). Copigmentation (stacking with polyphenols/metals) shifts equilibrium, stabilizing colored forms at higher pH. Critical for juice color stability: acidic pH maintains red color, buffer capacity prevents shifts during storage/processing. HOMO-LUMO gap changes with protonation state, altering λmax (absorption wavelength).",
          es: "Las antocianinas sufren transformaciones estructurales dependientes de pH a través de equilibrio de catión flavilio. A pH<2: catión flavilio rojo (AH⁺) predomina con ion oxonio. pH 2-4: hidratación forma pseudobase carbinol incolora. pH 4-6: desprotonación produce bases quinoidales púrpuras/azules (A). pH>7: apertura de anillo produce chalcona incolora. Constantes de equilibrio: pKa1 ≈ 2-4 (flavilio → carbinol), pKa2 ≈ 6-7 (base quinoidal). Copigmentación (apilamiento con polifenoles/metales) desplaza equilibrio, estabilizando formas coloreadas a pH más alto. Crítico para estabilidad de color de jugo: pH ácido mantiene color rojo, capacidad buffer previene cambios durante almacenamiento/procesamiento. Brecha HOMO-LUMO cambia con estado de protonación, alterando λmax (longitud de onda de absorción).",
          de: "Anthocyane durchlaufen pH-abhängige strukturelle Transformationen durch Flavylium-Kation-Gleichgewicht. Bei pH<2: rotes Flavylium-Kation (AH⁺) überwiegt mit Oxoniumion. pH 2-4: Hydratation bildet farbloses Carbinol-Pseudobase. pH 4-6: Deprotonierung ergibt lila/blaue Chinoide Basen (A). pH>7: Ringöffnung produziert farbloses Chalkon. Gleichgewichtskonstanten: pKa1 ≈ 2-4 (Flavylium → Carbinol), pKa2 ≈ 6-7 (Chinoide Base). Copigmentierung (Stapeln mit Polyphenolen/Metallen) verschiebt Gleichgewicht, stabilisiert farbige Formen bei höherem pH. Kritisch für Saftfarbstabilität: saurer pH erhält rote Farbe, Pufferkapazität verhindert Verschiebungen während Lagerung/Verarbeitung. HOMO-LUMO-Lücke ändert sich mit Protonierungszustand, verändert λmax (Absorptionswellenlänge).",
          nl: "Anthocyanines ondergaan pH-afhankelijke structurele transformaties door flavylium kation evenwicht. Bij pH<2: rood flavylium kation (AH⁺) overheerst met oxonium ion. pH 2-4: hydratie vormt kleurloze carbinol pseudobase. pH 4-6: deprotonatie levert paarse/blauwe quinoidale basen (A). pH>7: ring opening produceert kleurloze chalcon. Evenwichtsconstanten: pKa1 ≈ 2-4 (flavylium → carbinol), pKa2 ≈ 6-7 (quinoidale base). Copigmentatie (stapelen met polyfenolen/metalen) verschuift evenwicht, stabiliseert gekleurde vormen bij hogere pH. Kritiek voor sapkleur stabiliteit: zure pH handhaaft rode kleur, buffercapaciteit voorkomt verschuivingen tijdens opslag/verwerking. HOMO-LUMO kloof verandert met protoneringsstatus, wijzigt λmax (absorptie golflengte)."
        }
      },
      {
        question: {
          en: "How does colloidal stability theory (DLVO) explain juice cloud stability and the role of electrostatic vs van der Waals forces?",
          es: "¿Cómo explica la teoría de estabilidad coloidal (DLVO) la estabilidad de nube de jugo y el papel de fuerzas electrostáticas vs van der Waals?",
          de: "Wie erklärt kolloidale Stabilitätstheorie (DLVO) Saftwolkenstabilität und die Rolle elektrostatischer vs van der Waals Kräfte?",
          nl: "Hoe verklaart colloïdale stabiliteit theorie (DLVO) sapwolk stabiliteit en de rol van elektrostatische vs van der Waals krachten?"
        },
        options: [
          { en: "VT = VR + VA; electrostatic repulsion VR = εψ²e^(-κr) vs attractive VA = -A/(12πr²) creates energy barrier preventing aggregation", es: "VT = VR + VA; repulsión electrostática VR = εψ²e^(-κr) vs atractiva VA = -A/(12πr²) crea barrera de energía previniendo agregación", de: "VT = VR + VA; elektrostatische Abstoßung VR = εψ²e^(-κr) vs anziehende VA = -A/(12πr²) schafft Energiebarriere, die Aggregation verhindert", nl: "VT = VR + VA; elektrostatische afstoting VR = εψ²e^(-κr) vs aantrekkende VA = -A/(12πr²) creëert energie barrière die aggregatie voorkomt" },
          { en: "Only gravity affects particle stability", es: "Solo gravedad afecta estabilidad de partículas", de: "Nur Schwerkraft beeinflusst Partikelstabilität", nl: "Alleen zwaartekracht beïnvloedt deeltjes stabiliteit" },
          { en: "Particles never interact with each other", es: "Partículas nunca interactúan entre sí", de: "Partikel interagieren nie miteinander", nl: "Deeltjes interageren nooit met elkaar" },
          { en: "Van der Waals forces are always repulsive", es: "Fuerzas van der Waals son siempre repulsivas", de: "Van der Waals Kräfte sind immer abstoßend", nl: "Van der Waals krachten zijn altijd afstotend" }
        ],
        correct: 0,
        explanation: {
          en: "DLVO (Derjaguin-Landau-Verwey-Overbeek) theory describes total interaction potential VT = VR + VA between colloidal particles. Electrostatic repulsion VR = εψ²e^(-κr) depends on surface potential (ψ), Debye length (1/κ ∝ √(ionic strength)), and dielectric constant (ε). Van der Waals attraction VA = -A/(12πr²) depends on Hamaker constant (A) and separation distance (r). At low ionic strength, high energy barrier prevents aggregation (stable cloud). Adding Ca²⁺ compresses electrical double layer (decreases κ⁻¹), reduces VR, causes flocculation. Pectin adsorption increases ψ (negative charge), enhances stability. Steric stabilization (polymer layers) adds additional repulsion. Critical coagulation concentration (CCC) for divalent cations ~10⁻³ M. Essential for understanding calcium-induced juice clarification and cloud destabilization mechanisms.",
          es: "Teoría DLVO (Derjaguin-Landau-Verwey-Overbeek) describe potencial de interacción total VT = VR + VA entre partículas coloidales. Repulsión electrostática VR = εψ²e^(-κr) depende de potencial de superficie (ψ), longitud de Debye (1/κ ∝ √(fuerza iónica)), y constante dieléctrica (ε). Atracción van der Waals VA = -A/(12πr²) depende de constante de Hamaker (A) y distancia de separación (r). A baja fuerza iónica, alta barrera de energía previene agregación (nube estable). Añadir Ca²⁺ comprime capa eléctrica doble (disminuye κ⁻¹), reduce VR, causa floculación. Adsorción de pectina aumenta ψ (carga negativa), mejora estabilidad. Estabilización estérica (capas de polímero) añade repulsión adicional. Concentración crítica de coagulación (CCC) para cationes divalentes ~10⁻³ M. Esencial para comprender clarificación de jugo inducida por calcio y mecanismos de desestabilización de nube.",
          de: "DLVO (Derjaguin-Landau-Verwey-Overbeek)-Theorie beschreibt Gesamtwechselwirkungspotential VT = VR + VA zwischen kolloidalen Partikeln. Elektrostatische Abstoßung VR = εψ²e^(-κr) hängt ab von Oberflächenpotential (ψ), Debye-Länge (1/κ ∝ √(Ionenstärke)) und Dielektrizitätskonstante (ε). Van der Waals Anziehung VA = -A/(12πr²) hängt ab von Hamaker-Konstante (A) und Trennabstand (r). Bei niedriger Ionenstärke verhindert hohe Energiebarriere Aggregation (stabile Wolke). Zugabe von Ca²⁺ komprimiert elektrische Doppelschicht (verringert κ⁻¹), reduziert VR, verursacht Flockung. Pektin-Adsorption erhöht ψ (negative Ladung), verbessert Stabilität. Sterische Stabilisierung (Polymerschichten) fügt zusätzliche Abstoßung hinzu. Kritische Koagulationskonzentration (CCC) für zweiwertige Kationen ~10⁻³ M. Wesentlich zum Verständnis calciuminduzierter Saftklärung und Wolkendestabilisierungsmechanismen.",
          nl: "DLVO (Derjaguin-Landau-Verwey-Overbeek) theorie beschrijft totale interactie potentiaal VT = VR + VA tussen colloïdale deeltjes. Elektrostatische afstoting VR = εψ²e^(-κr) hangt af van oppervlakte potentiaal (ψ), Debye lengte (1/κ ∝ √(ionsterkte)), en diëlektrische constante (ε). Van der Waals aantrekking VA = -A/(12πr²) hangt af van Hamaker constante (A) en scheidingsafstand (r). Bij lage ionsterkte voorkomt hoge energie barrière aggregatie (stabiele wolk). Ca²⁺ toevoegen comprimeert elektrische dubbellaag (vermindert κ⁻¹), vermindert VR, veroorzaakt flocculatie. Pectine adsorptie verhoogt ψ (negatieve lading), verbetert stabiliteit. Sterische stabilisatie (polymeer lagen) voegt extra afstoting toe. Kritische coagulatie concentratie (CCC) voor tweewaardig kationen ~10⁻³ M. Essentieel voor begrip van calcium-geïnduceerde sapklarering en wolk destabilisatie mechanismen."
        }
      },
      {
        question: {
          en: "What is the thermodynamic and kinetic basis for glass transition temperature (Tg) in juice concentrates and its role in stability?",
          es: "¿Cuál es la base termodinámica y cinética para temperatura de transición vítrea (Tg) en concentrados de jugo y su papel en estabilidad?",
          de: "Was ist die thermodynamische und kinetische Grundlage für Glasübergangstemperatur (Tg) in Saftkonzentraten und ihre Rolle in Stabilität?",
          nl: "Wat is de thermodynamische en kinetische basis voor glas overgangstemperatuur (Tg) in sapconcentraten en de rol in stabiliteit?"
        },
        options: [
          { en: "Tg separates glassy (T<Tg, high viscosity η>10¹² Pa·s, kinetically trapped) from rubbery state; Gordon-Taylor equation predicts Tg of mixtures", es: "Tg separa estado vítreo (T<Tg, alta viscosidad η>10¹² Pa·s, atrapado cinéticamente) de estado gomoso; ecuación Gordon-Taylor predice Tg de mezclas", de: "Tg trennt glasigen (T<Tg, hohe Viskosität η>10¹² Pa·s, kinetisch eingeschlossen) von gummiartigen Zustand; Gordon-Taylor-Gleichung sagt Tg von Mischungen voraus", nl: "Tg scheidt glasachtige (T<Tg, hoge viscositeit η>10¹² Pa·s, kinetisch gevangen) van rubberachtige toestand; Gordon-Taylor vergelijking voorspelt Tg van mengsels" },
          { en: "Glass transition is a first-order phase transition", es: "Transición vítrea es transición de fase de primer orden", de: "Glasübergang ist Phasenübergang erster Ordnung", nl: "Glas overgang is eerste-orde fase overgang" },
          { en: "Temperature has no effect on juice concentrate stability", es: "Temperatura no tiene efecto en estabilidad de concentrado de jugo", de: "Temperatur hat keinen Effekt auf Saftkonzentrat-Stabilität", nl: "Temperatuur heeft geen effect op sapconcentraat stabiliteit" },
          { en: "All concentrates have the same Tg", es: "Todos los concentrados tienen la misma Tg", de: "Alle Konzentrate haben dasselbe Tg", nl: "Alle concentraten hebben dezelfde Tg" }
        ],
        correct: 0,
        explanation: {
          en: "Glass transition at Tg is second-order thermodynamic transition where amorphous material changes from glassy (solid-like, high viscosity η>10¹² Pa·s, molecular mobility frozen) to rubbery (liquid-like, lower viscosity, mobile) state. Below Tg, juice concentrates are kinetically stable—diffusion-limited reactions (crystallization, Maillard browning, oxidation) proceed extremely slowly. Above Tg, molecular mobility increases dramatically, accelerating degradation. Gordon-Taylor equation predicts mixture Tg: 1/Tg = w₁/Tg₁ + w₂/Tg₂, where w is weight fraction. For juice: sugars (Tg ≈ -30 to 60°C), water (Tg ≈ -135°C). Storage T-Tg (typically >10°C below Tg) ensures stability. Williams-Landel-Ferry (WLF) equation relates viscosity/reaction rate to T-Tg. Critical for spray-dried powders (moisture-induced Tg depression causes caking) and frozen concentrates.",
          es: "Transición vítrea en Tg es transición termodinámica de segundo orden donde material amorfo cambia de estado vítreo (sólido, alta viscosidad η>10¹² Pa·s, movilidad molecular congelada) a gomoso (líquido, menor viscosidad, móvil). Bajo Tg, concentrados de jugo son cinéticamente estables—reacciones limitadas por difusión (cristalización, pardeamiento de Maillard, oxidación) proceden extremadamente lento. Sobre Tg, movilidad molecular aumenta dramáticamente, acelerando degradación. Ecuación Gordon-Taylor predice Tg de mezcla: 1/Tg = w₁/Tg₁ + w₂/Tg₂, donde w es fracción de peso. Para jugo: azúcares (Tg ≈ -30 a 60°C), agua (Tg ≈ -135°C). Almacenamiento T-Tg (típicamente >10°C bajo Tg) asegura estabilidad. Ecuación Williams-Landel-Ferry (WLF) relaciona viscosidad/tasa de reacción con T-Tg. Crítico para polvos secados por aspersión (depresión de Tg inducida por humedad causa apelmazamiento) y concentrados congelados.",
          de: "Glasübergang bei Tg ist thermodynamischer Übergang zweiter Ordnung, bei dem amorphes Material von glasigem (feststoffähnlich, hohe Viskosität η>10¹² Pa·s, molekulare Mobilität eingefroren) zu gummiartigem (flüssigähnlich, niedrigere Viskosität, mobil) Zustand wechselt. Unter Tg sind Saftkonzentrate kinetisch stabil—diffusionslimitierte Reaktionen (Kristallisation, Maillard-Bräunung, Oxidation) laufen extrem langsam ab. Über Tg nimmt molekulare Mobilität dramatisch zu, beschleunigt Abbau. Gordon-Taylor-Gleichung sagt Mischungs-Tg voraus: 1/Tg = w₁/Tg₁ + w₂/Tg₂, wobei w Gewichtsanteil ist. Für Saft: Zucker (Tg ≈ -30 bis 60°C), Wasser (Tg ≈ -135°C). Lagerung T-Tg (typischerweise >10°C unter Tg) gewährleistet Stabilität. Williams-Landel-Ferry (WLF)-Gleichung verknüpft Viskosität/Reaktionsrate mit T-Tg. Kritisch für sprühgetrocknete Pulver (feuchtigkeitsinduzierte Tg-Depression verursacht Verklumpung) und gefrorene Konzentrate.",
          nl: "Glas overgang bij Tg is tweede-orde thermodynamische overgang waarbij amorfe materiaal verandert van glasachtige (vast-achtige, hoge viscositeit η>10¹² Pa·s, moleculaire mobiliteit bevroren) naar rubberachtige (vloeistof-achtige, lagere viscositeit, mobiel) toestand. Onder Tg zijn sapconcentraten kinetisch stabiel—diffusie-gelimiteerde reacties (kristallisatie, Maillard bruinering, oxidatie) verlopen extreem langzaam. Boven Tg neemt moleculaire mobiliteit dramatisch toe, versnelt degradatie. Gordon-Taylor vergelijking voorspelt mengsel Tg: 1/Tg = w₁/Tg₁ + w₂/Tg₂, waarbij w gewichtsfractie is. Voor sap: suikers (Tg ≈ -30 tot 60°C), water (Tg ≈ -135°C). Opslag T-Tg (typisch >10°C onder Tg) verzekert stabiliteit. Williams-Landel-Ferry (WLF) vergelijking relateert viscositeit/reactie snelheid aan T-Tg. Kritiek voor sproeigedroogde poeders (vocht-geïnduceerde Tg depressie veroorzaakt verklontering) en bevroren concentraten."
        }
      }
    ]
  };

  // Export for use in the quiz application
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = level8;
  } else if (typeof window !== 'undefined') {
    window.level8 = level8;
  }
})();
